### ISSUE TITLE
nodejs发送json串，不加引号服务端收不到内容

### ISSUE THREAD

**Issue by xtgxiso** [googollee/go-socket.io#102]
服务器代码：
so.On("event", func(msg string) {
			log.Println("so event")
		})

客户端代码：
socket.emit('event', {aa: 'bb'}) ; 这样收不到
socket.emit('event', "{aa: 'bb'}") ; 这样才能收到

**Comment by googollee** [comment]
You can't save a map into a string.

**Comment by xtgxiso** [comment]
不知道能不能在go的socket.io库上做个处理呢？

**Comment by googollee** [comment]
You need to use map or struct to receive a JSON map.
