### ISSUE TITLE
event ack seems to interfere with new message

### ISSUE THREAD

**Issue by mob8607** [googollee/go-socket.io#103]
Hi there,

we are having troubles with the websocket connection handling in go. 

This is an excerpt of the TCP connection:

```
16:09:29.244948 IP localhost.dls-monitor > localhost.63564: Flags [P.], seq 18972:18981, ack 1982, win 12697, options [nop,nop,TS val 582690697 ecr 582690697], length 9
E..=.}@.@..............L..l.......1..1.....
".'.".'...438null
16:09:29.244978 IP localhost.dls-monitor > localhost.63564: Flags [P.], seq 18981:19376, ack 1982, win 12697, options [nop,nop,TS val 582690697 ecr 582690697], length 395
E...}.@.@..............L..l.......1........
".'.".'..~..438nullne.update",{ % valid JSON string here % }]
```

The second message leads to a socket.io disconnect, because of an invalid message format: 438nullne.update...

Normally the message should look like: ["szene.update", ...]

For us it looks like the ACK of a previously sent event is mixed up with a new event from the server: ["scene.update",{ % valid JSON string here % }]

Any idea how this could happen?

/cc @chirimoya

**Comment by erkie** [comment]
This issue is very old now so I'm closing it. Unfortunately I don't know the answer the question, so if it's still an issue please reopen the ticket. 🙈Trying to clean up the issues here.
