### ISSUE TITLE
Slow delivering

### ISSUE THREAD

**Issue by pgamaster** [googollee/go-socket.io#104]
Trying on a website with 1000 connections. But expecting very slow data delivery. On node.js working fine and very fast.

Using Access-Control-Allow-Origin because socket is on a subdomain.
Using Nginx in front.

Before that got error: http Too many open files. Tuned server for maximum opened files.

**Comment by googollee** [comment]
Try ulimit?

**Comment by pgamaster** [comment]
tried, still slow even on less connections

**Comment by DisruptiveMind** [comment]
@pgamaster just curious, what were system configurations? and how `slow` is `slow`?

**Comment by pgamaster** [comment]
Currently using node version
but the problem is here
https://github.com/googollee/go-socket.io/issues/174

**Comment by jjhesk** [comment]
yes, @googollee, what is the maximum amount of the connection that this program can make if I open all available resources to support open files. 65550 with 16 cores cpus.

**Comment by erkie** [comment]
@jjhesk one connection = one open file. How many open files linux can handle just depends on the RAM and cpu capabilities. If you increase max open files this software will handle not error. There are a couple of places that need to be changed to ensure max open files is correctly set everywhere, but if it is set correctly there is no limit.
