### ISSUE TITLE
Has anybody used this on production?

### ISSUE THREAD

**Issue by twboc** [googollee/go-socket.io#110]
I can see that this library has frequent commits but have anyone successfully used in in a production environment without any serous issues?

**Comment by AnatolyRugalev** [comment]
Interested in this question too

**Comment by polds** [comment]
We tried but found the library to be too immature. This was about 6 months ago so maybe there have been many improvements since then.

**Comment by AnatolyRugalev** [comment]
@polds thank you. We are interested in multi server usage

**Comment by DisruptiveMind** [comment]
We are using this for PESA Live (available for Android and iOS). This helps us with our custom tailored Twitter Feeds to emit to all users listening in on the room.

**Comment by YellowOrWhite** [comment]
I have found https://github.com/igm/sockjs-go/ to be more stable. But you need to write your own pub/sub and authentication library.

**Comment by m4ng0squ4sh** [comment]
Try https://github.com/desertbit/glue. Using it in production since almost one year now.

**Comment by pathbox** [comment]
I am using it for the app in my work. But something is problem.
I use mgo
The websocket connections are 1w, but the memory usage reaches 14G, it is too terrible, and I don't know why.
What could be the problem?

**Comment by osxi** [comment]
We run this in production. A simple API that blasts out WS traffic to a single page web app and it uses anywhere between 10-13 MB on a normal day. The Docker container that runs the API on Kubernetes has a 15 MB memory limit and hasn't had any issues since it's creation (about one year ago).

So I'd say yeah-- it's production ready :)
