### ISSUE TITLE
socket.disconnect() on client causes double disconnect event on server

### ISSUE THREAD

**Issue by nkovacs** [googollee/go-socket.io#112]
client-side using socket.io-client@1.4.4:

``` js
var socket = io({
    path: '/socket.io'
});

socket.on('connect', function() {
    console.log('connect');

    setTimeout(function() {
        socket.disconnect();
    }, 1000);
});

socket.on('disconnect', function() {
    console.log('disconnect');
});
```

go server:

``` go
socketserver.On("connection", func(socket socketio.Socket) {
    log.Println("socket connected")
    socket.On("disconnection", func() {
        log.Println("socket disconnected")
    })
})
```

reference nodejs server:

``` js
var io = require('socket.io')();
io.on('connection', function(socket) {
    console.log('connected');
    // for some reason this is disconnect, not disconnection
    socket.on('disconnect', function() {
        console.log('disconnected');
    });
});
io.listen(3000);
```

The go server prints:

```
socket connected
socket disconnected
socket disconnected
```

The nodejs server prints:

```
connected
disconnected
```

**Comment by nkovacs** [comment]
Looks like the problem is that the disconnect packet is received and processed, then when the loop ends [here](https://github.com/googollee/go-socket.io/blob/master/socket.go#L159), the defer function emits another disconnect packet event: https://github.com/googollee/go-socket.io/blob/master/socket.go#L111

The defer function shouldn't do this in case the loop function exited because to the disconnect packet, since that packet has already been processed.

**Comment by bkubiak** [comment]
Hello @googollee, could you merge that fix into this repo? The bug is clear and well explained by @nkovacs.

**Comment by erkie** [comment]
The code has changed significantly since this issue was created, so please open a new issue if this is still an issue. Thanks!
