### ISSUE TITLE
Please expose the Disconnect call

### ISSUE THREAD

**Issue by greenenergy** [googollee/go-socket.io#117]
There is no way right now for the server to actually disconnect. When a disconnection call is made from the client, the server doesn't actually close the socket. We need to be able to do this.

**Comment by globexdesigns** [comment]
+1

**Comment by nodecode** [comment]
+1

**Comment by j955** [comment]
+1 have any idea?

**Comment by betterjun** [comment]
+1

**Comment by anonzi** [comment]
+1

**Comment by Kay-Zee** [comment]
From the looks of it, this is possible by [emitting a disconnect event](https://github.com/googollee/go-socket.io/blob/master/socket.go#L66) from the server on the socket you want to disconnect from. That is at least how I've been handling it, and seems to be working for my use-case.
