### ISSUE TITLE
On(*, func) seems to indicate that you can have the socket passed as an arg, but this is not explained anywhere?

### ISSUE THREAD

**Issue by nfirvine** [googollee/go-socket.io#119]
https://github.com/googollee/go-socket.io/blob/b14926c0af346c1ec2ac75cfb74acad2e48b3a69/caller.go#L31-L34

makes it look like you could do something like:

``` go
so.On("message", func(Socket socketio.Socket) {
    // so == Socket
})
```

But this is undocumented.

**Comment by mrfoe7** [comment]
@nfirvine Hi. Is it actually problem?
It is old code version.
