### ISSUE TITLE
If you specify an On() handler with an empty signature, it can stall the server socket when called

### ISSUE THREAD

**Issue by nfirvine** [googollee/go-socket.io#121]
On the server:

``` go
so.On("something", func() {})
```

If the client then emits "something", `so` will be in some bad state, no longer firing handlers, but not disconnecting either.

It's possible this is actually a bug in engine.io.

The fix is to do this:

```
so.On("something", func(msg interface{}){})
```

and just ignore msg. Here's a few tests I did:
- `Emit("something")`: works
- `Emit("something", nil)`: works
- `Emit("something", nil, nil)`: causes disconnection

**Comment by nfirvine** [comment]
The fix is to do this:
```
so.On("something", func(msg interface{}){})
```
and just ignore msg. Here's a few tests I did:
* `Emit("something")`: works
* `Emit("something", nil)`: works
* `Emit("something", nil, nil)`: causes disconnection

**Comment by erkie** [comment]
Interesting bug! If this is still an issue please reopen the issue. I'm cleaning up old issues. Thanks!
