### ISSUE TITLE
how to broadcast without room?

### ISSUE THREAD

**Issue by anumantharaja** [googollee/go-socket.io#125]
How to broadcast a message to all clients without using rooms? Is this possible by using this library?
As the sample code i expecting in golang.. is this is possible by using googollee?

Ex.
// sending to all clients except sender
 socket.broadcast.emit('message', "this is a test");

**Comment by CyberLight** [comment]
Hi @anumantharaja ! 
You can create your own custom BroadcastAdaptor which implements [interface BroadcastAdaptor](https://github.com/googollee/go-socket.io/blob/7000a8a5cd56ab1c3ead7cf33de3e9b2b1906af4/adapter.go
)
And inside method ```Send``` you can check for ```*``` (star symbol). if "star symbol" found then you can enumerate all rooms registered inside your custom BroadcastAdaptor for notifying all sockets in all rooms.

For applying your custom adaptor, please use ```server.SetAdaptor(instance of your adaptor)```.
    * ```server``` - it's instance of ```socketio.Server``` created by ```socketio.NewServer()``` constructor 

May be my answer can be helpfull :)
