### ISSUE TITLE
go-socket.io will update? 

### ISSUE THREAD

**Issue by j955** [googollee/go-socket.io#126]
I very much hope go-socket.io will be updated. The current function is still relatively small, but with a lot of go-socket.io performance has been better than the nodejs of socket.io

**Comment by CyberLight** [comment]
My be! But @googollee seems to disappear somewhere and abandoned the project, 
maybe I'm wrong :)
If it's true then perhaps we ourselves should implement new features in our github repos

**Comment by CyberLight** [comment]
@j955 What features would you like to implement in **go-socket.io** ? :) May be i can help to implement this features :)

**Comment by j955** [comment]
thx ~ I found some bug
1. I'm try  IE browsers  (eg. IE8 ,  IE9)  input  Chinese characters , IE browsers is not work. 
may be IE8, IE9 cat not use websocket protocol?
2. Multiple protocol connect  go server (eg. polling, websocket), connect over ten thousand people
send the message will be a big delay, about 10-30 second, but only use websocket protocol connect 
fifty thousand use 1second.

so I hope you can help solve ^_^

**Comment by danielfbm** [comment]
@j955 I think your are not really understanding what each part does. Browser implementation has to do with the socket.io JavaScript library and should be reported there.
For the second big, this could be a implementation issue or a infrastructure problem. Try to implement the same thing in Node.JS and let us know how it works.

My guess is that you are reaching the limit of your hardward and should expand your server capacity by adding new servers to the deployment etc...

**Comment by danielfbm** [comment]
@CyberLight regarding the update, I think that just implement all features like Node.js should suffice. As I can see in other issues there seems to be some features lacking or unexpected behavior

**Comment by googollee** [comment]
@j955 

> 1. I'm try IE browsers (eg. IE8 , IE9) input Chinese characters , IE browsers is not work. 

I think you are better to check js client. Browser's feature is beyond server capable. But polling model should work.

> 2. Multiple protocol connect go server (eg. polling, websocket), connect over ten thousand people send the message will be a big delay

Could you minimum business logic and benchmark it? It's hard to say with little information.

**Comment by holygeek** [comment]
> thx ~ I found some bug
> 1. I'm try IE browsers (eg. IE8 , IE9) input Chinese characters , IE browsers is not work. 
> may be IE8, IE9 cat not use websocket protocol?

I had similar problem - unicode don't play well on on websocket for those browsers. I worked around it by manually encoding (base64) all the payload, so I send only strings instead of javascript objects.

**Comment by CyberLight** [comment]
@holygeek interesting :) Can you give me an example of your data, I can test on IE using current version of go-socket.io?

**Comment by holygeek** [comment]
@CyberLight for my case I used the unicode sample text from this page (it contains Swedish unicode letters): http://sv.lipsum.com/

**Comment by im-kulikov** [comment]
> @j955 What features would you like to implement in go-socket.io ? :) May be i can help to implement this features :)

@CyberLight how about middleware? I can't find how to implement like this (nodejs example) - http://socket.io/docs/migrating-from-0-9/

or mb some like this - https://www.npmjs.com/package/socket.io-events
