### ISSUE TITLE
Please tag and version this project

### ISSUE THREAD

**Issue by jredville** [googollee/go-socket.io#133]
Tags and versions aid in packaging for things like .deb files, and for anyone wanting to use Glide and other version based package managers to version their dependencies. It would also help ensure that if you make a breaking change, we don't pull it down until we are ready.

**Comment by fuel-shea** [comment]
Would it make sense to tie the versioning to the Javascript implementation? (Currently v1.4.5)

**Comment by jredville** [comment]
I think that would make total sense






On Thu, Jul 14, 2016 at 8:30 PM -0400, "Shea Clare" <notifications@github.com> wrote:












Would it make sense to tie the versioning to the Javascript implementation? (Currently v1.4.5)

**Comment by erkie** [comment]
This is now done if I understand correctly. :)
