### ISSUE TITLE
pingLoop reclose channel panic

### ISSUE THREAD

**Issue by zs1379** [googollee/go-socket.io#134]
panic: close of closed channel

goroutine 575796 [running]:
panic(0x7f59a0, 0xc8b1edc710)
    /usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/googollee/go-engine%2eio.(_serverConn).OnClose(0xc8d31ca9c0, 0x7f780ff80178, 0xc8d36f3c40)
    /data/html/live_im_system/src/github.com/googollee/go-engine.io/server_conn.go:257 +0x1a2
github.com/googollee/go-engine.io/polling.(_Polling).Close(0xc8d36f3c40, 0x0, 0x0)
    /data/html/live_im_system/src/github.com/googollee/go-engine.io/polling/server.go:67 +0x115
github.com/googollee/go-engine%2eio.(_serverConn).Close(0xc8d31ca9c0, 0x0, 0x0)
    /data/html/live_im_system/src/github.com/googollee/go-engine.io/server_conn.go:176 +0x217
github.com/googollee/go-engine%2eio.(_serverConn).pingLoop(0xc8d31ca9c0)
    /data/html/live_im_system/src/github.com/googollee/go-engine.io/server_conn.go:384 +0x416
created by github.com/googollee/go-engine%2eio.newServerConn
    /data/html/live_im_system/src/github.com/googollee/go-engine.io/server_conn.go:112 +0x58e

**Comment by ammario** [comment]
Same problem

**Comment by Jumla** [comment]
+1

**Comment by majintao** [comment]
https://github.com/googollee/go-socket.io/issues/190    is the same problem

@googollee

**Comment by erkie** [comment]
@majintao or anyone else in this thread, you can check/help out my debugging journey here: https://github.com/googollee/go-engine.io/issues/53

**Comment by erkie** [comment]
As this is a go-engine.io issue I am closing this issue. Please continue journey on the linked issue above. Thanks!
