### ISSUE TITLE
Namespace isn't working 

### ISSUE THREAD

**Issue by douglasmakey** [googollee/go-socket.io#138]
My namespace isn't working with this code, someone knows why?

``` go
//Server 
    server, err := socketio.NewServer(nil)
    if err != nil {
        log.Fatal(err)
    }

    profile := server.Of("/profile")

    profile.On("connection", func(so socketio.Socket) {
        log.Print("Connect NSP:PROFILE")
    })

    server.On("connection", func(so socketio.Socket) {
        log.Print("CONNECT DEFAULT")
    })
```

``` html
//Client
<script>
    console.log("Err:")
    var socket = io("http://localhost:5000");
    socket.on('news', function (data) {
        console.log(data);
        socket.emit('my other event', { my: 'data' });
    });

    var socket2 = io("http://localhost:5000/profile");
    socket2.on('connect', function() {
        socket2.emit('authorization', "user1");
    })
</script>
```

OUTPUT:

> 2016/07/26 17:32:44 CONNECT DEFAULT
> 2016/07/26 17:32:44 CONNECT DEFAULT

**Comment by alexkarpovich** [comment]
+1

**Comment by kagtaviy** [comment]
+1

**Comment by bughou** [comment]
+1

**Comment by geoffatcircle** [comment]
+10

**Comment by dcormier** [comment]
Possibly related to #59.

**Comment by agbaraka** [comment]
+1

**Comment by agbaraka** [comment]
I think I figured out the problem. I notice that "Namespace" interface did not implement a "On" method. So when you call "On" there is no method to handle that call. I might be wrong :)
[https://github.com/googollee/go-socket.io/blob/master/namespace.go](url)

**Comment by dcormier** [comment]
The `namespace` type composes `*baseHandler`, which has [On](/googollee/go-socket.io/blob/master/handler.go#L24)

**Comment by JuanjoA** [comment]
Maybe someone can help with this tip, how to work with namespaces?
Thx.

**Comment by EwanValentine** [comment]
Is this codebase maintained anymore? Can't get namespaces/rooms to work at all unfortunately.

**Comment by googollee** [comment]
please try v1.4

**Comment by MattDrummy** [comment]
So after working on this, I found a solution that works well for me.  Basically upon setting the socket, you send an emit to the server with the name of the room you wish to join.  On the server, you use a so.On("open") to take the name of the room and the name of the user and do a so.Join() to add the user to the room.  On the client, you don't have to do anything special for the socketFor, and it effectively creates the same effect as using a namespace.

```foo.On("connection", func(so socketio.Socket) {
    so.On("open", func(user [2]string){
      fmt.Println(user[0] + " connected to " + user[1])
      so.BroadcastTo(user[1], "message", user[0] + " connected to " + user[1])
      so.Join(user[1])
    })
    so.On("message", func(msg [2]string) {
      fmt.Printf("%+v\n", msg)
      so.Emit("message", msg[1])
      so.BroadcastTo(msg[0], "message", msg[1])
    })
    so.On("disconnection", func() {
      fmt.Println("on disconnect")
    })
  })
  foo.On("error", func(so socketio.Socket, err error) {
    log.Println("error:", err)
  })```
