### ISSUE TITLE
HTTP request cross domain，No set function on Response Origin

### ISSUE THREAD

**Issue by mrkt** [googollee/go-socket.io#140]
HTTP request cross domain，No set function on Response Origin

**Comment by netzadel** [comment]
Hey!

You need to implement your own custom server to set the origin header like:

type customServer struct {
	Server *socketio.Server
}

func (s *customServer) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Access-Control-Allow-Credentials", "true")
	origin := r.Header.Get("Origin")
	w.Header().Set("Access-Control-Allow-Origin", origin)
	s.Server.ServeHTTP(w, r)
}

        serverio := configureSocketIO()
        wsServer := new(customServer)
        wsServer.Server = serverio

	http.Handle("/socket.io/", wsServer)
	http.ListenAndServe(":8081", nil)


configureSocket method is something like:

func configureSocketIO() *socketio.Server {
	server, err := socketio.NewServer(nil)
	if err != nil {
		log.Fatal(err)
	}
	server.On("connection", func(so socketio.Socket) {
		custLog("new socket conneted to host: "+so.Id(), nil)

		so.On("disconnection", func() {
			log.Println("on disconnect")
		})
	})
	server.On("error", func(so socketio.Socket, err error) {
		log.Println("error:", err)
	})

	return server
}


hope that helps.

**Comment by EsSpricht** [comment]
I have an example how to configure origin headers: https://github.com/EsSpricht/GolangBoilerplate/blob/master/googollee's%20socket.io/server.go

cheers
