### ISSUE TITLE
XHR poll error : Connection Refused

### ISSUE THREAD

**Issue by AhmedX6** [googollee/go-socket.io#143]
Hello,

I have a local server in Golang which implements socket :

```
`server, err := socketio.NewServer(nil)
if err != nil {
    log.Fatal(err)
}

server.On("connection", func(so socketio.Socket) {
    fmt.Println(so.Id())
})

server.On("error", func(so socketio.Socket, err error) {
    fmt.Println("error:", err)
})
    http.Handle("/", server)
log.Fatal(http.ListenAndServe(":5000", nil))`
```

I have an android app which uses 'io.socket:socket.io-client:0.7.0'

```
           `try {
            IO.Options options = new IO.Options();
            options.forceNew = true;
            options.reconnection = true;
            options.timeout = 20000;
            options.port = 5000;

            socket = IO.socket("http://192.168.0.50:5000/", options); //ip of my computer
            socket.connect();
        } catch (URISyntaxException e) {
            e.printStackTrace();
        }`
```

It makes me an xhr poll error : java.net.ConnectException: failed to connect to /192.168.0.50 (port 5000) after 10000ms: isConnected failed: ECONNREFUSED (Connection refused)

Can you tell me why ? Maybe the two library are not compatible ??... I have no idea..

Thank you !

**Comment by KristinaEtc** [comment]
@AhmedX6 Hi, did you get what's the problem of this error?

**Comment by AhmedX6** [comment]
@KristinaEtc I forgot ... It was a long time ago now... I fixed the issue. I added cors, here is my last code :
```
c := cors.New(cors.Options{ 
		AllowedOrigins:   []string{"*"}, 
	AllowedMethods:   []string{"GET", "POST", "PUT", "DELETE"}, 
 		AllowCredentials: true, 
 	}) 
 
 
 	http.Handle("/socket.io/", c.Handler(server)) 
	log.Println("Serving at localhost:5000...") 
	log.Fatal(http.ListenAndServe(":5000", nil)) 

```
On Android like this :

```
try { 
                 IO.Options options = new IO.Options(); 
                options.forceNew = true; 
                 options.reconnection = true; 
                 options.port = 5000; 
                 options.multiplex = true; 
 
 
                 socket = IO.socket(ip, options); 
                 socket.connect(); 
               checkListenersForBroadcast(); 
            } catch (URISyntaxException e) { 
                 e.printStackTrace(); 
             } 

```

And that's it ... It worked...

**Comment by guptaaashutosh** [comment]
![image](https://github.com/googollee/go-socket.io/assets/83817233/119eafcc-99b5-4b02-90b9-60617d3db7fb)

socketServer, err := socketio.NewServer(&engineio.Options{
		Transports: []transport.Transport{
			&websocket.Transport{
				CheckOrigin: func(r *http.Request) bool {
					return true
				},
			},
		},
	})

srv := &http.Server{
		Addr:        port,
		Handler:     route.InitializeRouter(dbConn, redisClient, socketServer),  //  this function contain socketEvent functions
		IdleTimeout: 10 * time.Minute,
		ReadHeaderTimeout: 30 * time.Second,
	}

go socketServer.Serve()
	defer socketServer.Close()

	log.Println("Server Started on Port", port)
	log.Fatal(srv.ListenAndServe())
