### ISSUE TITLE
How use room's in go-socket.io?

### ISSUE THREAD

**Issue by kagtaviy** [googollee/go-socket.io#144]
Hi, i don't understand how i can use room's in socket.io?

**Comment by guidiego** [comment]
@kagtaviy A room is a kind of "flag" into a `socket connection` you can gave N rooms for a socket connection use `so.Join("nameOfRoom")`. After do that yo ucan use `BroadcastTo` to `Emit` an event for every people that have this Room registered in you Socket Connection :D
