### ISSUE TITLE
Memory leak prolem

### ISSUE THREAD

**Issue by aiden0z** [googollee/go-socket.io#145]
We have a service based on go-socket.io and have a memory leak problem. We found the memory usage is always increase, the idle heap is not return back to the OS. The heap pprof show that the runtime.goexit took much memory,  seems  that the memory not release after the goroutine exit. 

- heap in-use callgraph

https://lh3.googleusercontent.com/-mOinFHs1gmM/V854u84GSMI/AAAAAAAAAFI/Dz7zJN6hobsrhRDBTfE__iR-AXp-rpxkACLcB/s1600/comet_inuse_heap.png

- heap alloc callgraph

https://lh3.googleusercontent.com/-zriittHlglE/V8542kygEqI/AAAAAAAAAFM/BojzIQ73zy0XbkrNeU4LX7dUAjC6T0ipQCLcB/s1600/comet_alloc_heap.png

I also open a topic in google-nuts group, more detail you can see https://groups.google.com/forum/#!topic/golang-nuts/h2YObrIw7Fg.

**Comment by googollee** [comment]
Thanks. I saw the topic and try to find out now.

**Comment by aiden0z** [comment]
@googollee  thanks so much. Is any update?

**Comment by googollee** [comment]
@aiden0z 

I'm busy on rewrite engine.io now. Could you help to review the new code at https://github.com/googollee/go-engine.io/tree/1.4? It's focus on memory usage and speed.

1.4 branch is under developing and not finish yet. The demo/server.go can run but may have some issue if reading/writing message while upgrading.

Thank you.

**Comment by aiden0z** [comment]
@googollee  I finally fixed the memory leak problem. It is not bug of go-socket.io.

I use the https://github.com/auth0/go-jwt-middleware to auth with JWT. I also open the KeepContext of gorilla mux router to true for that can get the jwt token of  request from the goriila context. When I get the jwt token, will clear the request context (via context.Clear(r))  immediately. So far, all is work correctly. But when the go-jwt-middleware auth failed there is no chance to clear the request context because KeepContext of mux has been to true. This is the root cause.
