### ISSUE TITLE
support cluster?

### ISSUE THREAD

**Issue by arden** [googollee/go-socket.io#149]
can support cluster?

**Comment by im-kulikov** [comment]
+1

**Comment by qrpike** [comment]
+1

**Comment by googollee** [comment]
Yes. I'm doing new version of go-socket.io which will support cluster with a Room interface which you can custom for cluster usage. I will add details some days later.

Will you describe your target usage of cluster? I want to make sure it's OK for product environment.

**Comment by hadv** [comment]
It seems similar to socket.io-redis

https://github.com/socketio/socket.io-redis

**Comment by balintant** [comment]
@googollee What's the state of this?

I don't know how much you want to change for that. You mentioned "new version", which feels to me like a major update.

If that's not the case and PRs are welcome, I might implement this.

**Comment by googollee** [comment]
Yes it's a major update. You can find code on v1.4 branch, which is kind of working, but not stable and lack of testing.

**Comment by balintant** [comment]
@googollee so I can jump in and decrease that lack of testing ;)

**Comment by googollee** [comment]
@balintant Thank you.

I just fix a race when upgrading. Now the example should run OK if you use latest go-engine.io and go-socket.io in v1.4.

IMO, cluster-support should be separated from socketio, focusing on broadcasting between multi-node. It can register a receiver with key, then broadcast a message to all receiver registered. It should abstract an interface, which let user custom their backend implement.

**Comment by balintant** [comment]
I will try to free some time up next week, so I can go through [go-engine.io] and [v1.4].

[go-engine.io]: https://github.com/googollee/go-socket.io
[v1.4]: https://github.com/googollee/go-socket.io/tree/v1.4

**Comment by balintant** [comment]
@googollee ah, I just realized what you said. Your solution sounds better. ;) 

I will have time on the week of 30th. That discussion would be great. Maybe on some IM kinda place like [Gitter][gitter]?

[gitter]: https://gitter.im

**Comment by googollee** [comment]
Sure. I use Telegram & wechat if you like them. You can find @googollee to reach me. Or you can find me on Hangouts & iMessage with i@googol.im.

Gitter seems a kind of Slack. Do you have a group already? What's that group for?

**Comment by balintant** [comment]
@googollee Gitter is based on GitHub. So your projects can have their own channels basically. It's pretty nice 😊

**Comment by lincanli** [comment]
Hi, any update on this issue? I downloaded v1.4 version of go-socket and go-engine and have no idea to to setup cluter

**Comment by balintant** [comment]
@lincanli I happened to lose the time I could have invest in this. I'm planning to get back to this as soon as possible.

**Comment by niocncn** [comment]
a is there any updates?

**Comment by erkie** [comment]
@niocncn sorry no! I'll close this issue and refer to the https://github.com/googollee/go-socket.io/issues/64 for discussion on clustering/scaling up.
