### ISSUE TITLE
Connect two servers.

### ISSUE THREAD

**Issue by gamest1** [googollee/go-socket.io#156]
Is it possible to connect two backends using this library or must the client connect to the GoLang server from a Javascript environment?

**Comment by gamest1** [comment]
It seems someone created a client version:
github.com/zhouhui8915/go-socket.io-client
Is this an official effort?

**Comment by googollee** [comment]
Yes. I plan to release a client with new version of go-socket.io. Working on it now.

**Comment by elvizlai** [comment]
@googollee  Thanks for great job. Is there any schedule or roadmap?

**Comment by googollee** [comment]
I have done the go-engine.io and parser of go-socket.io. I'm working on dispatcher. Hope whole go-socket.io can finished this year.

go-engine.io already have the client part. So I think it's easy to do go-socket.io client based on it.

**Comment by danielfbm** [comment]
@googollee will the API be much different from this one? I am planning to start using this library, but I need something that would not have breaking changes once I replace if your new library...

thanks for your work and time

**Comment by googollee** [comment]
API will change. You can find code on v1.4 branch, which is kind of working, but not stable and lack of testing.

**Comment by googollee** [comment]
@danielfbm I just fix a race when upgrading. Now the example should run OK if you use latest go-engine.io and go-socket.io in v1.4.

**Comment by danielfbm** [comment]
@googollee thanks, I will test it this weekend.

Let me know if you need any help on the development. I want to use this in production so I might help you with some coding as well!

微信：danielfbm

**Comment by erkie** [comment]
@danielfbm if you're still interested we need help :D
