### ISSUE TITLE
Why does connection event fire twice?

### ISSUE THREAD

**Issue by tastywheat** [googollee/go-socket.io#157]
When a client connects, the `connection` event is firing twice. Is this expected?

```
       server.On("connection", func(so socketio.Socket) {
		log.Println("on connection", server.Count())
	})
```

**Comment by producerism** [comment]
if you nstat, can you see whether or not there are actually two connections and not just one?

**Comment by wahello** [comment]
```
server.OnConnect("/", func(s socketio.Conn) error {
}
```
is called twice.

**Comment by erkie** [comment]
@boshenglee what version of socket.io are you using? This library does not support socket-io 4
