### ISSUE TITLE
Socket IO Connection fails

### ISSUE THREAD

**Issue by AhmedX6** [googollee/go-socket.io#158]
Hello,

I just copied and pasted the sample code on the readme.

I'm using Socket IO Tester (a Google Chrome plugin to test the socket). It seems that I can't connect to the socket correctly, this message appears "An error occured while reconnecting"
In the log I got the "on connection" but I can't connect to the socket.
![screenshot from 2016-11-19 19-59-20](https://cloud.githubusercontent.com/assets/13573148/20457775/c2c19648-ae92-11e6-9416-22cf59922988.png)

Can someone help me ?
Thank you!

**Comment by NikosEfthias** [comment]
same here i cant connect at all

**Comment by AhmedX6** [comment]
I solved this with Cors !
