### ISSUE TITLE
server disconnects client after emitting message

### ISSUE THREAD

**Issue by aksentyev** [googollee/go-socket.io#159]
server:
```go
Server.On("connection", func (so socketio.Socket, err error) {
        Logger.Infof("Connected: %v ", so.Id)
        so.On("event", func(msg string) {
            Logger.Info("event ", msg)
            so.Emit("event:resp", `{"data": "data"}`)
        })
        so.On("disconnection", func() {
            Logger.Info("on disconnect")
        })
    })
```

Socket.io-client v1.6.0 and 1.3.7 was tested and has the same behavior.
socket.io's native js implementation doesn't have this problem.

Maybe anyone have the same issue?

**Comment by loint** [comment]
Same issue !!

**Comment by parhamdb** [comment]
if you emmit json from client, this happens.
it is all ok if you are just sending strings. so just JSON.stringify before sending to server
