### ISSUE TITLE
long connection and then appear upgrading  

### ISSUE THREAD

**Issue by BlackCodes** [googollee/go-socket.io#162]
we use go-socket.io in my project. client connection is normal, But send many messages or later one hour.The socket.io appear  "upgrading" Error. we also can't send message. There isn't  discount hint. It's looks like socket also normal. We want to get help and how to resolve this question? 
Many thanks!

**Comment by pgamaster** [comment]
+1 getting "upgrading" Error

**Comment by googollee** [comment]
Which version?

**Comment by erkie** [comment]
This issue is pretty old, so closing. If you have more info and it still an issue please feel free to reopen with that. Thanks!
