### ISSUE TITLE
v1.4 OnConnect() not triggering

### ISSUE THREAD

**Issue by stverhae** [googollee/go-socket.io#166]
I was checking the impact of v1.4 conversion on my code when I noticed the OnConnect never triggers.
I ran the example in the 1.4 branch and noticed the same issue. Even if you put  a panic in the OnConnect handler, nothing happens. Major breaking issue for us.

**Comment by tpoxa** [comment]
Same here. Have you found any solution?

**Comment by stverhae** [comment]
Nope, I just went back to using the old version as I didn't trust the v1.4 version at this stage yet. You can fork and hack in the fix, but for us that kind of defeats the purpose of upgrading. Tried to make a clean fix so I could submit a PR, but was unsure where to do that since the relevant code still seems to be in a transition fase between the old master code and v1.4.
Hopefully this gets fixed soon!

**Comment by googollee** [comment]
Thank you @stverhae. Could you try again?

**Comment by stverhae** [comment]
@googollee Thanks, the onConnect handler works well in the example code now!
Could you shed some light on the state of the v1.4 branch? how production ready is it, and would you recommend people to upgrade at this point?

**Comment by tpoxa** [comment]
Thank you for update. On connect event works now. But what about onDisconnect?
Should I see "closed" message after I close the page?

**Comment by googollee** [comment]
@tpoxa Currently, if you close socketio connection in js, the server will receive disconnect event, otherwise, the server will receive an error.

**Comment by fooevr** [comment]
I close socket.io connection in js, but OnDisconnect and OnError  event is not trigger.
go-socket.io version is v1.4. can you fix it? thanks.

**Comment by googollee** [comment]
@fooevr could you give me any example code?

**Comment by tangxinfa** [comment]
> @tpoxa  Currently, if you close socketio connection in js, the server will  receive disconnect event, otherwise, the server will receive an error.
@googollee Sadly the OnError callback just pass a error object, no conn provide, so i can't figureout which connection disconnected
