### ISSUE TITLE
concurrent map read and map write

### ISSUE THREAD

**Issue by fromiuan** [googollee/go-socket.io#170]
请问在并发下，发送广播，会不会造成map读写问题
`goroutine 1237 [running]:`
`runtime.throw(0xee03c0, 0x21)`
`	/usr/local/go/src/runtime/panic.go:547 +0x90 fp=0xc820aa2b98 sp=0xc820aa2b80
runtime.mapaccess1_faststr(0xd29f00, 0xc8203a4b70, 0xc820b17600, 0x13, 0xc820b17600)`
`	/usr/local/go/src/runtime/hashmap_fast.go:202 +0x5b fp=0xc820aa2bf8 sp=0xc820aa2b98
github.com/googollee/go-socket%2eio.broadcast.Send(0xc8203a4b70, 0x7f95568353d0, 0xc8207c8a50, 0xc820b17600, 0x13, 0xe22e00, 0xf, 0xc820b9e670, 0x1, 0x1, ...)`
`	/root/go/src/github.com/googollee/go-socket.io/adapter.go:49 +0x72 fp=0xc820aa2ce0 sp=0xc820aa2bf8github.com/googollee/go-socket%2eio.(*socketHandler).BroadcastTo(0xc820824360, 0xc820b175e0, 0x12, 0xe22e00, 0xf, 0xc820b9e670, 0x1, 0x1, 0x0, 0x0)`
`	/root/go/src/github.com/googollee/go-socket.io/handler.go:120 +0x137 fp=0xc820aa2d78 sp=0xc820aa2ce0weserver/src/socket.Chatprogram.func1.1(0xc8208fefc0, 0x1a1)`
`	/root/go/src/weserver/src/socket/chat_socket.go:115 +0x1ccb fp=0xc820aa35c0 sp=0xc820aa2d78
runtime.call32(0xc820390380, 0xc820824460, 0xc820a33790, 0x1000000010)`
`	/usr/local/go/src/runtime/asm_amd64.s:472 +0x3e fp=0xc820aa35e8 sp=0xc820aa35c0
reflect.Value.call(0xb58a40, 0xc820824460, 0x13, 0xe06f98, 0x4, 0xc8206cde20, 0x1, 0x1, 0x0, 0x0, ...)`
`	/usr/local/go/src/reflect/value.go:435 +0x120d fp=0xc820aa3938 sp=0xc820aa35e8
reflect.Value.Call(0xb58a40, 0xc820824460, 0x13, 0xc8206cde20, 0x1, 0x1, 0x0, 0x0, 0x0)`
`	/usr/local/go/src/reflect/value.go:303 +0xb1 fp=0xc820aa3998 sp=0xc820aa3938
github.com/googollee/go-socket%2eio.(*caller).Call(0xc82085f440, 0x7f95568353d0, 0xc8207c8a50, 0xc8209571c0, 0x1, 0x1, 0x0, 0x0, 0x0)`
`	/root/go/src/github.com/googollee/go-socket.io/caller.go:81 +0x6c3 fp=0xc820aa3b50 sp=0xc820aa3998
github.com/googollee/go-socket%2eio.(*socketHandler).onPacket(0xc820824360, 0xc820aa3f20, 0xc820aa3ee8, 0x0, 0x0, 0x0, 0x0, 0x0)`
`	/root/go/src/github.com/googollee/go-socket.io/handler.go:165 +0x37a fp=0xc820aa3d20 sp=0xc820aa3b50
github.com/googollee/go-socket%2eio.(*socket).loop(0xc8207c8a50, 0x0, 0x0)`
`	/root/go/src/github.com/googollee/go-socket.io/socket.go:135 +0x3d3 fp=0xc820aa3f68 sp=0xc820aa3d20`
github.com/googollee/go-socket%2eio.(*Server).loop.func1(0xc8207c8a50)
`	/root/go/src/github.com/googollee/go-socket.io/server.go:103 +0x21 fp=0xc820aa3f88 sp=0xc820aa3f68`
`runtime.goexit()`
`	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc820aa3f90 sp=0xc820aa3f88
created by github.com/googollee/go-socket%2eio.(*Server).loop
	/root/go/src/github.com/googollee/go-socket.io/server.go:104 +0xfc`

**Comment by googollee** [comment]
Which version? Example code?

**Comment by fromiuan** [comment]
sorry , The project has been abandoned，so i not code ,i will close the question
