### ISSUE TITLE
Unable to set Headers to allow remote connections

### ISSUE THREAD

**Issue by mihok** [googollee/go-socket.io#179]
I've been unable to get 1.4 to work properly. 

It looks like the ServeHTTP connection is trying to write its own headers and therefore I cannot set Access-Control-Allow-Origin headers.

Any help would be greatly appreciated (awesome work on this lib)

**Comment by kamildrazkiewicz** [comment]
I had been struggling with the same issue and I found solution which is very simple. You just need to pass ResponseWriter Headers to websocket.Upgrade() method. 

Here's a code and PR (@googollee):
https://github.com/googollee/go-engine.io/pull/51

After that, you will be able to set `"Access-Control-Allow-Origin"` header on your connection handler.

**Comment by erkie** [comment]
@googollee do you remember why you closed this issue? The PR that @kamildrazkiewicz seems very relevant to the master branch at least.

**Comment by googollee** [comment]
IMO, it's better to wrap a ServeHTTP() and handle headers in the wrapper. It always work well to me, and I can't find any benefit by adding a API to update headers.

Some similar issues: #33, #46, #70.
