### ISSUE TITLE
Cant install v1.4

### ISSUE THREAD

**Issue by AStaroverov** [googollee/go-socket.io#181]
Hi, I'm new to the world of go, and I do not understand how to install a package of a certain version.
Im try 
```
go get gopkg.in/googollee/go-socket.io.v1
```
and result was
```
package github.com/googollee/go-socket.io/parser: cannot find package "github.com/googollee/go-socket.io/parser" in any of:
	/usr/local/go/src/github.com/googollee/go-socket.io/parser (from $GOROOT)
	/home/hellbeast92/go/src/github.com/googollee/go-socket.io/parser (from $GOPATH)
```
I tried to use dep and I also failed.
What i should do for install go-socket.io v1.4?

**Comment by juanvallejo** [comment]
If using gopk.in does not work, you could just try cloning the repo with `-b v1.4` to `$GOPATH/src/github.com/googollee/go-socket.io`

`$ git clone -b v1.4 https://github.com/googollee/go-socket.io $GOPATH/src/github.com/googollee/go-socket.io`

**Comment by AStaroverov** [comment]
Ok, i can use it for devolop at local machine,but if i want use it for
every day automatically deploy?
Mb u can say when 1.4 will be merge to master?

чт, 22 июня 2017 г., 0:53 Juan Vallejo <notifications@github.com>:

**Comment by googollee** [comment]
I don't understand what's the meaning of automatically deploying.

Because v1.4 is not compatible with the master, I don't have any plan to merge them. If I want to do it, I will use the master branch as developing branch, and move all releases to their branches separately.
