### ISSUE TITLE
so.Emit not delivering message, keep stuck with Upgrading error

### ISSUE THREAD

**Issue by LFerrolho** [googollee/go-socket.io#183]
<pre>
package main

var waitingQueue []Connection
var curConnections = make(map[string]Connection)

var gameID = 0

type Connection struct {
	Socket    socketio.Socket
	Username  string
        GameState *GameState
}

func main() {
	server, err := socketio.NewServer(nil)
	if err != nil {
		log.Fatal(err)
	}

	quit := make(chan struct{})
	go matchPlayers(quit)

	server.On("connection", func(so socketio.Socket) {
		log.Println("connection")

		username, err := checkUserSession(so)
		if err != nil {
			so.Emit("disconnect")
		}

		log.Println("connected")

		so.On("join queue", func() {
			if _, ok := curConnections[username]; !ok {
				conn := Connection{Socket: so, Username: username}
				waitingQueue = append(waitingQueue, conn)
				curConnections[username] = conn 
				log.Println("joining queue")
			}
		})

		so.On("make a move", func(data string) {
                        // Another code goes here
		})

		so.On("disconnection", func() {
			log.Println("on disconnect")
		})

	})

	server.On("error", func(so socketio.Socket, err error) {
		log.Println("error:", err)
	})

	r := mux.NewRouter()

	r.Handle("/socket.io/", server)

	c1 := handlers.AllowedOrigins([]string{"http://localhost:8080"})
	c2 := handlers.AllowCredentials()

	log.Println("Serving at localhost:5001...")
	log.Fatal(http.ListenAndServe(":5001", handlers.CORS(c1, c2)(r)))
}

func matchPlayers(quit chan struct{}) {
	ticker := time.NewTicker(2 * time.Second)
	for {
		select {
		case <-ticker.C:
			log.Println("MatchMacking the players")
			log.Println(len(waitingQueue))

			if len(waitingQueue) >= 2 {

				player1 := waitingQueue[0]
				waitingQueue = waitingQueue[1:]

				player2 := waitingQueue[0]
				waitingQueue = waitingQueue[1:]

				gameName := "Game" + strconv.Itoa(gameID)
				gameID++

				gameState := newGameState(gameName, []Connection{player1, player2})

				player1.Socket.Join(gameName)
				player2.Socket.Join(gameName)

				gameState.Started = true

				for _, conn := range gameState.Players {
					log.Println("JOINING GAME")
					<b>err := conn.Socket.Emit("join game")
					if err != nil {
						log.Println(err) //Keep getting Upgrading error here 
					}</b>
				}
			}

		case _, ok := <-quit:
			if !ok {
				return
			}

			ticker.Stop()
			close(quit)
			return
		}
	}
}
</pre>

Hi, I'm getting an Upgrading Error in that piece of code that is in bold, where I try to emit the "join game" event to clients.
The basic idea is to have a goroutine in parallel with the socketio server that checks periodically if there are enough players to start a new game (basic matchmaking queue). The other events of server, such as "join queue" and "disconnect" are working normally.
I'm using the fixed version of go-engine.io [solved here](https://github.com/googollee/go-socket.io/issues/53) .
Any idea?

**Comment by googollee** [comment]
Could you try the branch v1.4? It fixed a lot of this kind issues.

**Comment by LFerrolho** [comment]
I ended up using nodejs socket.io version. But I'll try later v1.4 and give you feedback

**Comment by mrfoe7** [comment]
@LFerrolho Hi
Are you tested new version v1.4 go-socket.io in your game server?

If version v1.4 Emit interface is 
```go
func (c *namespaceConn) Emit(event string, v ...interface{})
```

But if you wanna use Emit i shout use by *conn.Socket.Emit("reply", "join game")*
