### ISSUE TITLE
Authorizing socket connection using JWT

### ISSUE THREAD

**Issue by kuzzmi** [googollee/go-socket.io#185]
Hi! It's not an issue by itself, but I struggle with understanding of how to implement the following behavior with `go-socket.io`.

In the official Node.js version, you have access to query string that was used by a client to establish the connection. This way one can pass JWT using the connection string, e.g.:

```
http://localhost:3000?access_token=${access_token}
```

And in the `connection` event handler one can get this information and authorize a user's connection.

I don't see a way of how this could be done using this implementation. Are there any tips or ready-to-go solutions for such cases?

Thanks in advance!

**Comment by bhargavpanth** [comment]
I tweaked around a little and found a way to fetch the JWT token in the `so.On("connection"...)` handler. According to the socket.io [doc](https://socket.io/docs/client-api/) passing the token like 
```
const socket = io({
  query: {
    token: 'cde'
  }
});
``` 
appends the token in the query parameter. So, you can access the JWT token within the 
```
socket.On("connection", func(so socketio.Socket) {
  // "so" is a request Object
  jwtToken := so.Request().URL.Query()["token"][0]
  fmt.Println(" Token here..",jwtToken)
})
``` 
You can then pass this on to your `JWT` function to validate it
