### ISSUE TITLE
panic: send on closed channel

### ISSUE THREAD

**Issue by wenzhenxi** [googollee/go-socket.io#190]
panic: send on closed channel

goroutine 3306134 [running]:
sunmi-socket.io/vendor/github.com/googollee/go-engine.io/polling.(*Writer).Close(0xc73d557b40, 0x9b4d10, 0xc73d557b60)
        /app/go/src/sunmi-socket.io/vendor/github.com/googollee/go-engine.io/polling/writer.go:29 +0xdb
sunmi-socket.io/vendor/github.com/googollee/go-engine%2eio.(*connWriter).Close(0xc73d557b60, 0x0, 0x0)
        /app/go/src/sunmi-socket.io/vendor/github.com/googollee/go-engine.io/ioutil.go:49 +0x6f
sunmi-socket.io/vendor/github.com/googollee/go-socket%2eio.(*encoder).encodePacket(0xc440818698, 0x0, 0x0, 0x0, 0xffffffffffffffff, 0x0, 0x0, 0x0, 0x0, 0x0)
        /app/go/src/sunmi-socket.io/vendor/github.com/googollee/go-socket.io/parser.go:130 +0x56b
sunmi-socket.io/vendor/github.com/googollee/go-socket%2eio.(*encoder).Encode(0xc5bb7afe98, 0x0, 0x0, 0x0, 0xffffffffffffffff, 0x0, 0x0, 0x0, 0x842703, 0xc4408186f8)
        /app/go/src/sunmi-socket.io/vendor/github.com/googollee/go-socket.io/parser.go:82 +0xb2
sunmi-socket.io/vendor/github.com/googollee/go-socket%2eio.(*socket).loop(0xc7281d87c0, 0x0, 0x0)
        /app/go/src/sunmi-socket.io/vendor/github.com/googollee/go-socket.io/socket.go:137 +0x1dc
sunmi-socket.io/vendor/github.com/googollee/go-socket%2eio.(*Server).loop.func1(0xc7281d87c0)
        /app/go/src/sunmi-socket.io/vendor/github.com/googollee/go-socket.io/server.go:103 +0x2b
created by sunmi-socket.io/vendor/github.com/googollee/go-socket%2eio.(*Server).loop
        /app/go/src/sunmi-socket.io/vendor/github.com/googollee/go-socket.io/server.go:104 +0xa9

**Comment by majintao** [comment]
@googollee  the same problem

**Comment by kunaldawn** [comment]
@googollee crashed our server 5 times in last month

**Comment by kunaldawn** [comment]
@googollee are u maintaining this repo anymore?

**Comment by googollee** [comment]
Basically, no. I don’t have enough time on this now. Welcome to PR.

**Comment by erkie** [comment]
This is a go-engine.io issue. Please refer to that project:

https://github.com/googollee/go-engine.io/issues/47
