### ISSUE TITLE
Connect to existing server?

### ISSUE THREAD

**Issue by Mobilpadde** [googollee/go-socket.io#191]
I cannot seem to find anything, but is it possible to connect to an existing server, instead of creating one?

**Comment by erkie** [comment]
This project does not seem to have a websocket client for Go. However, the library it uses seems to have client support: https://github.com/googollee/go-engine.io/blob/master/websocket/client.go

**Comment by Mobilpadde** [comment]
@erkie, oh, that's neat! But, I can't figure out how to use the client?

**Comment by erkie** [comment]
Hmm... From the looks of it it's only used for testing. Internally it uses https://github.com/gorilla/websocket which is probably more what you're looking for.

**Comment by Mobilpadde** [comment]
As I understand Gorilla, it doesn't support socket.io
