### ISSUE TITLE
example in documentation  report "http: multiple response.WriteHeader calls" error when client connect from browser. And the client received "Error during WebSocket handshake Ask Unexpected response code: 403"  

### ISSUE THREAD

**Issue by mmmmmagina** [googollee/go-socket.io#194]
Hi, guys,
   I tried your example in branch 1.4, i write a simplest web page to conncet the example main.go server, first i received cors error, after fix that , then the server print out some log "http: multiple response.WriteHeader calls" and the client also report the error : "Error during WebSocket handshake Ask Unexpected response code: 403", do someone see this problem before?

**Comment by abourget** [comment]
Same here, no one? :)

**Comment by erkie** [comment]
@abourget this repo is in need of contributors or help. So if you found the solution feel free to paste it here. :)

**Comment by Romakita** [comment]
Hello guys,
Same problem for me. I use Gorilla mux with Socket.io and since the recent update I have this error 
`http: multiple response.WriteHeader calls`.

Here my code:
```go
router := gorilla_mux.NewRouter()
server, err := socketIo.NewServer(nil)

if err != nil {
  logrus.Fatal(err)
  return nil
}

router.Handle("/socket.io/", server)
```
I don't know how I can fix that ?
Thanks in advance,
Romain

**Comment by erkie** [comment]
@Romakita cut you perhaps put together a git repo with minimal code for the server and minimal client code that reproduces this?

**Comment by Romakita** [comment]
@erkie here the minimal code:

```go
package main

import (
	"github.com/Sirupsen/logrus"
	"github.com/carbocation/interpose"
	socket_io "github.com/googollee/go-socket.io"
	gorilla_mux "github.com/gorilla/mux"
	"github.com/tylerb/graceful"
	"net/http"
)

func createWsServer() *socket_io.Server {
	server, err := socket_io.NewServer(nil)

	if err != nil {
		logrus.Fatal(err)
		return nil
	}

	server.OnConnect("/", func(conn socket_io.Conn) error {
		logrus.WithFields(logrus.Fields{
			"event": "Connection",
			"type":  "websocket",
			"id":    conn.ID(),
			"room":  "/",
		}).Info("client connected")
		return nil
	})

	return server
}

func main() {
	logrus.Info("Starting server")

	interpose.New()

	router := gorilla_mux.NewRouter()
	// WS
	router.Handle("/socket.io/", createWsServer())

	middleware := interpose.New()
	middleware.UseHandler(router)

	srv := &graceful.Server{
		Server: &http.Server{Addr: "0.0.0.0:8888", Handler: middleware},
	}

	err := srv.ListenAndServe()

	if err != nil {
		logrus.Fatal(err)
	}
}
```

**Comment by erkie** [comment]
@Romakita thanks! And the client code too please.

**Comment by Romakita** [comment]
I use the given example in your repository.
```html
<!doctype html>
<html>
  <head>
    <title>Socket.IO</title>
  </head>
  <body>
    <script src="/socket.io.js"></script>

    <script>
      var socket = io(); // try to connect on the server. The server 
      
    </script>
  </body>
</html>
```
> Emit this error in the browser console: WebSocket connection to 'ws://localhost:8888/socket.io/?EIO=3&transport=websocket&sid=5' failed: Error during WebSocket handshake: Unexpected response code: 403

And the backend log `http: multiple response.WriteHeader calls`.  I used also https://electronjs.org/apps/socket-io-tester to call the socket.io service and it's the same problem on the backend side.

Thanks @erkie for your time :)

**Comment by erkie** [comment]
@Romakita thanks, and can you link the version of `/socket.io.js` you used.

**Comment by Romakita** [comment]
I use the v2.2.0.

**Comment by erkie** [comment]
OK, that is the problem. Right we only support 1.4 of Socket.IO client library. Please follow this issue for updates if/when it gets implemented: https://github.com/googollee/go-socket.io/issues/188

In the meantime you should simply just use the 1.4 socket.io client library.

**Comment by Romakita** [comment]
No the problem doesn't come from this client version. As I explained the socket server respond WriteHeader more than once and the response isn't correct. 

The 2.2 version works fine before the merge 1.4 on the master (2 days ago).

**Comment by Romakita** [comment]
I don't understand why 2 days ago your server works with the 2.2.0 socket.io client and now this lib support only 1.4.0. I'll try to downgrade my socket-io client version and test again :(

**Comment by erkie** [comment]
@Romakita we have never officially supported anything over 1.4. I guess it was a happy mistake, but it was never tested so it could have nasty bugs that break other features. Please try again with 1.4 and let me know

**Comment by Romakita** [comment]
@erkie As I expected the problem isn't the socket.io client version. Now I use the v1.4 and it doesn't works. I have the same problem from the server:

> http: multiple response.WriteHeader calls

**Comment by erkie** [comment]
@Romakita OK. Sorry to be a bother but can you put everything in a git repo and publish to your github account? It's so I can quickly clone it and try it for myself.

**Comment by Romakita** [comment]
I'll try to give you a repo example ASAP ;)

**Comment by Romakita** [comment]
I found the problem. In 1.4, the server check the Origin headers. Know for me it works but BroadcastTo method hasn't equivalent in 1.4 or I missed something. 
Thanks for your answers ;)

**Comment by erkie** [comment]
@Romakita I'm sorry I'm not really following, where you able to fix the problem with `http: multiple response.WriteHeader calls`? What was the solution?

**Comment by Romakita** [comment]
The problem come from the client. I use Vue-cli with proxy configuration, and the host set in `Origin` header isn't the same as the WebSocket server host. So when you check the origin header "CheckSameOrigin" the server send headers and a 403 response.

The problem come from Vue-cli not from your library. I have another issues with the 1.4 about performance and stability when I try to emit/broadcast message (server to client) but I haven't time to investigate, I forked your project temporary and use the v1.0 which is work perfectly (and it has the BroadcastTo method ^^).

If I have a time, I'll try reproduce the problem performance and stability with a simple example.  

See you
Romain

**Comment by xgene** [comment]
我看你是中国人，我英文不好，就用中文说一下，我想你一定是跨域调用胡时候遇到这个问题的，我就是这么遇到的。例子中的socketio.NewServer(nil)的参数为nil，它是*engineio.Options , 它里面有个字段叫Transports，当它为nil或空数组时会返回一个默认数组，请看其getTransport()方法，其元素websocket.Default 是这个Transport默认值没有指定CheckOrigin函数，这个函数返回true表示域验证通过，你需要实现并指定它

**Comment by mattrout92** [comment]
FYI The work around I came up with for this was:

```go
        pt := polling.Default

	wt := websocket.Default
	wt.CheckOrigin = func(req *http.Request) bool {
		return true
	}

	server, err := socketio.NewServer(&engineio.Options{
		Transports: []transport.Transport{
			pt,
			wt,
		},
	})
	if err != nil {
		log.Fatal(err)
	}
```

**Comment by mstapfner** [comment]
@mattrout92 thanks for your Workaround, that also worked for my setup (Gorilla Mux as Router)

**Comment by erkie** [comment]
This seems to be a CORS documentation issue then. Will open a new issue for this
