### ISSUE TITLE
Not able to make namespaces work

### ISSUE THREAD

**Issue by tdida** [googollee/go-socket.io#206]
`func main() {
	router := gin.Default()
	var err error

	SocketServer, err = socketio.NewServer(nil)
	if err != nil {
		log.Fatal(err)
	}

	router.GET("/socket.io/", socketHandler)
	router.POST("/socket.io/", socketHandler)
	router.Handle("WS", "/socket.io/", socketHandler)
	router.Handle("WSS", "/socket.io/", socketHandler)

	router.Run(":8000")
}

func socketHandler(c *gin.Context) {

	SocketServer.Of("/claw").On("connection", func(so socketio.Socket) {
		fmt.Println("on connection")
	})

	SocketServer.On("error", func(so socketio.Socket, err error) {
		fmt.Printf("[ WebSocket ] Error : %v", err.Error())
	})

	SocketServer.ServeHTTP(c.Writer, c.Request)
}`

**Comment by erkie** [comment]
What error are you getting? What exactly is happening? Which version of this library are you using?

**Comment by manongguard** [comment]
oh shame, i accidentally erased my work for the namespaces for I am trying too many different implementation. Will try to provide if i get back on it, but is this good for socket.io 2.0?

**Comment by erkie** [comment]
This project is built for Socket.io 1.4.
