### ISSUE TITLE
client add query param and then server can not receive msg

### ISSUE THREAD

**Issue by wzhsh90** [googollee/go-socket.io#215]
Socket.IO v2.2.0
client:
  var socket = io.connect('http://localhost:5000/socket.io?xx=bar',{transports:['websocket']});
   socket.on('connect', function () {
    socket.send('hi');
	socket.emit('chat message', "msg");
	  socket.on('chat message', function (msg) {
      console.log(msg);
    });
  socket.on('disconnect', function () {
    socket.emit('user disconnected');
  });
	
  });
server:
transName := [] string{"websocket", "polling"}
	server, err := socketio.NewServer(transName)
	if err != nil {
		log.Fatal(err)
	}
	server.On("connection", func(so socketio.Socket) {
		//log.Println("on connection",so.Request().FormValue("xx"))
		log.Println("on connection")
		so.Join("chat")
		so.On("chat message", func(msg string) {
			log.Println("emit:", so.Emit("chat message", msg))
			server.BroadcastTo("chat", "chat message", msg)
		})
		so.On("disconnection", func() {
			log.Println("on disconnect")
		})
	})
	server.On("message", func(msg string) {
		log.Println("message:", msg)
	})
	server.On("error", func(so socketio.Socket, err error) {
		log.Println("error:", err)
	})

if i remove xx=bar client and serve can receive each event, but if i and ther query, event can not work.

**Comment by erkie** [comment]
This project does not support socket.io I'm afraid.
