### ISSUE TITLE
Issue template

### ISSUE THREAD

**Issue by erkie** [googollee/go-socket.io#216]
@googollee I've closed a lot of old/stale issues and added tags to a lot of other issues. A common theme is the version of the socket.io client and go-socket.io version is not posted. I think an Issue template would help a lot with that.

However I can't seem to access the "Settings" tab as posted by this document. Can you perhaps follow the steps and set one up? https://help.github.com/articles/creating-issue-templates-for-your-repository/

**Comment by googollee** [comment]
Thank you for your hard work. I set a bug template.
