### ISSUE TITLE
How to find out the message received to client

### ISSUE THREAD

**Issue by SinaZK** [googollee/go-socket.io#220]
Hi i'am implementing a game server with this awesome library. Now i'am testing my game and if a client with very bad internet connection joined my game after a while there is a lot messages that should send to this client (I send the game state with around 20 times per second to all clients) and this cause connection problems and another players see the bad effect of it. For solving this i have an idea that don't emit every message to client sockets. This cause many messages to be queued to socket stack and many of them is not needed now. (i can send new state not the old state that in the queue 1 second ago). Now i want to know how to findout a message received to client so i can send next snapshot of my game to this client. i download the socket.io lib code and engine.io code but i can't findout how to handle this. please help me. thanks

**Comment by googollee** [comment]
The queue or cache of a socket is inside OS kernel. go-socket.io/go-engine.io doesn't have that thing.

I recommend you adding a queue and wrap go-socket.io inside the queue. The queue will emit message with a fixed count, and store others in itself and do cleanup when new message coming in.

Furthermore, please consider UDP if you want to have a good experience with not-so-good network connections.

**Comment by SinaZK** [comment]
First of all thanks for your response. I'm going to use this queue thing around library that always send the last snapshot to client and client send what is the last snapshot received to server. This means if the client don't send last received message the server don't send another snapshots so there should be no queue overflowing and bad experience for another players. 
Another question is for example server sends snapshot for time=1 to time=1000 to client. This library use tcp so the messages come in the right order and time=1000 snapshot comes at last. Is that also guarantee if a client received snapshot time=1000 also received every snapshot from 1 to 1000? Or is there any time to live attribute for messages and if that exceed the message will drop?
