### ISSUE TITLE
Support Rooms

### ISSUE THREAD

**Issue by jianglijie** [googollee/go-socket.io#222]
I cant find somecode like “joinroom”， “leaveroom”， “emit(msg, room)”  etc.
in example code it only show the broadcast and namespace 
so it support room now?

**Comment by erkie** [comment]
Isn't a namespace a room?

**Comment by erkie** [comment]
Aha, sorry, I see the distinction now. Seems like a feature request. Help would be greatly appreciated :)

**Comment by yanqingliu** [comment]
hi,@erkie, can you support an example to use “joinroom”， “leaveroom”，etc. In this project, i can't find how to use them. thankyou

**Comment by peiying16** [comment]
Room is a great feature on socket.io. We should support it soon. 
https://socket.io/docs/rooms-and-namespaces/#Rooms

**Comment by erkie** [comment]
@peiying16 absolutely! Unfortunately I don't have much time to put in here. If you can make a PR for this feature I'd be more than happy to review it :)

**Comment by erkie** [comment]
Closed thanks to https://github.com/googollee/go-socket.io/pull/239
