### ISSUE TITLE
server.On undefined [BUG]

### ISSUE THREAD

**Issue by farzadi** [googollee/go-socket.io#224]
after updating to the new version I get this error : 
```
server.On undefined (type *socketio.Server has no field or method On)
 undefined: socketio.Socket

```

**Comment by ChinmayNaphade** [comment]
That method is called differently in the new version. 


	server.OnEvent("/", "notice", func(s socketio.Conn, msg string) {
		fmt.Println("notice:", msg)
		s.Emit("reply", "have "+msg)
	})

**Comment by randiaz95** [comment]
Wow appreciate the help but.... do we even have documentation on this method?

That answer seems a little cryptic.

**Comment by SAM-M-GO** [comment]
Buenas!! Al cambiar el método seguramente cambia la manera de la que se llama desde el lado de cliente.. por ej. con el método anterior se llamaba así: const socket = io(); (desde js) 
La duda es, ahora con el nuevo método como seria el método de llamada? Gracias!

**Comment by mrfoe7** [comment]
@SAM-M-GO Hola
del mismo modo
