### ISSUE TITLE
runtime error: invalid memory address

### ISSUE THREAD

**Issue by farzadi** [googollee/go-socket.io#225]
I'm having this problem .why this happen?

```

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x72c399]

goroutine 7 [running]:
github.com/googollee/go-socket%2eio.(*conn).serveError(0xc4201c2000)
        /home/vira/go/src/github.com/googollee/go-socket.io/conn.go:150 +0x1a9
created by github.com/googollee/go-socket%2eio.newConn
        /home/vira/go/src/github.com/googollee/go-socket.io/conn.go:73 +0x2d3
```

**Comment by erkie** [comment]
Please provide a github repo with all code required to reproducd this error so the community can take a look.

**Comment by redbulled** [comment]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x130dc70]

goroutine 24 [running]:
github.com/googollee/go-socket%2eio.(*conn).serveError(0xc000080120)
	/Users/admin/code/go/src/github.com/googollee/go-socket.io/conn.go:150 +0x180
created by github.com/googollee/go-socket%2eio.newConn
	/Users/admin/code/go/src/github.com/googollee/go-socket.io/conn.go:73 +0x2a6
exit status 2

**Comment by redbulled** [comment]
https://github.com/redbulled/go-socket.io-unexpected-panic

and everything is from "expamples"

**Comment by farzadi** [comment]
My server is located in my office and its internet is providing with my office's internet which is via wireless (Microwave). I guess Go-socket-io crashing is because of my server's internet instability.
Do you think so?

**Comment by erkie** [comment]
Until my PR https://github.com/googollee/go-socket.io/pull/227 has been merged you should be able to avoid this by just adding an `OnError` handler (as defined in the README).

**Comment by erkie** [comment]
#227 merged so this is fixed now. Create a new issue if not
