### ISSUE TITLE
error when connecting from another port or server

### ISSUE THREAD

**Issue by AndrusGerman** [googollee/go-socket.io#229]
**Describe the bug**
Error conection sockect server in external conection. unsuccessful connection attempt multiples

**To Reproduce**
Brief code to reproduce the behavior.
Open index in other server

**Expected behavior**

**Environment (please complete the following information):**
 - Go version: [v1.11.5]
 - Server version [ go-socket.io v1.4]
 - Client version [ socket.io v1.4 - v2.2 ]

**Additional context**
https://i.imgur.com/BBKkLnA.png

**Comment by AndrusGerman** [comment]
https://github.com/AndrusGerman/ErrorSocketIO

**Comment by AndrusGerman** [comment]
https://github.com/AndrusGerman/ErrorSocketIO

**Comment by mrfoe7** [comment]
@AndrusGerman Hi
Is it actually problem?

**Comment by AndrusGerman** [comment]
@mrfoe7 Hello, currently in my company we use an old version of sk. Since with the new version (of the date of the issue) it did not work.  

> I will do some tests to verify if this problem still exists

**Comment by AndrusGerman** [comment]
@mrfoe7 The error continues to occur, Go1.13.1 (Module)  https://github.com/AndrusGerman/go-socket.io-issues-229

**Comment by AndrusGerman** [comment]
the problem was solved [cors documentation](https://github.com/googollee/go-socket.io/pull/477)
