### ISSUE TITLE
where is server.Broadcast

### ISSUE THREAD

**Issue by korpmaks** [googollee/go-socket.io#230]
Can't find server.Broadcast at the latest edition

**Comment by BarretoDiego** [comment]
Same thing here!!

**Comment by googollee** [comment]
No broadcast feature in the latest version. PR is welcome.

**Comment by korpmaks** [comment]
What do you mean "PR is welcome"

**Comment by webern** [comment]
Problems here, too. I had a different version. Seems the interface/design has changed a lot, hope I can figure out the commit sha that I had.

**Comment by webern** [comment]
Don't know if this helps anyone else but I found the sha commits that compile with my existing code.  For me socketio.Server returned *socketio.Server, err and the broadcast function was named BroadcastTo

The shas needed are these:

go-socket.io `0ad7206c347a1c531174c35fb3b68be22360a80c`
which is [here](https://github.com/googollee/go-socket.io/commit/0ad7206c347a1c531174c35fb3b68be22360a80c)

and go-engine.io `e2f255711dcb2ea41e42c6d9d98c172d7edf6509`
which is [here](https://github.com/googollee/go-engine.io/commit/e2f255711dcb2ea41e42c6d9d98c172d7edf6509)

My go.mod now looks like this

```
github.com/googollee/go-engine.io v0.0.0-20180829091931-e2f255711dcb // indirect
github.com/googollee/go-socket.io v0.0.0-20181214084611-0ad7206c347a
```

**Comment by chuan9** [comment]
@googollee hi, also need this feature, do you any plans to support Broadcast function? or have any other replacements? If I want to implement a room, how to broadcast to any other clients in v1.4? thanks
I can use broadcast in v1.0, but it has hijected issue.

**Comment by kunaldawn** [comment]
@chuan9 found any way?

**Comment by chuan9** [comment]
@kunaldawn No, used node.js as a replacement.

**Comment by kunaldawn** [comment]
@chuan #239 might help?

**Comment by chuan9** [comment]
@kunaldawn You can google socketio node.js, and have many tutorials.

**Comment by lemontreehuang** [comment]
@kunaldawn i find you have finished Broadcast, why does not  @googollee  combine it?

**Comment by erkie** [comment]
Thanks to the awesome work by @kunaldawn I believe we can close this now.
