### ISSUE TITLE
i want to use  golang socket.io-client in a device

### ISSUE THREAD

**Issue by Mountains-and-rivers** [googollee/go-socket.io#232]
socket.io and socket.io-client are great in nodejs !

but now i want to use golang socket.io-client as it in nodejs ,wo should i do ? can you help me?

**Comment by huiruo** [comment]
I have same problem

**Comment by Mountains-and-rivers** [comment]
> I have same problem

https://github.com/Ali-IoT-Lab/socketio-client-go

**Comment by huiruo** [comment]
thanks,i will try

**Comment by huiruo** [comment]
> > I have same problem
> 
> https://github.com/Ali-IoT-Lab/socketio-client-go

thanks,i will try

**Comment by Mountains-and-rivers** [comment]
> > > I have same problem
> > 
> > 
> > https://github.com/Ali-IoT-Lab/socketio-client-go
> 
> thanks,i will try

i just find ```github.com/graarh/golang-socketio``` support socket.io 1.7.4 well

**Comment by huiruo** [comment]
> > > > I have same problem
> > > 
> > > 
> > > https://github.com/Ali-IoT-Lab/socketio-client-go
> > 
> > 
> > thanks,i will try
> 
> i just find `github.com/graarh/golang-socketio` support socket.io 1.7.4 well

well,It's very coincidental that I used this library in my project！

**Comment by elbashery** [comment]
I think the protocol mqtt is better in Iot projects
like mats or nsq or anything similar

**Comment by erkie** [comment]
Closing this because it seems that other projects might be better suited.
