### ISSUE TITLE
README is outdated

### ISSUE THREAD

**Issue by derektolliver** [googollee/go-socket.io#233]
In the master branch of the README it mentions the use of functions like `BroadcastTo`. I have seen in other issues that this function no longer exists. Would it be possible to get updated examples that don't refer to functions we can no longer utilize?

**Comment by yanqingliu** [comment]
Have the some problem, who can modify the example？

**Comment by erkie** [comment]
I'd be happy to merge a PR for this.

**Comment by erkie** [comment]
This has improved since my comment.
