### ISSUE TITLE
compared to NodeJS

### ISSUE THREAD

**Issue by redbulled** [googollee/go-socket.io#234]
why is it so much slower than nodeJS socket.io? When I'am emitting an event and wait for a cb, I get the response from server same fast as nodeJS does. But when I'm listening for the event on the client side omg its so slow compared to Node. I was waiting like 5 sec or maybe even more. it takes too much time. Is it suppose to be like that? because I thought golang would be faster but turns out it's not

**Comment by BelkevichAndry** [comment]
Have the same problem, any ideas?

**Comment by nokkusuu** [comment]
you don't happen to be running your go code in the browser (on the front-end), do you? correct me if i'm wrong, but gopherjs probably will not work 100% of the time, and wasm support for go might need to be refined a bit before its use is practical in a production environment. 

if you're using one of these methods, you may want to consider using socket.io's official js library instead. if not... well, i probably look like a fool haha

**Comment by redbulled** [comment]
> you don't happen to be running your go code in the browser (on the front-end), do you? correct me if i'm wrong, but gopherjs probably will not work 100% of the time, and wasm support for go might need to be refined a bit before its use is practical in a production environment.
> 
> if you're using one of these methods, you may want to consider using socket.io's official js library instead. if not... well, i probably look like a fool haha

Well, mate, that was a socket.io js version 1.4 (same as in docs) lib on the fronted and this lib "go-socket.io" on the backend. I didn't actually use gopherjs. lol

**Comment by mrfoe7** [comment]
@redbulled Hi
Is it actually problem?
