### ISSUE TITLE
How can I get conn on Error event? I need timeout event when pingtimout occur....

### ISSUE THREAD

**Issue by Azure1029** [googollee/go-socket.io#235]
**Describe the bug**

**To Reproduce**
Brief code to reproduce the behavior.

**Expected behavior**

**Environment (please complete the following information):**
 - Go version: [e.g. v1.11]
 - Server version [e.g. go-socket.io v1.4]
 - Client version [e.g. socket.io v1.4]

**Additional context**

**Comment by ardingchen** [comment]
I meet the same problem. I registe the error handler like this:

```go
	mysocketio.OnError("", func(err error) {
		log.Errorf("error=%+v", err)
		ctrl.DealError("", err)
	})
```

When error event is triggered, I can get the call stack, but I don't known which Conn this error beyond to.

[ERRO] [2019/05/06 19:29:00.894] [controller.go:490 DealError] DealError, err: websocket: close 1006 (abnormal closure): unexpected EOF
DealError
main.(*WGController).DealError
	../controller.go:490
main.setupSocketIOServer.func3
	../main.go:93
vendor/github.com/googollee/go-socket%2eio.(*conn).serveError
	.../vendor/github.com/googollee/go-socket.io/conn.go:150
runtime.goexit
	C:/Go/src/runtime/asm_amd64.s:1337
