### ISSUE TITLE
Runtime error: invalid memory address or nil pointer dereference.

### ISSUE THREAD

**Issue by harisgen79** [googollee/go-socket.io#236]
When I try 
pi@raspberrypi:~/Downloads/New/go-socket.io-master/example $ go run main.go
I get :

2019/04/26 13:31:31 Serving at localhost:5000...
2019/04/26 13:31:34 http: panic serving [::1]:52606: runtime error: invalid memory address or nil pointer dereference
goroutine 6 [running]:
net/http.(*conn).serve.func1(0x1488720)
	/usr/local/go/src/net/http/server.go:1769 +0xf0
panic(0x34c5b8, 0x65c1b0)
	/usr/local/go/src/runtime/panic.go:522 +0x1a0
runtime/internal/atomic.goCas64(0x150a06c, 0x0, 0x0, 0x1, 0x0, 0x145a000)
	/usr/local/go/src/runtime/internal/atomic/atomic_arm.go:83 +0x1c
github.com/googollee/go-engine.io/payload.(*Payload).FlushOut(0x150a000, 0x40c1b0, 0x1504000, 0x0, 0x0)
	/home/pi/go/pkg/mod/github.com/googollee/go-engine.io@v1.4.1/payload/payload.go:129 +0xf8
github.com/googollee/go-engine.io/transport/polling.(*serverConn).ServeHTTP(0x150c000, 0x40eb88, 0x1504000, 0x14f8000)
	/home/pi/go/pkg/mod/github.com/googollee/go-engine.io@v1.4.1/transport/polling/server.go:80 +0x368
github.com/googollee/go-engine%2eio.(*session).serveHTTP(0x150c070, 0x40eb88, 0x1504000, 0x14f8000)
	/home/pi/go/pkg/mod/github.com/googollee/go-engine.io@v1.4.1/session.go:197 +0xa0
github.com/googollee/go-engine%2eio.(*Server).ServeHTTP(0x1482230, 0x40eb88, 0x1504000, 0x14f8000)
	/home/pi/go/pkg/mod/github.com/googollee/go-engine.io@v1.4.1/server.go:191 +0x344
github.com/googollee/go-socket%2eio.(*Server).ServeHTTP(0x1410688, 0x40eb88, 0x1504000, 0x14f8000)
	/home/pi/Downloads/New/go-socket.io-master/server.go:33 +0x38
net/http.(*ServeMux).ServeHTTP(0x663c08, 0x40eb88, 0x1504000, 0x14f8000)
	/usr/local/go/src/net/http/server.go:2375 +0x1ac
net/http.serverHandler.ServeHTTP(0x1496200, 0x40eb88, 0x1504000, 0x14f8000)
	/usr/local/go/src/net/http/server.go:2774 +0x88
net/http.(*conn).serve(0x1488720, 0x40f0e8, 0x14ec040)
	/usr/local/go/src/net/http/server.go:1878 +0x7e4
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2884 +0x298
2019/04/26 13:31:41 http: panic serving [::1]:52608: runtime error: invalid memory address or nil pointer dereference
goroutine 7 [running]:
net/http.(*conn).serve.func1(0x1488780)
	/usr/local/go/src/net/http/server.go:1769 +0xf0
panic(0x34c5b8, 0x65c1b0)
	/usr/local/go/src/runtime/panic.go:522 +0x1a0
runtime/internal/atomic.goCas64(0x154006c, 0x0, 0x0, 0x1, 0x0, 0x664340)
	/usr/local/go/src/runtime/internal/atomic/atomic_arm.go:83 +0x1c
github.com/googollee/go-engine.io/payload.(*Payload).FlushOut(0x1540000, 0x40c1b0, 0x153c000, 0x0, 0x0)
	/home/pi/go/pkg/mod/github.com/googollee/go-engine.io@v1.4.1/payload/payload.go:129 +0xf8
github.com/googollee/go-engine.io/transport/polling.(*serverConn).ServeHTTP(0x1542000, 0x40eb88, 0x153c000, 0x14f8100)
	/home/pi/go/pkg/mod/github.com/googollee/go-engine.io@v1.4.1/transport/polling/server.go:80 +0x368
github.com/googollee/go-engine%2eio.(*session).serveHTTP(0x1542070, 0x40eb88, 0x153c000, 0x14f8100)
	/home/pi/go/pkg/mod/github.com/googollee/go-engine.io@v1.4.1/session.go:197 +0xa0
github.com/googollee/go-engine%2eio.(*Server).ServeHTTP(0x1482230, 0x40eb88, 0x153c000, 0x14f8100)
	/home/pi/go/pkg/mod/github.com/googollee/go-engine.io@v1.4.1/server.go:191 +0x344
github.com/googollee/go-socket%2eio.(*Server).ServeHTTP(0x1410688, 0x40eb88, 0x153c000, 0x14f8100)
	/home/pi/Downloads/New/go-socket.io-master/server.go:33 +0x38
net/http.(*ServeMux).ServeHTTP(0x663c08, 0x40eb88, 0x153c000, 0x14f8100)
	/usr/local/go/src/net/http/server.go:2375 +0x1ac
net/http.serverHandler.ServeHTTP(0x1496200, 0x40eb88, 0x153c000, 0x14f8100)
	/usr/local/go/src/net/http/server.go:2774 +0x88
net/http.(*conn).serve(0x1488780, 0x40f0e8, 0x14ec320)
	/usr/local/go/src/net/http/server.go:1878 +0x7e4
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2884 +0x298

Error pops up only after I open http://localhost:5000/ in my browser.
It keeps on "refreshing", it pops up new errors with different goroutines, different addresses etc.

I'm using Raspberry Pi 3 model B V1.2 with raspbian on it.
Go version: go1.12.4 linux/arm

**Comment by mrfoe7** [comment]
@harisgen79 Hi! Is it actual problem?

**Comment by joaopedropio** [comment]
Yes... I'm having the same problem... i'm using go version go1.13.8 linux/arm
