### ISSUE TITLE
[BUG] Response and ack from server are slow

### ISSUE THREAD

**Issue by vagase** [googollee/go-socket.io#238]
While running example chat program, the client receives acks from server for command "/chat msg" seconds delay after client sending the payload.

![Screen_Shot_2019-05-23_at_10_39_19](https://user-images.githubusercontent.com/807706/58222335-4594ae80-7d48-11e9-9fa6-85cc1dd2f970.png)

You can refer records with red underlines, # 42 packet sent at 10:38:52.788, but the ack # 43 packet was received at 10:39:05.564 !

It seems that the server will only write data to client while there are more upcoming request from client (refer blue line). 

### Environments:
- OS: macOS Mojave 10.14.4 (18E226)
- Go version: go1.11.4 darwin/amd64
- go-socket.io: v1.4.1

**Comment by elbashery** [comment]
yes it is very slow also on fedora 30

**Comment by ibuler** [comment]
The bug is here https://github.com/googollee/go-engine.io/blob/master/util.go#L33

Get the lock write slow, shared upgrade lock and writer lock

If we change the new write func:

```
func newWriter(w io.WriteCloser, locker *sync.RWMutex) *writer {
	return &writer{
		WriteCloser: w,
		locker:      new(sync.RWMutex),
	}
}
```

solve it

**Comment by tdaajames** [comment]
> The bug is here https://github.com/googollee/go-engine.io/blob/master/util.go#L33
> 
> Get the lock write slow, shared upgrade lock and writer lock
> 
> If we change the new write func:
> 
> ```
> func newWriter(w io.WriteCloser, locker *sync.RWMutex) *writer {
> 	return &writer{
> 		WriteCloser: w,
> 		locker:      new(sync.RWMutex),
> 	}
> }
> ```
> 
> solve it

not yet,  concurrent write will cause crash in your case.

**Comment by jrodatus** [comment]
ardingchen's change seems to fix this:
https://github.com/googollee/go-engine.io/issues/70#issuecomment-489561993

However, I don't know what `upgradeLocker` needs to protect, so I don't know if that's safe.

**Comment by erkie** [comment]
@jrodatus I merged this PR https://github.com/googollee/go-engine.io/pull/73 does that fix it for you?

**Comment by jrodatus** [comment]
@erkie Yes it does! Thanks for your work on this.

**Comment by erkie** [comment]
@jrodatus @tdaajames and everyone else in this thread are the real heroes :) Glad it's working.
