### ISSUE TITLE
[BUG] The following - 下面的

### ISSUE THREAD

**Issue by pi-pi-miao** [googollee/go-socket.io#244]
Origin: 在go-engine.io/transport/transport.go中 下面的n==name的地方，这里的order为一个slice，这里写的有点问题

Translate:
在 go-engine.io/transport/transport.go中 here's where n= = name, here's the order for a slice, a bit of a problem written here

Code:
```
func (m *Manager) UpgradeFrom(name string) []string {
	for i, n := range m.order {
		if n == name {
			return m.order[i+1:]
		}
	}
	return nil
}
```

**Comment by mrfoe7** [comment]
@pi-pi-miao Hi
I don't understand your question. Is it actual problem?

**Comment by mrfoe7** [comment]
It does not apply to the library
