### ISSUE TITLE
[bug]下面的

### ISSUE THREAD

**Issue by pi-pi-miao** [googollee/go-socket.io#245]
在go-engine.io/transport/transport.go中 下面的n==name的地方，这里的order为一个slice，这里写的有点。。。，把i和len(m.order)做一个校验，比较好
func (m *Manager) UpgradeFrom(name string) []string {
	for i, n := range m.order {
		if n == name {
			return m.order[i+1:]
		}
	}
	return nil
}

**Comment by mrfoe7** [comment]
@pi-pi-miao Hi
What is this? I don't understood issue
Please, send some more information

**Comment by mrfoe7** [comment]
Close because it is duplicated #244
