### ISSUE TITLE
undefined socketio.Socket

### ISSUE THREAD

**Issue by majimboo** [googollee/go-socket.io#248]
I understand that this has been updated and the API has changed but I don't want to change anything with my code so I'm looking for the right commit to go back to for my code to work. 

Using modules I tried to go back to this commit `5447e71f36d394766bf855d5714a487596809f0d` but it gives a parser error. So, which commit should I use for the old API to work?

**Comment by majimboo** [comment]
I figured out to use the release version `v1.0.1` for the older API to work.

You can use this on your `go.mod`:

    	github.com/googollee/go-socket.io v1.0.1

**Comment by zyctinker** [comment]
How can I downgrade version to v1.0.1 if my project is too old for go.mod? Thank you...

**Comment by shyandsy** [comment]
could you upgrade the demo code?
there is no socketio.Scoket now
