### ISSUE TITLE
How to access the connection request for using session

### ISSUE THREAD

**Issue by majimboo** [googollee/go-socket.io#249]
I used to do it like this:

	// 	var request = so.Request()
	// 	var session = sessions.GetSession(request, "sess_k", store)

But I can no longer access request with the new API.

**Comment by sumi-123** [comment]
@majimboo I think if you want request header, then can use `so.RemoteHeader()` and if want url then can use `so.URL()`

**Comment by TroyDota** [comment]
Is there any thing on this? We can get the header but how do we access the session data as to do that requires a http.Request and to save requires an http.RequestWriter
