### ISSUE TITLE
http: panic serving [::1]:53376: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by shubham-asati** [googollee/go-socket.io#252]
```go
package main
import (
	
	"fmt"
    "time"
	"log"

    kubeinformers "k8s.io/client-go/informers"
    "k8s.io/client-go/kubernetes"
    "k8s.io/client-go/tools/cache"
	"k8s.io/client-go/tools/clientcmd"
	"net/http"
	
	"github.com/googollee/go-socket.io"
)
var (
	data string
)
func main() {
	server, err := socketio.NewServer(nil)
	if err != nil {
		log.Fatal(err)
	}
	server.OnConnect("/", func(s socketio.Conn) error {
		s.SetContext("")
		fmt.Println("connected:", s.ID())
		return nil
	})
	server.OnEvent("/", "notice", func(s socketio.Conn, msg string) {
		fmt.Println("notice:", msg)
		s.Emit("reply", "have "+msg)
	})
	server.OnEvent("/chat", "msg", func(s socketio.Conn, msg string) string {
		s.SetContext(msg)
		return "recv " + msg
	})
	server.OnEvent("/", "bye", func(s socketio.Conn) string {
		last := s.Context().(string)
		s.Emit("bye", last)
		s.Close()
		return last
	})
	server.OnError("/", func(e error) {
		fmt.Println("meet error:", e)
	})
	server.OnDisconnect("/", func(s socketio.Conn, msg string) {
		fmt.Println("closed", msg)
	})
	fmt.Println(server)
	go server.Serve()
	//defer server.Close()

	http.Handle("/socket.io/", server)

	http.Handle("/", http.FileServer(http.Dir("./static")))
	
	log.Println("Serving at localhost:8000...")
	log.Fatal(http.ListenAndServe(":8000", nil))
    

}
```

error after running ths ->
2019/08/07 11:48:24 http: panic serving [::1]:53503: runtime error: invalid memory address or nil pointer dereference
goroutine 109 [running]:
net/http.(*conn).serve.func1(0x1492c180)
        C:/Go/go/src/net/http/server.go:1769 +0xed
panic(0x1045ba0, 0x1c8ce10)
        C:/Go/go/src/runtime/panic.go:522 +0x165
runtime/internal/atomic.Cas64(0x14a1c7bc, 0x0, 0x0, 0x1, 0x0)
        C:/Go/go/src/runtime/internal/atomic/asm_386.s:60 +0xc
github.com/googollee/go-engine.io/payload.(*Payload).FlushOut(0x14a1c750, 0x12da550, 0x148fe480, 0x0, 0x0)
        C:/Users/shubham.asati/Desktop/kubernetes/src/github.com/googollee/go-engine.io/payload/payload.go:129 +0x10c
github.com/googollee/go-engine.io/transport/polling.(*serverConn).ServeHTTP(0x14a1e7e0, 0x12eb890, 0x148fe480, 0x14984380)
        C:/Users/shubham.asati/Desktop/kubernetes/src/github.com/googollee/go-engine.io/transport/polling/server.go:80 +0x36
github.com/googollee/go-engine%2eio.(*session).serveHTTP(0x14a1e850, 0x12eb890, 0x148fe480, 0x14984380)
        C:/Users/shubham.asati/Desktop/kubernetes/src/github.com/googollee/go-engine.io/session.go:197 +0x9f
github.com/googollee/go-engine%2eio.(*Server).ServeHTTP(0x148b7cc0, 0x12eb890, 0x148fe480, 0x14984380)
        C:/Users/shubham.asati/Desktop/kubernetes/src/github.com/googollee/go-engine.io/server.go:191 +0x36d
github.com/googollee/go-socket%2eio.(*Server).ServeHTTP(0x1486f6a0, 0x12eb890, 0x148fe480, 0x14984380)
        C:/Users/shubham.asati/Desktop/kubernetes/src/github.com/googollee/go-socket.io/server.go:35 +0x3c
net/http.(*ServeMux).ServeHTTP(0x1c9b080, 0x12eb890, 0x148fe480, 0x14984380)
        C:/Go/go/src/net/http/server.go:2375 +0x189
net/http.serverHandler.ServeHTTP(0x148a6300, 0x12eb890, 0x148fe480, 0x14984380)
        C:/Go/go/src/net/http/server.go:2774 +0x84
net/http.(*conn).serve(0x1492c180, 0x12f0540, 0x14953f00)
        C:/Go/go/src/net/http/server.go:1878 +0x793
created by net/http.(*Server).Serve
        C:/Go/go/src/net/http/server.go:2884 +0x26c
>

**Comment by pandrej** [comment]
@shub-asa1 have you find any solution/work-around for this issue
I am seeing exactly the same behaviour. The strange thing is that I observe it only on binary cross-compiled for raspberry pi. Build for linux desktop works as expected

**Comment by shub-asa1** [comment]
@pandrej Nope, I couldn't find any solution , I set this up on windows machine and it was not working .

**Comment by pandrej** [comment]
@shub-asa1 I have found a work-around that suits my needs. When I disable `polling` transport and use only `websocket` everything works fine. This requires adequate changes on the `client` side but fortunately in my situation I am in control of the client also.

> 	opts := engineio.Options {
> 		Transports : []transport.Transport{websocket.Default},
> 	}
> 	srv, err := socketio.NewServer(&opts)
> 	if err != nil {
> 		log.Fatal(err)
> 	}

**Comment by mrfoe7** [comment]
@shub-asa1 and @pandrej It is actual problem?

**Comment by shub-asa1** [comment]
@mrfoe7 I will try to recreate this issue and update you on it.

**Comment by mrfoe7** [comment]
Thanks ^^

**Comment by shubham-asati** [comment]
closing this issue
