### ISSUE TITLE
[HELP] Broadcast [] byte instead of string.

### ISSUE THREAD

**Issue by StartAt24** [googollee/go-socket.io#255]
I just want to broadcast some images (png). But i got `string` in javascript. It seems that it has been base64 encode which cost a lot. 
So how can i broadcast `[] byte` instead of string.

``` Go
for{
		mat := <- ch
		t1 := time.Now()
		png, err := cv.IMEncode(".png", mat)
		if err!= nil{
			panic(err)
		}
		t2 := time.Now()
		fmt.Println("encode cost:", t2.Sub(t1))

		serve.BroadcastToRoom("stream", "png" , png)

		t3 := time.Now()
		fmt.Println("pub cost:", t3.Sub(t2))
	}
```

 - Go version: 1.12
 - Server version : 1.4.2

**Comment by blackkopcap** [comment]
`import github.com/googollee/go-socket.io/parser
 var buf parser.Buffer
 buf.Data = png
 serve.BroadcastToRoom("stream", "png" , buf)`

try this
