### ISSUE TITLE
Gin-gonic and go-socket.io

### ISSUE THREAD

**Issue by BuiChiBach** [googollee/go-socket.io#261]
Hello every one, currently , i want to build a server use go-socket.io and gin-gonic, i have researched but i can't find anything, so  does anyone  have any an specific example ?  

Thanks !

**Comment by Lil-M0use** [comment]
You can added the handler though this just past in server you can see example 
https://github.com/googollee/go-socket.io/blob/master/example/main.go

`router.GET("/socket.io/", gin.WrapH(server)
router.POST("/socket.io/", gin.WrapH(server))`

**Comment by mrfoe7** [comment]
@BuiChiBach Hi

It is simple example by gin-gonic and go-socket.io

```
package main

import (
	"fmt"
	"log"

	"github.com/gin-gonic/gin"

	socketio "github.com/googollee/go-socket.io"
)

func main() {
	router := gin.New()
	server, err := socketio.NewServer(nil)
	if err != nil {
		log.Fatal(err)
	}
	server.OnConnect("/", func(s socketio.Conn) error {
		s.SetContext("")
		fmt.Println("connected:", s.ID())
		return nil
	})
	server.OnEvent("/", "notice", func(s socketio.Conn, msg string) {
		fmt.Println("notice:", msg)
		s.Emit("reply", "have "+msg)
	})
	server.OnEvent("/chat", "msg", func(s socketio.Conn, msg string) string {
		s.SetContext(msg)
		return "recv " + msg
	})
	server.OnEvent("/", "bye", func(s socketio.Conn) string {
		last := s.Context().(string)
		s.Emit("bye", last)
		s.Close()
		return last
	})
	server.OnError("/", func(e error) {
		fmt.Println("meet error:", e)
	})
	server.OnDisconnect("/", func(s socketio.Conn, msg string) {
		fmt.Println("closed", msg)
	})

        go server.Serve()
	defer server.Close()

	router.GET("/ws/*any", gin.WrapH(server))

	router.Run(":8090")
}

```

**Comment by BuiChiBach** [comment]
> @BuiChiBach Hi
> 
> It is simple example by gin-gonic and go-socket.io
> 
> ```
> package main
> 
> import (
> 	"fmt"
> 	"log"
> 
> 	"github.com/gin-gonic/gin"
> 
> 	socketio "github.com/googollee/go-socket.io"
> )
> 
> func main() {
> 	router := gin.New()
> 	server, err := socketio.NewServer(nil)
> 	if err != nil {
> 		log.Fatal(err)
> 	}
> 	server.OnConnect("/", func(s socketio.Conn) error {
> 		s.SetContext("")
> 		fmt.Println("connected:", s.ID())
> 		return nil
> 	})
> 	server.OnEvent("/", "notice", func(s socketio.Conn, msg string) {
> 		fmt.Println("notice:", msg)
> 		s.Emit("reply", "have "+msg)
> 	})
> 	server.OnEvent("/chat", "msg", func(s socketio.Conn, msg string) string {
> 		s.SetContext(msg)
> 		return "recv " + msg
> 	})
> 	server.OnEvent("/", "bye", func(s socketio.Conn) string {
> 		last := s.Context().(string)
> 		s.Emit("bye", last)
> 		s.Close()
> 		return last
> 	})
> 	server.OnError("/", func(e error) {
> 		fmt.Println("meet error:", e)
> 	})
> 	server.OnDisconnect("/", func(s socketio.Conn, msg string) {
> 		fmt.Println("closed", msg)
> 	})
> 
>         go server.Serve()
> 	defer server.Close()
> 
> 	router.GET("/ws/*any", gin.WrapH(server))
>         router.POST("/ws/*any", gin.WrapH(server))
> 
> 	router.Run(":8090")
> }
> ```

That's was what i need ! thank you so much <3

**Comment by BuiChiBach** [comment]
That's was what i need ! thank you so much <3

**Comment by mrfoe7** [comment]
@erkie Plz, close this issue

**Comment by erkie** [comment]
@mrfoe7 thanks for helping out 💥🥳🚀
