### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by Karafs** [googollee/go-socket.io#263]
Hi. I'm a beginner in Golang and wrote a server application with this library.
My problem is that when just one user connects to the server with socket, the CPU performance of the server is going upper than 100%. Do you have any idea?
I registered about 35 events on the server socket.
Also when I send an event from the client to the server, It’s taking a too long time to call event on the server. The server state and ping time is OK.

**Comment by mrfoe7** [comment]
@Karafs Hi!
Tell about you os and hardware parameters. We need more informations

**Comment by Karafs** [comment]
> @Karafs Hi!
> Tell about you os and hardware parameters. We need more informations
I'm in the test and debug state. So I set up a simple and minimum server with 2 Gig ram and 2 core at CPU and 25 Gig hardDrive and my os is ubuntu 18.04.
I know my hardware is low, but my problem is with one socket pet time, not oo much socket and process.

**Comment by Karafs** [comment]
![image](https://user-images.githubusercontent.com/19264836/66047565-d5d3d300-e534-11e9-9e8c-593ce6778608.png)

**Comment by Karafs** [comment]
My mongodb version is 4.2 and I'm using globalsign library. I think the problem is the mongo library that I use.

**Comment by mrfoe7** [comment]
@Karafs if your graph is true. bottlenecks is mongodb library.
Notice: you will wanna approve performance, you should rewrite [broadcast.go](https://github.com/googollee/go-socket.io/blob/master/broadcast.go).
Because "Deffer" construction is overhead on 10-20 ns.
But if you use sync.Mutex have problem you can face the problem about - "Cache contention problem". It is problem resolved on Golang 1.9 by sync.Map. sync.Mutex is faster as sync.Map on lower cpu machines but if you use machine upper 4 cores, sync.Map is faster as sync.Mutex.

Graph by performance sync.Mutex and sync.Map
https://habrastorage.org/web/fc8/179/905/fc81799050554f20a7b28314b68afe47.png

@Karafs If your question is not actual yet. please close issue.

**Comment by Karafs** [comment]
Thanks for your reply. I used a mongo package that doesn't support mongo 4.2. So I changed that library with mongo official library. But the problem is consists. I'm working on that.

**Comment by Karafs** [comment]
I tested more.
I disabled any sending event to server socket. Right now I just connect to server socket and nothing more. after connect with just one user, My server ram usage is going up from 300 to 1 Gig. And when I disconnect from client before Ram reaches 1 Gig, the ram is not going up anymore. Do you have any idea? Am I wrong somewhere? Is there any configuration that I missed?
@mrfoe7

**Comment by Karafs** [comment]
![image](https://user-images.githubusercontent.com/19264836/66252305-ef5c6100-e766-11e9-9cb5-629d3cf1a5fd.png)
![image](https://user-images.githubusercontent.com/19264836/66252310-fb482300-e766-11e9-8a75-565afdddcaf6.png)

**Comment by mrfoe7** [comment]
> Thanks for your reply. I used a mongo package that doesn't support mongo 4.2. So I changed that library with mongo official library. But the problem is consists. I'm working on that.

Not problem. It is so interesting theme.

**Comment by mrfoe7** [comment]
> I tested more.
> I disabled any sending event to the server socket. Right now I just connect to server socket and nothing more. after connect with just one user, My server ram usage is going up from 300 to 1 Gig. And when I disconnect from the client before Ram reaches 1 Gig, the ram is not going up anymore. My CPU is the same as my ram. It's going up. Do you have any idea? Am I wrong somewhere? Is there any configuration that I missed?
> My actual problem is sending an event to the server. After connect, some initial events reach the server and after a few seconds, events do not reach to server. So I test some more and observed the above issue.
> @mrfoe7

Thanks for you research.
I think it is same problem by go-engine but not go-socket.io. I know what go-engine need some engineers contributors! [link](https://github.com/googollee/go-socket.io/issues/192)
If you have some free time, we need you help
