### ISSUE TITLE
[BUG] Shutdown server after reload html page

### ISSUE THREAD

**Issue by mrfoe7** [googollee/go-socket.io#265]
**Describe the bug**
When i open chat page and try to reload page, server was shutdown and don't recovery.
I run basic socket.io server by example. 

**To Reproduce**
Open chat page by simple example and reload page.

**Expected behavior**
Server don't shutdown.

**Environment (please complete the following information):**
 - Go version: [e.g. v1.11]
 - Server version [e.g. go-socket.io v1.4]
 - Client version [e.g. socket.io v1.4]

**Additional context**
Panic description:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1315829]

goroutine 13 [running]:
github.com/googollee/go-socket%2eio.(*conn).Close.func1()
        /Users/semen/go/src/github.com/googollee/go-socket.io/conn.go:91 +0x139
sync.(*Once).Do(0xc00017a138, 0xc000198e18)
        /usr/local/opt/go/libexec/src/sync/once.go:44 +0xb3
github.com/googollee/go-socket%2eio.(*conn).Close(0xc00017a0e0, 0x0, 0x0)
        /Users/semen/go/src/github.com/googollee/go-socket.io/conn.go:86 +0x6c
github.com/googollee/go-socket%2eio.(*conn).serveRead(0xc00017a0e0)
        /Users/semen/go/src/github.com/googollee/go-socket.io/conn.go:197 +0xbb2
created by github.com/googollee/go-socket%2eio.(*conn).connect
        /Users/semen/go/src/github.com/googollee/go-socket.io/conn.go:114 +0x251
exit status 2
```

**Comment by dream960727** [comment]
if i delete all code about "/chat", the bug can be fixed.but i know this is not a right way.

**Comment by mrfoe7** [comment]
@dream960727 Hi
I think, it is not correct behavior :) Some time age i used debug mode and find what happened.

Because twice call this row https://github.com/googollee/go-socket.io/blob/master/conn.go#L91
Method called https://github.com/googollee/go-socket.io/blob/master/conn.go#L84
```
func (c *conn) Close() error {
```

only 3 goroutines by _defer_ in https://github.com/googollee/go-socket.io/blob/master/conn.go#L112 https://github.com/googollee/go-socket.io/blob/master/conn.go#L113 https://github.com/googollee/go-socket.io/blob/master/conn.go#L114

I don't understand how method in _sync.Once_ called twice.

**Comment by mrfoe7** [comment]
After reload web page fmt printed twice message: *Call c.closeOnce.Do function*

STDOUT:
```
After nc.LeaveAll()
Call nh.onDisconnect
closed bye                                <- this message on server.OnDisconnect handler
Call c.closeOnce.Do function
After nc.LeaveAll()
```

Experimental code:
```
func (c *conn) Close() error {
	var err error
	c.closeOnce.Do(func() {
		// For each namespace, leave all rooms, and call the disconnect handler.
		for ns, nc := range c.namespaces {
			nc.LeaveAll()
                         fmt.Println("After nc.LeaveAll()")
			if nh := c.handlers[ns]; nh != nil {
                                 fmt.Println("Call nh.onDisconnect")
				nh.onDisconnect(nc, "bye")
				break
			}
		}
		err = c.Conn.Close()
		close(c.quitChan)
	})
	return err
}
```
If i added after command *nh.onDisconnect(nc, "bye")* *break*. Error wasn't happened. But i am not sure what behavior is correct

**Comment by mrfoe7** [comment]
@dream960727 I understood why happened this problem. By basic example, You connected double namespace and you have one onDisconnect handler on server side. When go to range of namespaces and call onDisconnect handler, but in basic example client connected to twice namespaces, but server have one handler function.
