### ISSUE TITLE
[BUG] Emit问题

### ISSUE THREAD

**Issue by chenyihui555** [googollee/go-socket.io#266]
在OnConnet方法中使用多次 conn.Emit("ssss"), 会导致客户端多次重连。

**Comment by chenyihui555** [comment]
@googollee

**Comment by mrfoe7** [comment]
> 在OnConnet方法中使用多次 conn.Emit("ssss"), 会导致客户端多次重连。

Using multiple conn in OnConnet method.Emit ("ssss"), causes the client to reconnect multiple times.

It is translate description by @chenyihui555

**Comment by mrfoe7** [comment]
@chenyihui555 Hi
Example usage:
```go
s.Emit("reply", "have "+msg)
```

if you wanna use conn.Emit() you should write first argument as event: 
```go
        Connect Type = iota
	// Disconnect type
	Disconnect
	// Event type
	Event
	// Ack type
	Ack
	// Error type
	Error

	// BinaryEvent type
	binaryEvent
	// BinaryAck type
	binaryAck
	typeMax
```
It is declaration in [line](https://github.com/googollee/go-socket.io/blob/master/parser/data.go#L10)
