### ISSUE TITLE
[BUG]run gin example failed

### ISSUE THREAD

**Issue by dream960727** [googollee/go-socket.io#267]
I want to run gin+go-socket, but when I go to example/gin-gonic and run `go run main.go`, it runs wrong, showing `panic: wildcard route '*filepath' conflicts with existing children in path '/* Filepath'`

**Comment by mrfoe7** [comment]
Hi, @dream960727 Thank you for you attention
It is my fault. When i tested it, i don't used statics dir. I fixed it at PR  #268

**Comment by mrfoe7** [comment]
But now you need to follow the route
http://localhost:8080/public

**Comment by dream960727** [comment]
so, this means that I can no longer use route "/" ?

**Comment by mrfoe7** [comment]
@dream960727 Yes, If you want use one server for return static file to client and with go-socket.io server. But you want use router "/" for static file can change routers of default socket.io server on client and backend side
It is problem in regular expressions by gin router
