### ISSUE TITLE
[BUG] Never calls event "OnDisconnect" after client loses a websocket connection

### ISSUE THREAD

**Issue by svksergey** [googollee/go-socket.io#279]
When my js client loses a websocket connection to my socket.io server it never calls event "OnDisconnect". I think it is bug. I only get event "OnError" with the text "websocket: close 1001 (going away)".

**Comment by mrfoe7** [comment]
@svksergey Hi, Sergey.

```
```

I tested on default version in master branch.

**Comment by shd101wyy** [comment]
I encountered the same issue.

**Comment by hzxgo** [comment]
I encountered the same issue.

**Comment by linwenchao** [comment]
I encountered the same issue.

**Comment by pkierski** [comment]
On websocket disconnection https://github.com/googollee/go-socket.io/blob/master/parser/decoder.go#L58 `NextReader` returns github.com/gorilla/websocket.CloseError with code 1001 `websocket.CloseGoingAway`.

I think wrapper.NextReader() in go-engine.io/transport/websocket/wrapper.go should check if error is websocket.CloseError and return this error wrapped with another error defined in go-engine.io API. Finally `conn.serveError()` https://github.com/googollee/go-socket.io/blob/master/conn.go#L196 should call onDisconnection in case of wrapped CloseError.

**Comment by mrfoe7** [comment]
Hi, @pkierski 
Can you send PR by your research?

**Comment by pkierski** [comment]
@mrfoe7 I haven't made MR yet. There are clues for solution only. I'll try to find some time in next week to implement such change.

I think there's one more change should be done even though it breaks backward compatibility. `OnError` handler function should have `Conn` type parameter just like others handlers.

**Comment by pkierski** [comment]
Just one more question: in polling mode could we detect if Socket.IO connection is closed? I think there's no such thing, because we don't know what is going between requests from client side. From the other side: it's possible to implement some disconnection logic based on ping...
I asking because I don't know if there is similar problem with no `OnDisconnect` call in case of polling transport.

**Comment by mrfoe7** [comment]
> I'll try to find some time in next week to implement such change.

I hope to it ^^

> I think there's one more change should be done even though it breaks backward compatibility. OnError handler function should have Conn type parameter just like others handlers.

It is done by PR #274 by @ardingchen and PR #237
If it is what you mean and new PR is correct, i will approve PR #274 

> I asking because I don't know if there is similar problem with no OnDisconnect call in case of polling transport.

I will try generate this situation on my PC and tell more information

**Comment by pangdahua** [comment]
other way

server.OnDisconnect("", func(s socketio.Conn, msg string) {
		fmt.Printf("client id %s say goodbye", s.ID())
})

namespace = "" can catch client disconnect event

**Comment by pkierski** [comment]
@pangdahua It doesn't work for me.

**Comment by pkierski** [comment]
@mrfoe7 #274 looks good for me. I thought about the same improvement for `OnDisconnect`. After that every handlers will be called in with connection context.

**Comment by mrfoe7** [comment]
@pkierski i approved changes and merge to master
