### ISSUE TITLE
I don't see some critical features (or am I missing?)

### ISSUE THREAD

**Issue by cyantarek** [googollee/go-socket.io#284]
Hi, this library is nice. But it lacks some features that javascript socketio offers.

For example:

01. How can I broadcast to all the connected socket connections without defining any room?
02. How can I emit private events targeting to a specific socket connection/id?
03. How can I send events to all the connected socket connections except me?

You can find out these implementation in official Socket.IO doc: https://socket.io/docs/emit-cheatsheet/

I found these features are really critical. Are they available right now? Am I missing?

**Comment by mrfoe7** [comment]
Hi, @cyantarek 

> 1. How can I broadcast to all the connected socket connections without defining any room?
Today, it is not implemented. It is good idea

> 2. How can I emit private events targeting to a specific socket connection/id?

I was implemented this in dev branch, but it is experimental feature. Main algorithm:
You safe all connection on your web sever and call by *server.Emit(connectionId, message, v ...interface{})* on your some events

> 3. How can I send events to all the connected socket connections except me?
If i understood correct your question, you may join all new connections to one room and after that send message for all different connections in this room about joined new client

**Comment by cyantarek** [comment]
> I was implemented this in dev branch, but it is experimental feature. Main algorithm:
> You safe all connection on your web sever and call by server.Emit(connectionId, message, v ...interface{}) on your some events

Saving connection in memory/web server using data structure like map is not a good idea.

**Comment by mrfoe7** [comment]
> Saving connection in memory/web server using data structure like map is not a good idea.
Why it is not a good idea?

**Comment by ElegantSoft** [comment]
@sshaplygin any updates for How can I emit private events targeting to a specific socket connection/id?
I

**Comment by ElegantSoft** [comment]
@sshaplygin is creating a separated room for each client when connect and broadcast to this room is a good idea ?
