### ISSUE TITLE
[BUG] Crash web-server after disconnected node.js client

### ISSUE THREAD

**Issue by mrfoe7** [googollee/go-socket.io#286]
**Describe the bug**

**To Reproduce**
Disconnect node.js client by crush client application

**Expected behavior**
Web server was not crush :)

**Environment (please complete the following information):**
 - Go version: go version go1.12.4 windows/amd64
 - Server version go-socket.io v1.4
 - Client version socket.io-client v2.3.0

**Additional context**
message - *meet error:  read tcp 127.0.0.1:8000->127.0.0.1:8386: wsarecv: An existing connection was forcibly closed by the remote host.mote host*

**Comment by googollee** [comment]
v2.0 doesn't exist now so it should not have bug yet.

While there are bugs against Node version in the old version, #295 should capture them automatically. I will close this one and #295 will do the job.
