### ISSUE TITLE
socket close does not work on disconnect ?

### ISSUE THREAD

**Issue by AhmedX6** [googollee/go-socket.io#290]
Hello,

In example I see that s.Close() is used on "bye" event.
Is it possible to do it onDisconnect event after doing some operations?

When I do s.Close() on disconnect, I have "Did you forget to Close() the ReadCloser from NextReader?" after some time. But I closed it.

SocketIO in golang is a great work but I find it more complicated than before...

Regards

**Comment by mrfoe7** [comment]
This issue duplicates to old issue #279

**Comment by AhmedX6** [comment]
Hello,

I'm with go v1.12.

I don't want to print anything but for example, here is my code :

```
server.OnDisconnect("/", func(s socketio.Conn, msg string) {
		lenRoom := len(s.Rooms())
		if lenRoom > 0 {
			for i := 0; i < lenRoom; i++ {
				log.Println("Socket id:", s.ID(), "left:", s.Rooms()[i])
				server.LeaveRoom(s.Rooms()[i], s)
				server.BroadcastToRoom(s.Rooms()[i], "nbr_connected", server.RoomLen(s.Rooms()[i])-1)
			}
		}
		s.Close()
})
```
It's simple. But have this message when I use s.Close() here "Did you forget to Close() the ReadCloser from NextReader?"

**Comment by mrfoe7** [comment]
@AhmedX6 
At first, Why are you call `Close` function at the socket after disconnect them.

If you want leave from all rooms use -  [LeaveAll](https://github.com/googollee/go-socket.io/blob/master/broadcast.go#L9) method.
and send for all what client disconnected from server please use [SendAll](https://github.com/googollee/go-socket.io/blob/master/broadcast.go#L12) method
