### ISSUE TITLE
Add basic example broadcast function in docs 

### ISSUE THREAD

**Issue by sshaplygin** [googollee/go-socket.io#292]

**Comment by bluebrown** [comment]
Hi folks, Its good to see that this library was not completely neglected as it looked for a moment. Socket.io itself is awesome. I am planning to use this library the revamp a python-socketio server. I would like to contribute along the way and could start out with adding examples like this, as I discover them. I could also help out somewhere else if my skills fit the job. Would be nice to get in touch. Cheers

**Comment by mrfoe7** [comment]
@bluebrown i am happy welcome to you. We have public chat at the telegram - [go-socket.io](https://t.me/go_socketio) You will may join with us.
