### ISSUE TITLE
Test against Node version socket.io.

### ISSUE THREAD

**Issue by googollee** [googollee/go-socket.io#295]
## Background

To make sure it works well with official Node.js version socket.io, it should have integration tests against Node socket.io. 

## Content

Tests should have:

- Node.js client vs Go server
- Go server vs Node.js server

Tests should be run automatically with CI.

**Comment by bluebrown** [comment]
I want travis CI right? I am going to implement pretty much this, node(electron) client to go server. I have to write tests along the way as it is a corporate project, I could try to adjust my tests a little so that we could reuse them here.

**Comment by googollee** [comment]
Thanks @bluebrown. Travis CI is good here.
