### ISSUE TITLE
Remove/merge go-engine.io into go-socket.io.

### ISSUE THREAD

**Issue by googollee** [googollee/go-socket.io#296]
## Background

I don't think anyone will use go-engine.io without go-socket.io. Separating these 2 projects will make the dependency complex and hard to do static analysis.

## Content

Drop go-engine.io. go-socket.io should contain all features of go-engine.io. We could put these features in `connection` subdirectory because go-engine.io maintains a connection. `engine` is not a good name here.

**Comment by danielfbm** [comment]
Maybe keeping it as a open package inside the repo and available to be used as a library? my 2-cents

**Comment by mrfoe7** [comment]
I was have idea use go-engine.io instead engine.io in socket.io server.
But i don't how to do it :( I think it is unbelievable

**Comment by googollee** [comment]
@mrfoe7, IMO, you can't mix them because engine.io is a library under socket.io, both node and go version.

@danielfbm I believe you can use it as `github.com/xxx/xxx/connection`.

**Comment by oo280635302** [comment]
Hi!the author, why can't I connect to socketio using gorilla / websocket?

**Comment by oo280635302** [comment]
Does this package have socketio client code, and if so, can you give an example?

**Comment by mrfoe7** [comment]
@oo280635302 Please, add new issue by your task and questions

**Comment by criyle** [comment]
I need a socket.io client which not provided in `go-socket.io` package, so I need to use `go-engine.io` directly. It would be helpful if socket.io client is officially supported in 2.0 version.

**Comment by adrianmxb** [comment]
With the PR above (#315) i merged engine.io into socket.io and even managed to preserve its history by merging the repositories togehter.

Question that came up in Telegram is, if it is a good idea to move some parts out of the project into a new repository (for shared stuff with the client)...

Personally I like the style of a monorepo for this project and merging socket&engine and then creating another repository again seems counterintuitive.
If it is planned to create a socket.io client we can just do that in this repo aswell, so everything is under one roof.

Maybe some opinions on that? :)

**Comment by erkie** [comment]
@adrianmxb @googollee @mrfoe7 we need to merge these 2 libraries into one. It will make developing and debugging a lot easier. How far did you get Adrian? I'd be happy to check+merge your progress.

**Comment by erkie** [comment]
OK went a bit nuts. I think just making a clean merge is a good start. If we want to move out things into other repos, that we can do. To get better momentum into this project we need to make it more approachable to start with, and consolidating them into one repo is the best start.

https://github.com/googollee/go-socket.io/pull/371
