### ISSUE TITLE
[QUESTION] What is the correct JS client version to use with this package?

### ISSUE THREAD

**Issue by pupizoid** [googollee/go-socket.io#298]
Hi I'm facing some problems with client disconnecting eventually, especially under large event count from server. I've tried 1.4, 1.2, 2.3 clients but the problem remains...

**Comment by mrfoe7** [comment]
Hi, @pupizoid

May you share your test case?
Do you use source code from master branch?
Thanks

**Comment by pupizoid** [comment]
Hi, after upgrading to master the problem seems to gone away... Thank you!

**Comment by mrfoe7** [comment]
@pupizoid No problem :)
