### ISSUE TITLE
The new version does not have a client for golang, the client for V0.9 has errors

### ISSUE THREAD

**Issue by oo280635302** [googollee/go-socket.io#300]
As title，
There is no Client.go after V0.9, and the client of v0.9 is wrong。

**Comment by Jarven89** [comment]
> As title，
> There is no Client.go after V0.9, and the client of v0.9 is wrong。

client of v0.9 is wrong can't to use？ I can‘t find any socket.io client to use，i just have to try this client。。。

**Comment by oo280635302** [comment]
v1.4.3 cannot accept messages from the client bye,

**Comment by abhiutd** [comment]
I am not able to find a "default-client" similar to "default-server". 

Is there a reference to how I can make calls like `so.Emit("some:event", dataForClient, func (so socketio.Socket, data string) {
    log.Println("Client ACK with data: ", data)
})` in my code ? 

I have written up a server using `example/default-server/main.go` as reference....

**Comment by oo280635302** [comment]
I have also used the server side, but the server ca n’t immediately remind me that the client side shuts down the client, and even my client actively sends a disconnect without awakening a reminder

**Comment by abhiutd** [comment]
Okay. I have a silly question - after starting the server, with appropriate `OnEvent` methods, how do I get access to the corresponding socket so that I can make `Emit` calls to the client ? I can't seem to find any struct/method which gives me that....any help would be great!

**Comment by erkie** [comment]
I dont think this library ever had a working client implementation of socket.io.
