### ISSUE TITLE
[BUG] Panic: index out of range

### ISSUE THREAD

**Issue by bluebrown** [googollee/go-socket.io#301]
**Describe the bug**
Panic when disconnecting with node client

```bash
websocket: close 1006 (abnormal closure): unexpected EOF
panic: runtime error: index out of range [0] with length 0
```

**To Reproduce**
Use node client to connect to master branch
Connect to server -> join new room -> disconnect

**Expected behavior**
No panic and actually it should not even enter this error handler. It should run the disconnect handler.

**Environment (please complete the following information):**

Go 1.13
Node v12.13.1 

github.com/googollee/go-socket.io v1.4.3-0.20191204093753-683f8725b6d0 (master)
github.com/googollee/go-engine.io v1.4.2 // indirect
github.com/gorilla/websocket v1.4.1 // indirect

socket.io 1.4 & 2.3

**Additional context**
```bash
websocket: close 1006 (abnormal closure): unexpected EOF
panic: runtime error: index out of range [0] with length 0

goroutine 30 [running]:
main.wsEvents.func1(0x94b040, 0xc0000ba960, 0x8ab09d, 0x1b)
        /home/gopher/Documents/code/go/src/bitbucket.org/cnx_devs/dispatcher/main.go:89 +0x213
github.com/googollee/go-socket%2eio.(*conn).Close.func1()
        /home/gopher/Documents/code/go/pkg/mod/github.com/googollee/go-socket.io@v1.4.3-0.20191204093753-683f8725b6d0/conn.go:91 +0x162
sync.(*Once).doSlow(0xc00010b4e8, 0xc00019fda8)
        /usr/lib/golang/src/sync/once.go:66 +0xe3
sync.(*Once).Do(...)
        /usr/lib/golang/src/sync/once.go:57
github.com/googollee/go-socket%2eio.(*conn).Close(0xc00010b490, 0x0, 0x0)
        /home/gopher/Documents/code/go/pkg/mod/github.com/googollee/go-socket.io@v1.4.3-0.20191204093753-683f8725b6d0/conn.go:86 +0x95
github.com/googollee/go-socket%2eio.(*conn).serveRead(0xc00010b490)
        /home/gopher/Documents/code/go/pkg/mod/github.com/googollee/go-socket.io@v1.4.3-0.20191204093753-683f8725b6d0/conn.go:197 +0xd1b
created by github.com/googollee/go-socket%2eio.(*conn).connect
        /home/gopher/Documents/code/go/pkg/mod/github.com/googollee/go-socket.io@v1.4.3-0.20191204093753-683f8725b6d0/conn.go:114 +0x24e
exit status 2
```

*, it could be the connection that is passed on the error handler, which has been changed in the master branch*

**Comment by mrfoe7** [comment]
Hi, @bluebrown 
Do you can shred's your client example?

**Comment by jbl19860422** [comment]
i meet similar issue, but my problem is when use socket.io to send signaling message to server, the error occurs in line 100 of decoder.go:if err := json.NewDecoder(r).Decode(&values); err != nil, the err is "unexpected EOF"

**Comment by jbl19860422** [comment]
i use wss, when connect it's ok, and also it processes one event normal, but when send another event to server, the socket disconnected because 'unexpected EOF'. I add some log to trace, and find the error is in here:":
 line 100 of decoder.go:
if err := json.NewDecoder(r).Decode(&values); err != nil {
      if err == io.EOF {
            err = nil
      }
      return nil, err
}"

**Comment by jbl19860422** [comment]
i found that when the content exceed 4096, this error will occur, and i found the bufio.Reader can only read about 4068 bytes, so it treat this as a error.
