### ISSUE TITLE
I'm getting bad request

### ISSUE THREAD

**Issue by cyantarek** [googollee/go-socket.io#311]
When emitting events from client, I got Bad Request 

```POST http://localhost:8500/socket.io/?EIO=3&transport=polling&t=1578039627529-2&sid=4 400 (Bad Request)```

And on the server console, it said 'resume'

Here's my client code:

```javascript
var socket = io();

var mesageForm = document.getElementById('send-container');
var mesageContainer = document.getElementById('message-container');
var mesageInput = document.getElementById('message-input');


const name = prompt('What is your name?');
appendMessage('You' + ' joined');

socket.emit('new-user', name);

socket.on('chat-message', data => {
    appendMessage(data)
});

socket.on('user-connected', name => {
    appendMessage(name + ' joined')
});

mesageForm.addEventListener('submit', function (e) {
    e.preventDefault();

    const message = mesageInput.value;
    socket.emit('send-chat-message', message);
    mesageInput.value = ''
});

function appendMessage(msg) {
    const messageElement = document.createElement('div');

    messageElement.innerText = msg;
    mesageContainer.append(messageElement)
}
```

And here's my server code

```go
package main

import (
	socketio "github.com/googollee/go-socket.io"
	"github.com/labstack/echo"
)

type Sock struct {
	sock socketio.Conn
	Name string
}

var socks = make(map[string]Sock)

func main() {
	io, _ := socketio.NewServer(nil)
	
	app := echo.New()
	
	app.Static("/", ".")
	
	app.Any("/socket.io/", func(s echo.Context) error {
		io.ServeHTTP(s.Response().Writer, s.Request())
		
		return nil
	})
	
	io.OnConnect("/", func(s socketio.Conn) error {
		socks[s.ID()] = Sock{
			sock: s,
		}
		
		s.Emit("chat-message", "Server: Hello World")
		
		return nil
	})
	
	io.OnEvent("/", "new-user", func(s socketio.Conn, name string) {
		sk := socks[s.ID()]
		sk.Name = name
		
		for k, v := range socks {
			if k != s.ID() {
				v.sock.Emit("user-connected", name)
			}
		}
	})
	
	io.OnEvent("/", "send-chat-message", func(s socketio.Conn, msg string) {
		for k, v := range socks {
			if k != s.ID() {
				v.sock.Emit("chat-message", msg)
			}
		}
	})
	
	go io.Serve()
	defer io.Close()
	
	app.Start(":8500")
}
```

It's annoying. What is causing this error?

**Comment by leobrines** [comment]
I have same error with gin gonic

**Comment by leobrines** [comment]
Testing [server example](https://github.com/googollee/go-socket.io#example), i have bad request error: `WebSocket connection to 'ws://localhost:8000/socket.io/' failed: Error during WebSocket handshake: Unexpected response code: 400`

**Comment by adrianmxb** [comment]
I tried to reproduce it but it is working fine for me.
Can you add a breakpoint or print the error you get in [go-engine.io/server.go:180](https://github.com/googollee/go-engine.io/blob/master/server.go#L180)

Also, can you provide a http request the socket.io client sends? (chrome devtools/network)
Hope I can help you with the additional info.

In the meantime it seems to be one of those errors, hope it helps...

	if !tokenListContainsValue(r.Header, "Connection", "upgrade") {
		return u.returnError(w, r, http.StatusBadRequest, badHandshake+"'upgrade' token not found in 'Connection' header")
	}

	if !tokenListContainsValue(r.Header, "Upgrade", "websocket") {
		return u.returnError(w, r, http.StatusBadRequest, badHandshake+"'websocket' token not found in 'Upgrade' header")
	}

	if !tokenListContainsValue(r.Header, "Sec-Websocket-Version", "13") {
		return u.returnError(w, r, http.StatusBadRequest, "websocket: unsupported version: 13 not found in 'Sec-Websocket-Version' header")
	}

	challengeKey := r.Header.Get("Sec-Websocket-Key")
	if challengeKey == "" {
		return u.returnError(w, r, http.StatusBadRequest, "websocket: not a websocket handshake: `Sec-WebSocket-Key' header is missing or blank")
	}

**Comment by leobrines** [comment]
This is my request from chrome and the breakpoint. It need a transport query
![image](https://user-images.githubusercontent.com/13511768/75446116-8c51ad80-5945-11ea-8d74-b1a777148374.png)
![image](https://user-images.githubusercontent.com/13511768/75448209-86f66200-5949-11ea-9584-a24c3ac39aff.png)

**Comment by leobrines** [comment]
Question. Why it does not support websocket transport? Thank you!

**Comment by adrianmxb** [comment]
It does support websocket but your client seems to be misconfigured.
Can you post example code of your client that showcases how you try to connect?

**Comment by leobrines** [comment]
If i use `transport=websocket` it show this error `websocket: request origin not allowed by Upgrader.CheckOrigin` but if I use `transport=polling` it return 200 without problem. This is the client
![image](https://user-images.githubusercontent.com/13511768/75450365-6f20dd00-594d-11ea-873e-0d1fc1d653df.png)

**Comment by adrianmxb** [comment]
This is a https://socket.io/ library which _uses_ websocket as lower level transport, **not** a websocket library.
If you are looking for a websocket library check out https://github.com/gorilla/websocket

**Comment by leobrines** [comment]
I used [websockets with nodejs](https://socket.io/docs/server-api/) for a while without problems. I used socket io and this library (go-socket.io) was the most similar at the time of issuing and obtaining events. I checked gorilla websockets but it is more complex. Do you still recommend me gorilla?

**Comment by adamsafr** [comment]
I used `const socket = io({transports: ['websocket']});` for frontend to fix this

**Comment by camilovp01** [comment]
I get the same error sometimes...
<img width="805" alt="Captura de Pantalla 2020-06-08 a la(s) 9 19 56 p  m" src="https://user-images.githubusercontent.com/4354454/84098916-0de9ba80-a9ce-11ea-9fc7-fec24bf9adaf.png">
<img width="1138" alt="Captura de Pantalla 2020-06-08 a la(s) 9 20 16 p  m" src="https://user-images.githubusercontent.com/4354454/84098935-18a44f80-a9ce-11ea-83c8-d9247d4e5dc6.png">

**Comment by MaximeAubanel** [comment]
I have the same errors to using `"socket.io-client": "^2.3.0"`.

It always happens when `go-socket.io` print `resume` on the console. 

Very weird, anyone got this fixed ?

**Comment by MaximeAubanel** [comment]
Well, I found the solution:

In your client when setting up the socket do it specifying the transport to be websocket only, like that:
```typescript
socket = io(ENDPOINT, {
            transports: ['websocket']
})
```

**Comment by erkie** [comment]
This issue has a lot of different issues in it, but when using the correct client library it seems to be a CORS issue. The documentation is way too vague how to get it running using CORS, so trying to consolidate that.

**Comment by Espresso521** [comment]
> I have same error with gin gonic

I have the same error, how to deal it??
