### ISSUE TITLE
How does namespace work ?

### ISSUE THREAD

**Issue by ghost** [googollee/go-socket.io#32]
Hello,

Im trying to use namespace but it didn't work.
Here's the code I used :

client:

var socket = io('/chat');

server :

```
server, err := socketio.NewServer(nil)
if err != nil {
    log.Fatal(err)
}

server.Of("/chat").On("connection", func(so socketio.Socket) {
    log.Println("on connection")
}
server.On("error", func(so socketio.Socket, err error) {
    log.Println("error:", err)
})
```

When I ran the program, it didn't show "on connection".
Why is it not working?

**Comment by iurisilvio** [comment]
I was unable to use namespaces too. I'm using latest go-socket.io and go-engine.io. It never trigger the `connection` event.
