### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by yykpf** [googollee/go-socket.io#322]
**Describe the bug**

**To Reproduce**
Brief code to reproduce the behavior.

**Expected behavior**

**Environment (please complete the following information):**
 - Go version: [e.g. v1.11]
 - Server version [e.g. go-socket.io v1.4]
 - Client version [e.g. socket.io v1.4]

**Additional context**
![image](https://user-images.githubusercontent.com/14089155/75768987-5c107180-5d80-11ea-9f88-41b00c90671e.png)

**Comment by mrfoe7** [comment]
@yykpf Hi
Please use latest go-socket.io version
