### ISSUE TITLE
Add documentation for how to use rooms

### ISSUE THREAD

**Issue by Stvchm9703** [googollee/go-socket.io#329]
Examples:

1. how manage client Join / Leave the room
2. how the server broadcast to all room
3. how the server broadcast to single room
4. how to close a single room

**Comment by mrfoe7** [comment]
@Stvchm9703 Hi
Please tell about wanna details about room features

**Comment by Stvchm9703** [comment]
1. how manage client Join / Leave the room
2. how the server broadcast to all room 
3. how the server broadcast to single room
4. how to close a single room

**Comment by litao09h** [comment]
mark

**Comment by aligurelli** [comment]
is there any documentation

**Comment by erkie** [comment]
We need help writing documentation! 😀

**Comment by armin-ahmadi** [comment]
+1, sadly this library is not very usable since there is zero documentation and basically zero comments describing how anything works.

**Comment by erkie** [comment]
@armin-ahmadi are you the person to make it happen? 💪 💪 💪
