### ISSUE TITLE
How to get Query Params in Golang, which is sent from Client Application ?

### ISSUE THREAD

**Issue by ShankyTiwari** [googollee/go-socket.io#331]
**I have a question, not a bug**
How to get Query Params in Golang, which is sent from the Client application (VanillaJs)?

---
**Below is my implementation:**
GoLang Code:
```golang
socketServer.OnConnect("/", func(s socketio.Conn) error {
	fmt.Println("connected:", s.URL())
	s.Emit("reply", "have ")
	return nil
})
```

Javascript Code:
```javascript
const socket = io({ query: `username=${username}`});
```

Right now am getting below displayed output,
``` bash 
connected: {    /socket.io/  false username=Shashank&EIO=3&transport=websocket&sid=3 }
```

But I want the only **`username`** which has **`Shashank`** as it's value.

---
**Environment (please complete the following information):**
I have installed the latest version using ```go get```

Thanks guys for maintaining this project.

**Comment by mrfoe7** [comment]
Example usage after approved next MR: https://github.com/googollee/go-engine.io/pull/89

```go

package main

import (
	"fmt"
	"log"
	"net/http"
	"net/url"

	engineio "github.com/googollee/go-engine.io"
	"github.com/googollee/go-engine.io/transport"
	"github.com/googollee/go-engine.io/transport/polling"
	"github.com/googollee/go-engine.io/transport/websocket"
	socketio "github.com/googollee/go-socket.io"
)

func main() {
	v := url.Values{
		"username": []string{"test_username"},
	}
	myUrl := url.URL{
		RawQuery: v.Encode(),
	}
	pollTransport := polling.Default
	wsTransport := websocket.Default

	pollTransport.SetURL(myUrl)
	pollTransport.SetURL(myUrl)

	options := engineio.Options{
		Transports: []transport.Transport{
			pollTransport,
			wsTransport,
		},
	}

	server, err := socketio.NewServer(&options)
	if err != nil {
		log.Fatal(err)
	}
	server.OnConnect("/", func(s socketio.Conn) error {
		s.SetContext("")
		fmt.Println("connected:", s.ID())
		return nil
	})
	server.OnEvent("/", "notice", func(s socketio.Conn, msg string) {
		fmt.Println("notice:", msg)
		server.Emit(s.ID(), "reply", "notice message "+msg)
	})
	server.OnEvent("/chat", "msg", func(s socketio.Conn, msg string) string {
		s.SetContext(msg)
		server.Emit(s.ID(), "reply", "chat msg "+msg)
		fmt.Println("connect id", s.ID())
		return "recv " + msg
	})
	server.OnEvent("/", "bye", func(s socketio.Conn) string {
		last := s.Context().(string)
		s.Emit("bye", last)
		s.Close()
		return last
	})
	server.OnError("/", func(s socketio.Conn, e error) {
		fmt.Println("meet error:", e)
	})
	server.OnDisconnect("/", func(s socketio.Conn, msg string) {
		fmt.Println("closed", msg)
	})
	go server.Serve()
	defer server.Close()

	http.Handle("/socket.io/", server)
	http.Handle("/", http.FileServer(http.Dir("../asset")))
	log.Println("Serving at localhost:8000...")
	log.Fatal(http.ListenAndServe(":8000", nil))
}

**Comment by mrfoe7** [comment]
I will add this example to _example directory

**Comment by adrianmxb** [comment]
Shouldn't this be enough?

```go
socketServer.OnConnect("/", func(s socketio.Conn) error {
	fmt.Println("connected:", s.URL().Query().Get("username"))
	s.Emit("reply", "have ")
	return nil
})
```

Could be mistaken, but because of the current situation I don't have a set-up environment to verify my suggestion.

**Comment by mrfoe7** [comment]
@adrianmxb If i am correctly understood, we need send custom query parameter each request

**Comment by 3miro** [comment]
I solved it, using nuxtjs to client using query param and server golang:
I sent room name from client

Client:

this.socket = this.$nuxtSocket({
           query: {
                room: 'room1'
            },            
        }) 


server:

server.OnConnect("/", func(s socketio.Conn) error {
		url := s.URL()
		room := url.Query().Get("room")
		s.SetContext("")
		s.Join(room)
		return nil
	})

**Comment by bbars** [comment]
@erkie, it looks like this issue could be closed

**Comment by erkie** [comment]
@bbars I haven't been too active in this project. Has the underlying issue been fixed or a workaround/existing solution been found?

**Comment by bbars** [comment]
> Has the underlying issue been fixed or a workaround/existing solution been found?

Yes, @ShankyTiwari can get query parameter of initial URL:
```golang
	socketServer.OnConnect("/", func(s socketio.Conn) error {
		url := s.URL()
		log.Println("username:", url.Query().Get("username"))
		return nil
	})
```

**Comment by ShankyTiwari** [comment]
Sure @bbars I will try and get back in case if it doesn't work.

Thanks everyonoe,

**Comment by phamtrongngh** [comment]
> > Has the underlying issue been fixed or a workaround/existing solution been found?
> 
> Yes, @ShankyTiwari can get query parameter of initial URL:
> 
> ```go
> socketServer.OnConnect("/", func(s socketio.Conn) error {
> 	url := s.URL()
> 	log.Println("username:", url.Query().Get("username"))
> 	return nil
> })
> ```

Execute me! 
I don't know why this will be OK:
```
url := s.URL()
log.Println("username:", url.Query().Get("username"))

```
But this will be not OK:
`log.Println("username:", s.URL().Query().Get("username"))`
Could anyone explain it to me, please?
