### ISSUE TITLE
[Question] How to connect as a client?

### ISSUE THREAD

**Issue by mrsydster** [googollee/go-socket.io#333]
I have my go-socket.io server running and I would connect as a client from another go file. Is that possible with this lib? Or do i need another lib?

**Comment by kabaluyot** [comment]
I think not supported

**Comment by mrfoe7** [comment]
At not, It does not exists

**Comment by xin7c** [comment]
> At now, It does not exists

we need it    ,really

**Comment by nyugoh** [comment]
This is required.

**Comment by erkie** [comment]
This will probably never happen in this library. It's hard enough managing the server side with the scarce resources we have. So closing this

**Comment by gzq0616** [comment]
i want client for golang library
