### ISSUE TITLE
[BUG] Meet EOF error with join to server on WebSocket

### ISSUE THREAD

**Issue by sshaplygin** [googollee/go-socket.io#336]
**Describe the bug**

*meet error: websocket: close 1006 (abnormal closure): unexpected EOF*

**To Reproduce**
Run default server in develop branch 

**Expected behavior**

**Environment (please complete the following information):**
 - Go version: [e.g. v1.11] v.1.13
 - Server version [e.g. go-socket.io v1.4] latest
 - Client version [e.g. socket.io v1.4] v.2.3.0

**Additional context**

**Comment by erkie** [comment]
Is this a socket 2 vs 1 issue?

**Comment by mrfoe7** [comment]
Client version [e.g. socket.io v1.4] v.2.3.0
