### ISSUE TITLE
Client Connection

### ISSUE THREAD

**Issue by Albinzr** [googollee/go-socket.io#338]
How to create client connection using go-socket.io 
instead of using socket.io.js to create client connection I want to start a client connection from golang

transporter := websocket.Default

	u, err := url.Parse("http://localhost:8080")
	if err != nil {
		util.LogFatal("cannot parse url")
	}
	transporter.Dial(u)
	transporter.Accept()

Tried this but not working

**Comment by mrfoe7** [comment]
it does not supported
