### ISSUE TITLE
I getting unexpected and unexplained message while running the socket

### ISSUE THREAD

**Issue by Albinzr** [googollee/go-socket.io#341]
**Describe the bug**
I'm getting the bellow message and not sure why its coming and how to solve it
"Did you forget to Close() the ReadCloser from NextReader?"

**To Reproduce**
Run a socket connection with multiple clients which keep sending message

**Expected behavior**
should explain where this problem is happening and logs or point towards how to solve it  

**Environment (please complete the following information):**
 - Go version: 1.13
 - Server version v1.4.3
 - Client version  v2.3.0

**Additional context**
"Did you forget to Close() the ReadCloser from NextReader?"

**Comment by Albinzr** [comment]
Anyone faced this issue?

**Comment by Albinzr** [comment]
Is this repo active?

**Comment by adrianmxb** [comment]
This issue should've been fixed with v.1.4.3
Can you provide sample code?

**Comment by Albinzr** [comment]
Code - Im facing this issue when there is multiple connections mainly 
`
package server

import (
	"fmt"
	"net/http"

	util "applytics.in/yin/src/helpers"
	middleware "applytics.in/yin/src/middlewares"

	engineio "github.com/googollee/go-engine.io"
	"github.com/googollee/go-engine.io/transport"
	"github.com/googollee/go-engine.io/transport/websocket"
	socket "github.com/googollee/go-socket.io"
)

var io *socket.Server = setupSocket()

//Start :- server start function
func Start() {
	//Socket io connection event listener
	socketConnectionListener()

	//Socket io beacon listner
	socketBeaconListener(beaconWriterCallback)

	//Socket io connection close listener
	socketCloseListener(io)

	setupHTTPServer(env.Port, io)
}

func setupSocket() *socket.Server {

	transporter := websocket.Default
	transporter.CheckOrigin = func(req *http.Request) bool {
		return true
	}

	options := &engineio.Options{Transports: []transport.Transport{transporter}}
	server, err := socket.NewServer(options)
	util.LogError("cannot start socket server", err)

	go server.Serve()
	return server
}

func setupHTTPServer(port string, io *socket.Server) {
	http.Handle("/socket.io/", middleware.EnableCors(io))
	util.LogInfo("Serving at localhost:" + port)
	util.LogFatal(http.ListenAndServe(":"+port, nil))
	defer io.Close()
}

func socketConnectionListener() {
	io.OnConnect("/", func(s socket.Conn) error {
		util.LogInfo("connected....:", s.RemoteAddr().String())
		s.Emit("ack", s.RemoteAddr().String())
		return nil
	})
}

func socketCloseListener(io *socket.Server) {
	io.OnDisconnect("/", func(s socket.Conn, msg string) {
		util.LogInfo("closed....:", s.RemoteAddr().String(), msg)
		s.Close()
	})
}

func socketBeaconListener(callback Message) {
	io.OnEvent("/", "beacon", func(s socket.Conn, msg string) {
		s.Emit("msgAck", "Recived msg")
		// util.LogInfo(msg)
		callback(msg + "\n")
	})
}

func beaconWriterCallback(message string) {
	fmt.Print(".")
	//

	//Perform action

	//
}

`

**Comment by Albinzr** [comment]
You mentioned  this issue was fixed, why did this issue came then and how was this solved

**Comment by Albinzr** [comment]
![image](https://user-images.githubusercontent.com/7425577/80920672-e1b79a00-8d8e-11ea-8bb0-f51eebb65250.png)
This is happening alot now,  I can atleast start looking why it's happening but the error dosent say anything properly

**Comment by Albinzr** [comment]
Are there any one else facing this issue? And how many project are using go-socket.io for production?

**Comment by Albinzr** [comment]
@adrianmxb Any progress on this issue?, Because of this unexplained issue im not able to use it in production 
Let me know once this is production ready.

**Comment by adrianmxb** [comment]
I tried reproducing your issue but it doesn't appear for me.

How large is the payload you are transfering?
How many clients are active?
How is the connection closed?
Are you sure that you are using v.1.4.3?

**Comment by Albinzr** [comment]
@adrianmxb 
1.Payload varies from 20kb to 4mb, Data is send as string
2.Connections Im seeing issue even when there is 2 to 5 active connections.
3. Connection is closed when client browser is closed
`
     io.OnDisconnect("/", func(s socket.Conn, msg string) {
         s.Close()
     })
`
4.Yes
copy for go.mod
`     	
     github.com/googollee/go-engine.io v1.4.3-0.20200220091802-9b2ab104b298
     github.com/googollee/go-socket.io v1.4.3
`

**Comment by Albinzr** [comment]
@adrianmxb Have you checked it?

**Comment by Albinzr** [comment]
I decided to user another socket lib, I really like this lib but there is huge cpu resource usage without any need and unknown messages that just pop up all the time, So cant use it in production
