### ISSUE TITLE
How to push to the designated person?

### ISSUE THREAD

**Issue by nelsonkti** [googollee/go-socket.io#345]
推送消息给指定的人

**Comment by jianzhiyao** [comment]
加入同一个房间，然后发送消息到这个房间进行处理
join the same room and send message to that room

**Comment by nelsonkti** [comment]
只有房间的概念？

**Comment by jianzhiyao** [comment]
@nelsonkti 我试过没问题的
```
server.BroadcastToRoom("/", "bcast", "event:name", msg)
```

**Comment by nelsonkti** [comment]
@jianzhiyao  我的代码是这样的，帮忙看看是否有用错？
 - Go version: [e.g. v1.14]
 - Server version [e.g. go-socket.io v1.4]

```
if err != nil {
		log.Fatal(err)
	}
	server.OnConnect("/", func(s socketio.Conn) error {
		s.SetContext("")
		s.Join("bcast")

		fmt.Println("connected:", s.ID())
		return nil
	})

	server.BroadcastToRoom("/", "bcast", "notice", "你哈222你哈222")


	//server.OnEvent("/", "notice", func(s socketio.Conn, msg string) {
	//	fmt.Println("notice:", msg)
	//	s.Emit("reply", "have "+msg)
	//})

	server.OnEvent("/chat", "msg", func(s socketio.Conn, msg string) string {
		s.SetContext(msg)
		server.BroadcastToRoom("", "bcast", "msg", "你好")


		return "recv " + msg
	})
	server.OnEvent("/", "bye", func(s socketio.Conn) string {
		last := s.Context().(string)
		s.Emit("bye", last)
		s.Close()
		return last
	})
	server.OnError("/", func(s socketio.Conn, e error) {
		fmt.Println("meet error:", e)
	})
	server.OnDisconnect("/", func(s socketio.Conn, reason string) {
		fmt.Println("closed", reason)
	})
	go server.Serve()
	defer server.Close()
```
```
<body>
<ul id="messages"></ul>
<form action="">
    <input id="m" autocomplete="off" /><button>Send</button>
</form>
<script src="https://cdn.socket.io/socket.io-1.2.0.js"></script>
<script src="https://code.jquery.com/jquery-1.11.1.js"></script>
<script>
    var socket = io("ws://localhost:8000", {transports: ['websocket']});
    // socket.emit('msg', 'hello');
    var s2 = io("ws://localhost:8000/chat", {transports: ['websocket']});
    socket.on('reply', function (msg) {
        $('#messages').append($('<li>').text(msg));
    });
    $('form').submit(function () {
        s2.emit('msg', $('#m').val(), function (data) {
            $('#messages').append($('<li>').text('ACK CALLBACK: ' + data));
        });
        socket.emit('notice', $('#m').val());
        $('#m').val('');
        return false;
    });
</script>
```

**Comment by xin7c** [comment]
求问@nelsonkti 

我后端写的
`	server.OnEvent("/chat", "notice", func(s socketio.Conn, msg string) string {
		s.SetContext(msg)
		log.Println("chat => ", s.URL().RawQuery)
		log.Println("chat => notice:", msg)
		s.Emit("reply", "recv " + msg)
		return "recv " + msg
`

前端用的socket.io-client

`var name = 'name_chat'
      this.socket = io('/chat', {
        query: {
          name
        },
        transports: ['websocket']
        // forceNew: true,
        // reconnectionAttempts: 3
      })`

我发现当我不传query参数的时候可以发到namespace chat，但是只要我带了query，后端就不停的重试，并且触发OnDisconnect，reason是client namespace disconnect

快疯了，请问你们是怎么前后端通过namespace连接的啊？

**Comment by nelsonkti** [comment]
@mrfoe7  Should it be a bug?

**Comment by nelsonkti** [comment]
> 求问@nelsonkti
> 
> 我后端写的
> 
> ```
> server.OnEvent("/chat", "notice", func(s socketio.Conn, msg string) string {
> 		s.SetContext(msg)
> 		log.Println("chat => ", s.URL().RawQuery)
> 		log.Println("chat => notice:", msg)
> 		s.Emit("reply", "recv " + msg)
> 		return "recv " + msg
> ```
> 
> 前端用的socket.io-client
> 
> ```
> var name = 'name_chat'
>       this.socket = io('/chat', {
>         query: {
>           name
>         },
>         transports: ['websocket']
>         // forceNew: true,
>         // reconnectionAttempts: 3
>       })
> ```
> 
> 我发现当我不传query参数的时候可以发到namespace chat，但是只要我带了query，后端就不停的重试，并且触发OnDisconnect，reason是client namespace disconnect
> 
> 快疯了，请问你们是怎么前后端通过namespace连接的啊？

我尝试了一下，用的库里面的例子，并没有出现你们这种情况；而且接受数据也是正确的
