### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by LoloAtHu** [googollee/go-socket.io#347]
**Describe the bug**
When listening on the server side whith namespace '/' and '/chat', I can connect to both these namesapces and send messages without query parameters. But when I connect to the server with query parameters, it does not work. Even the connect can not be establised.

**To Reproduce**
This can be reproduced in the example/default-server/main.go server. Only by conneting to the server with:
s1  = io("/chat")
s2 = io("/chat", {query: {username: 'lolo'}})

**Expected behavior**
With query parameters and specified namespace, it can connect to the server and emit message in the namespace.

**Environment (please complete the following information):**
 - Go version: [e.g. v1.14]
 - Server version [e.g. go-socket.io v1.4]
 - Client version [e.g. socket.io v2.0]

**Additional context**

**Comment by justinkiang** [comment]
I am observing the same behavior too,  Looks like the client keeps dropping the connection if a query param exists

**Comment by stong1994** [comment]
I met the same error and wanna know if there has some solutions

**Comment by alexliu2360** [comment]
In source code googollee\go-socket.io\conn.go, line 248:
`
handler, ok := c.handlers[header.Namespace]
`
this line doesn't seperate namespace and querys, you can seperate it by yourself as:
`
v := strings.Split(header.Namespace, "?")
`

**Comment by stong1994** [comment]
@alexliu2360  thanks a lot
