### ISSUE TITLE
[Question]how do i get the value of "any"

### ISSUE THREAD

**Issue by xin7c** [googollee/go-socket.io#348]
in my project, i was coding like this:
```
router.GET("/socket.io/*any", gin.WrapH(server))
```

but i want get this "any"，plz tell me how？？

**Comment by exapsy** [comment]
@xin7c What do you what do you mean exactly? What is it that you want to do? 
- Do you want to host your server on a different path?
- Or do you want to have dynamic namespaces under your socket.io path where Socket.IO deals with them for you? This one is already a default behavior, it's just called namespaces in Socket.IO.

## Hosting on a different path

If you want to host your socket.io server on a different path, you absolutely can. You dont have to do anything else than what you're already doing.
The one who has to care about the path is not the backend (thus you dont have to get this "any" for any reason), but the frontend.

The frontend I think will have to write this to connect to your server's websockets, according to
[Socket.io custom path guide](https://socket.io/docs/client-api/#With-custom-path)
```js
const socket = io("/namespace", {
    path: "/socket.io/*any*",
})
```

## Having namespaces

On the other hand, If you dont want to serve your server on a different path, and all you want is just namespaces, then what you're talking is literally just Socket.IO supported namespaces. You dont have to put them in your `router.GET`, Socket.IO takes care of those paths for you.

This is how you treat namespaces

### Backend
```golang
server.onConnect("/namespace", ... )

server.OnEvent("/namespace", "room", ... )

server.OnError("/namespace", ... )

server.OnDisconnnect("/namespace", ... )
```

### Frontend
```js
// window.location/socket.io/namespace
const socket = io("/namespace")

// localhost:8000/socket.io/namespace
const chat = io("http://localhost:8000/chat")
```

**Comment by erkie** [comment]
Great explanation @exapsy
