### ISSUE TITLE
Memory and OnDisconnect Issue

### ISSUE THREAD

**Issue by Albinzr** [googollee/go-socket.io#351]
**Describe the bug**
1. OnDisconnect not being called most of the time and prints message **Did you forget to Close() the ReadCloser from NextReader?**
2. Another issue is that memory increases when multiple connection happens but never releases after connection closes which leads to memory crash

**To Reproduce**
Have multiple socket client connect from browser and then sudden close of tabs 

**Expected behavior**
All active socket should have closed 

**Environment (please complete the following information):**
 - Go version: go1.13.5
 - Server version v1.4.3
 - Client version 2.3.0

**Additional context**
Logs message **Did you forget to Close() the ReadCloser from NextReader?**

**Comment by Albinzr** [comment]
Any update on this issue?
Are there anyone else using this in production?

**Comment by stong1994** [comment]
I met the second bug, do you have any solutions?

**Comment by Albinzr** [comment]
@stong1994, Nop, Also didn't get any support from the community also so i used another lib

**Comment by stong1994** [comment]
@Albinzr which lib? i think i should take another lib also.

**Comment by Albinzr** [comment]
@stong1994 an internal one that we wrote, it's a private repo

**Comment by stong1994** [comment]
@Albinzr All right,  but still thank you.
