### ISSUE TITLE
BroadcastToRoom blocks until all messages have been emited, causing delays with slow connections

### ISSUE THREAD

**Issue by lianmengworld** [googollee/go-socket.io#355]
**Describe the bug**
 "broadcast to room" will block broadcasting for a short time

**Comment by pkwong4321** [comment]
it's because when some clients disconnect, the connection is not never closed yet (polling client takes quite some time)
when we keep emitting to them, data is written into writeChan until it's full, then it will block
in such case, i suggest we add a sensible timeout in 
```func (c *conn) write(header parser.Header, args []reflect.Value)```

but it will still timeout at the next emit until it's closed
should we close these connections?
i can make a PR if we should go this direction

**Comment by erkie** [comment]
Seems to be related to this:

**Comment by erkie** [comment]
Seems to be related to this: https://github.com/googollee/go-socket.io/blob/master/broadcast.go#L93 Not sure why it's locking even during the .Emit. I assume it only needs to block while actually reading the current list of connections. Been trying to release the lock during Emit, running into other issues in production, so can't say if it works.

**Comment by jtcho** [comment]
To add another data point, I ran into this while trying the simple example of broadcasting to multiple clients when a client has disconnected - it blocks entirely until the read timeout is hit.

**Comment by erkie** [comment]
It seems to be a fairly easy fix. Not letting the `.Emit` call in `broadcast.Send` block by using go-routines. This is how the node-implementation works.

https://github.com/googollee/go-socket.io/blob/0c0217c03e1d56780f85e83696203837b62f58ef/broadcast.go#L101

```go
// change
connection.Emit(event, args...)
// to
go connection.Emit(event, args...)
```

@mrfoe7 what are your thoughts here?

**Comment by Karafs** [comment]
> It seems to be a fairly easy fix. Not letting the `.Emit` call in `broadcast.Send` block by using go-routines. This is how the node-implementation works.
> 
> https://github.com/googollee/go-socket.io/blob/0c0217c03e1d56780f85e83696203837b62f58ef/broadcast.go#L101
> 
> ```go
> // change
> connection.Emit(event, args...)
> // to
> go connection.Emit(event, args...)
> ```
> 
> @mrfoe7 what are your thoughts here?

Has anyone tried this solution? Is that OK?

**Comment by erkie** [comment]
We're running this in production for a long time

**Comment by Karafs** [comment]
> We're running this in production for a long time

thanks.

**Comment by tqrj** [comment]
Has the problem been solved yet?
