### ISSUE TITLE
Namespace not working[BUG]

### ISSUE THREAD

**Issue by wukaMM** [googollee/go-socket.io#361]
**Describe the bug**
Hi, I am using go-socket.io 1.4.3, and if the client request a connection with namespace "/", it works very well. But if the namespace is something like "/test", the server's OnDisconnect event will be triggered

**To Reproduce**

// Client, this desn't work

    var socket2 = io("http://localhost:5000/test");
   

// Client, this works well

    var socket2 = io("http://localhost:5000");
   

// Server
    
    server, err := socketio.NewServer(nil)
    if err != nil {
        log.Fatal(err)
    }
    server.OnConnect("/", func(s socketio.Conn) error {
        s.SetContext("")
        fmt.Println("connected:", s.ID())
        return nil
    })
    server.OnDisconnect("/", func(s socketio.Conn, reason string) {
        fmt.Println("closed", reason)
    })

And I received 

connected: 1 
closed client namespace disconnect
connected: 2
closed client namespace disconnect
connected: 3
closed client namespace disconnect
connected: 4
closed client namespace disconnect
connected: 5
closed client namespace disconnect
...

Anyone can help ?

**Environment (please complete the following information):**
 - Go version: [e.g. v1.14]
 - Server version [e.g. go-socket.io v1.4.3]
 - Client version [e.g. socket.io v2.1.1]

**Comment by wukaMM** [comment]
Hi,
I find out the reason.
When the client side is

```
const socket = io("http://127.0.0.1:8080/test", { 
        transport : ['websocket'],
        autoConnect: true,
        query: {
          auth: '1'
        }
      });
```
Both namespace and query are included, and then, the client can't connect to the server.

If there is only namespace or query included, the connect runs well.

And also, my socket.io client is 2.1.1, which convert the namespace from '/test' to '/test?auth=1'. While the client 1.4.0 is correct and works well.

How can I figure this out by using version 2.1.1 ?
Please help, thank you.

**Comment by AndrewOrr** [comment]
This still seems to be an issue when using the base example.
