### ISSUE TITLE
OnConnect returning error still allow connection/handshake

### ISSUE THREAD

**Issue by sshmaxime** [googollee/go-socket.io#366]
**Describe the bug**
I'm trying to prevent clients to deal with a namespace before auth. Therefore I do some auth on connect, like that:

```go
wsHandler.OnConnect("/rooms", func(socket socketio.Conn) error {
		if !isClientAuth(socket) {
			return errors.New("cli not auth")
		}
		return nil
})
```

then I set up a handler that will read message from incoming connected clients on `/rooms`:

```go
wsHandler.OnEvent("/rooms", "message", func(socket socketio.Conn, obj interface{}) error {
		fmt.Println(obj)
		return nil
})
```

But I still receive the message from the client even if OnConnect returned an error on its connection.

Is that normal ?

**Expected behavior**

if OnConnect returns an error, don't authorize the connection.

**Environment (please complete the following information):**
 - go version: `go1.14.5 darwin/amd64`
 - Server version: `github.com/googollee/go-socket.io v1.4.3`
 - Client version: `"socket.io-client": "^2.3.0"`

**Comment by erkie** [comment]
Please provide working sample code.
