### ISSUE TITLE
Go 1. 9 is not released

### ISSUE THREAD

**Issue by AbhigyanKumar** [googollee/go-socket.io#369]
It is provided in the `[README.md](README.md)` that Go 1.9+ is required. However, the latest stable versions Go is 1.15.

**Comment by mrfoe7** [comment]
Hey, @AbhigyanKumar. I apologize, but I don't understand what this is asking.
The Latest stable versions Go is 1.15 > Go 1.9. it is mean than you can user go-socket.io in golang latest versions
