### ISSUE TITLE
Goroutine example

### ISSUE THREAD

**Issue by jj0e** [googollee/go-socket.io#370]
Can we get an example of returning a value from a goroutine/channel to the websocket server? I'm a bit confused on how it would work. Thanks

**Comment by mrfoe7** [comment]
Hey, @jj0e 
Do you can give more informations about your problem?

**Comment by bbars** [comment]
@mrfoe7, it seems that @jj0e wants to run goroutine asynchronously within handler. This is how it might look like (IT IS NOT a working example, just a design suggestion):

```golang
server.OnEvent("/chat", "msg", func(s socketio.Conn, msg string) <-chan string {
	out := make(chan string)
	go func() {
		// ...
		out <- "recv " + msg
		close(out)
	}()
	return out
})
```

**Comment by erkie** [comment]
I'd say this is just a basic go-question. Using channels to block the func until a goroutine is finished. https://scene-si.org/2020/05/29/waiting-on-goroutines/
