### ISSUE TITLE
Make it easier to get running with CORS

### ISSUE THREAD

**Issue by erkie** [googollee/go-socket.io#372]
A lot of people are running into hard-to-debug issues because of CORS configuration. The answer (besides your server handler of choice):

```go
server, err := socketio.NewServer(&engineio.Options{
	Transports: []transport.Transport{
		polling.Default,
		&websocket.Transport{
			CheckOrigin: func(r *http.Request) bool {
				return true
			},
		},
	},
})
```

It's hard to find and it should be easier. Alternatives: 

- Should we hoist up the `CheckOrigin` to the main `engineio.Options` and feature it prominently in documentation?
- Or should we change the default behaviour to allow all origins? 
- Just change the documentation?

**Comment by bbars** [comment]
It is a good idea to hoist up the `CheckOrigin` to the main `engineio.Options`, because it is a security option, so it shouldn't depend on used transport. Unfortunately, it is an incompatible change of a nested package `go-engine.io` :(

**Comment by erkie** [comment]
@bbars that's no problem, go-engine.io is "our" repo too, so no issue with changing that. But with this PR they will become 1 anyway :) https://github.com/googollee/go-socket.io/pull/373

**Comment by adrianmxb** [comment]
This should be refactored in a more general way I think.
If I remember correctly the Access-Control-* headers aren't set correctly which really blows when relying on polling.

**Comment by erkie** [comment]
True. It's a bit weird that this library has a concept of CORS at all, when the server middleware should be dealing with it, or? Looking at what it does, I'm not sure why it's an issue at all.

**Comment by bbars** [comment]
It's an issue because default behaviour of engine.io and gorilla's websocket is to deny interaction. In addition, there's an [error reporting issue](https://github.com/googollee/go-engine.io/issues/91), that makes debugging very hard.

**Comment by Vindexus** [comment]
For anyone else getting CORS issues with the initial GET request, I used the code above but modified it so that both the polling and websocket transports used the same CORS function
`
	allowOrigin := func(r *http.Request) bool {
		return true
	}
	server, err := socketio.NewServer(&engineio.Options{
		Transports: []transport.Transport{
			&polling.Transport{
				Client: &http.Client{
					Timeout: time.Minute,
				},
				CheckOrigin: allowOrigin,
			},
			&websocket.Transport{
				CheckOrigin: allowOrigin,
			},
		},
	})
`

**Comment by mrfoe7** [comment]
Added into PR https://github.com/googollee/go-socket.io/pull/477
