### ISSUE TITLE
[ref] need refactor conn service with default context

### ISSUE THREAD

**Issue by mrfoe7** [googollee/go-socket.io#374]
We need use context interface from default library without interface{} 
Code - https://github.com/googollee/go-socket.io/blob/master/conn.go#L30

**Comment by erkie** [comment]
Do you mean this context? https://golang.org/pkg/context/ Isn't that a different thing from what the `.Context` field is for?

**Comment by mrfoe7** [comment]
Yeap, this. At now used 
```go
func (c *namespaceConn) SetContext(ctx interface{})
```
I will suggest to use:
```
func (c *namespaceConn) SetContext(ctx context.Context) 
```

**Comment by erkie** [comment]
But why do we need the `context.Context` here? As far as I understand `context.Context` is for completely different things. `SetContext` is just for attaching arbritrary values to the connection which can then be accessed in the `OnEvent`/`OnDisconnect`, right? `contet.Context` is for managing timeouts and other things?

**Comment by mrfoe7** [comment]
> contet.Context is for managing timeouts and other things?

yeap, sure, but you may attaching arbritrary values to the connection too and `context.Context` is basic way to do it

**Comment by erkie** [comment]
I don't see the benefit? `interface{}` does the exact same thing without depending on another package?

**Comment by mrfoe7** [comment]
Usage `context` is best practice in golang

**Comment by erkie** [comment]
I just don't see how it can be best practice for this use-case. The `context.Context` functionality won't be used? We just want it to carry an `interface{}` type that the user defines?

```
func WithCancel(parent Context) (ctx Context, cancel CancelFunc)
func WithDeadline(parent Context, d time.Time) (Context, CancelFunc)
func WithTimeout(parent Context, timeout time.Duration) (Context, CancelFunc
```

**Comment by mrfoe7** [comment]
Look up https://github.com/googollee/go-socket.io/pull/460
