### ISSUE TITLE
[BUG]Why client need to wait a pingInterval time for server replies?

### ISSUE THREAD

**Issue by ardingchen** [googollee/go-socket.io#383]
My client is web page using socketio.js, and the IO server is created by 
socket = io({
   transports: ['websocket']
 });

When the websoket is created, server send a message by Emit(...) after OnConnect callback, but in actually the message is sent for a pingInterval ms delay at server side. The message flow is bellow:
![websocket_server_reply_delay](https://user-images.githubusercontent.com/20982103/56585410-56021e00-6610-11e9-9656-af8a8a0c01c7.png)

And each time when I send a message to client, it will be delay for a pingInterval time.
How  to to reduce the deday time at server side? 
Thanks a lot!

**Comment by erkie** [comment]
This is not related to the master branch `func (s *session) nextReader() (base.FrameType, base.PacketType, io.ReadCloser, error) {` looks different now. Closing this
