### ISSUE TITLE
serverConn closed without calling serverConn.OnClose()

### ISSUE THREAD

**Issue by W1llyu** [googollee/go-socket.io#384]
Some connections are closed but they are still in session manger and the amount of connection in `engineio.Server` is not decreasing.

I tracked this and found sometimes connections closed without calling `ServerConn.OnClose()`, and this may be caused by the lock in `polling.Server`.

So what if waiting for the lock in `polling.Server.Close()` to touch off the callback of `ServerConn`?

**Comment by erkie** [comment]
Nice find (slowpoke). This can't related to the current 1.4 branch, AFAIK. If it still happens, please reopen!
