### ISSUE TITLE
Join SocketID to Room

### ISSUE THREAD

**Issue by recfish** [googollee/go-socket.io#387]
If I don't have the underlying connection, but do have the socketID, how can make the connection join a room. Essentially, I am looking for:
`JoinRoom(namespace string, room string, socketID string)`

**Comment by erkie** [comment]
To find the underlying Conn you can fetch all rooms using `server. Rooms`, the iterate each one using `server.ForEach` to iterate and compare the `.ID()`.

https://github.com/googollee/go-socket.io/blob/master/server.go#L146
