### ISSUE TITLE
Ack data is marshalled twice

### ISSUE THREAD

**Issue by uri111** [googollee/go-socket.io#388]
**Describe the bug**
Ack data is marshalled twice, producing a string like the following:
`"{\"User\":true,\"Name\":\"foo\"}"`
which throws an error client side

**To Reproduce**
marshal a struct into bytes. convert to string. Return string.

**Expected behavior**
when sending json in an acknowledgment, it should not be remarshalled

**Comment by erkie** [comment]
Can you include a code sample that can duplicate this issue?

**Comment by aifaniyi** [comment]
> **Describe the bug**
> Ack data is marshalled twice, producing a string like the following:
> `"{\"User\":true,\"Name\":\"foo\"}"`
> which throws an error client side
> 
> **To Reproduce**
> marshal a struct into bytes. convert to string. Return string.
> 
> **Expected behavior**
> when sending json in an acknowledgment, it should not be remarshalled

Rather than convert your struct to json and then string, the socket's Emit function allows you send your struct as-is. The Emit function handles serialization of you struct to json which you can automatically consume as json data on the client.

```golang
m := Model{User: true, Name: "foo"}
marshalled, _ := json.Marshal(m)
s.Emit("ack", string(marshalled))
```

You should

```golang
m := Model{User: true, Name: "foo"}
s.Emit("ack", m)
```

and on your client

```javascript
socket.on('reply', function(msg) {
   console.log(msg) // would be {"User":true,"Name":"foo"}
   console.log(msg.User) // true
   console.log(msg.Name) // foo
}
```
