### ISSUE TITLE
Erroneously named parameter in socket.Conn.Emit

### ISSUE THREAD

**Issue by conjohnerton** [googollee/go-socket.io#392]
**Describe the bug**
socket.Conn.Emit has a first parameter labelled `msg`. This is a bit misleading, as it's actually meant for the eventName.

**Expected behavior**
You can see the expected parameter naming convention here: with eventName being the label of the first parameter, not msg. 
https://socket.io/docs/server-api/#socket-emit-eventName-%E2%80%A6args-ack

**Additional context**
This issue is pretty much only with the name of the parameter, but everything else seemed fine. :smile:

**Comment by mrfoe7** [comment]
Resolved!
