### ISSUE TITLE
Using the client of the 0.9.x branch, I am disconnected after 15 seconds...

### ISSUE THREAD

**Issue by svanharmelen** [googollee/go-socket.io#40]
Without any waring or info being logged... It runs just fine the first 15 seconds, but that the fun is over. Any pointers on where to look anything know about an issue like this?

**Comment by zhengying** [comment]
+1 Same problem! any update ??

**Comment by svanharmelen** [comment]
@zhengying, it's been a couple of months ago since I fixed this locally but just made a PR which would fix this (if I recall the issue correctly). So if you could test again with the code in PR #58 that would be great.

**Comment by zhengying** [comment]
Thanks you!
But your code is too old. no session.go in latest version, the change is so big now,   I want a version keep update.  may be It's useful to someone else.

**Comment by svanharmelen** [comment]
Ah... Well my code isn't too old, but it's for the 0.9.x branch where this issue was opened for (see title of this issue) :wink:

So I think you reacted to a wrong issue then, if you are using the 1.x branch (master)...

**Comment by zhengying** [comment]
Oh, sorry I used master branch,   My problem already find, it's cause by client js error, 
Why don't you use the 1.x branch, It's seem more stable.

**Comment by svanharmelen** [comment]
Well... I only used the client part as I was talking to an exiting backend which required the 0.9.x branch :smiley:

**Comment by svanharmelen** [comment]
Fixed by PR #58
