### ISSUE TITLE
Socket Join Rooms

### ISSUE THREAD

**Issue by onlylin** [googollee/go-socket.io#400]
1、Is socket OnConnect will join a default room?
2、When a socket connection join room id 2 and call conn.Rooms() print [1,2] and another socket connection join room id 3 and call conn.Rooms() print [2,3]. I am confused that when a new socket connection join a new room, First, it will be join a existing room, then join a new room.

**Comment by mrfoe7** [comment]
> 1. Is socket OnConnect will join a default room?

yes - default room is a main and - namespace - "/"

> it will be join a existing room, then join a new room.

Oh... damn, it is bug
