### ISSUE TITLE
_example default-http & go-echo failed with "invalid sid"

### ISSUE THREAD

**Issue by jeremywangjun** [googollee/go-socket.io#402]
![Xnip2020-11-04_17-14-06](https://user-images.githubusercontent.com/5435403/98092762-03224b80-1ec2-11eb-9bfc-d38acae0806c.jpg)
![Xnip2020-11-04_17-15-14](https://user-images.githubusercontent.com/5435403/98092794-0d444a00-1ec2-11eb-83b7-3f54de10f840.jpg)

Requests flow :

1. GET /socket.io/?EIO=3&transport=polling&t=1604474977915-0 HTTP/1.1 
2. HTTP/1.1 200 OK 
3. POST /socket.io/?EIO=3&transport=polling&t=1604474977923-1&sid=7q HTTP/1.1 
4. HTTP/1.1 400 Bad Request  (text/plain)

**Comment by asura-10** [comment]
what is the solution?
