### ISSUE TITLE
All examples are outdated for v1.4.4

### ISSUE THREAD

**Issue by cyantarek** [googollee/go-socket.io#407]
Please update the examples for the latest version

**Comment by PoseidonCoder** [comment]
I can't even find any up-to-date documentation or examples on this.
I'm really interested in this package, please add more documentation.

**Comment by jianzhiyao** [comment]
can't not run any example successfully

**Comment by CoolRao** [comment]
more doc

**Comment by adrianmxb** [comment]
I'll look into it and update the examples/docs later this week.

**Comment by cp-sumi-k** [comment]
Can I Work On this?

**Comment by muhajirmuhajir** [comment]
Hi, I have updated the documentation for version 1.4.4. kindly check my PR here #438
