### ISSUE TITLE
Version incompatibility

### ISSUE THREAD

**Issue by natesales** [googollee/go-socket.io#416]
When instantiating a new socketio.Server with `sio = socketio.NewServer(nil)`, I'm getting a `assignment mismatch: 1 variable but socketio.NewServer returns 2 values`.

I'm guessing this is due to a version incompatibility but I can't seem to figure it out. My go.mod require block includes `github.com/googollee/go-socket.io v1.4.4` and I'm running `go build` in the root of the project directory which results in the error.

Any help would be greatly appreciated!

**Comment by wyattis** [comment]
Use `sio, err = socketio.NewServer(nil)` instead. It returns an error as well.

**Comment by mrfoe7** [comment]
Hey!
Look up examples into root path project
