### ISSUE TITLE
I need help to contribute a new feature: Redis Broadcast Adapter

### ISSUE THREAD

**Issue by vking34** [googollee/go-socket.io#420]
At the moment, ```go-socket.io``` does not support other broadcast adapters that are used to scale instances horizontally. 

On the other hand, ```socket.io``` has redis adapter:
https://github.com/socketio/socket.io-redis

Actually, I have been implemented the logic of redis adapter. But I am just new with Go, so I do not know how to abstract the broadcast adapter, and pass the redis configuration via server options.
In other words, if we pass / set redis adapter configuration, then we use redis broadcast adapter. and if we pass / set noting, we use the default broadcast.

Let's check my repo: https://github.com/vking34/go-socket.io
Feature Branch: ```feat/redis-adapter``` 

Could someone give me a helping hand?
Thank u so much.

**Comment by mrfoe7** [comment]
not actual
