### ISSUE TITLE
Problem with connection in react live mode

### ISSUE THREAD

**Issue by MikolajMGT** [googollee/go-socket.io#425]
Hello, I tried to connect with go-socket.io server (I used gin-cors from _example directory to avoid cors issues) from react app in live developer mode (running on local device). But I have a problem with connection to ws - when I enter the page nothing happens in console (no onConnect call) and after few seconds I'm getting few times
```
closed client namespace disconnect
meet error: write: timeout
```
Is there any way to configure it to work properly? It would make development much easier

**Comment by rr13k** [comment]
hi, I have the same question, please pay attention to it

**Comment by MikolajMGT** [comment]
Hi, I was playing with this few months ago and as far I remember the problem was version of socket.io on react side - in the description is written `Current this library supports 1.4 version of the Socket.IO client`. I didn't noticed it at first and when I was trying to use version 2, I was getting this problem :) When you will downgrade version of the client library in react it shuld work correctly :)
