### ISSUE TITLE
Seeing multiple-value uuid.NewV4() in single-value context error messages

### ISSUE THREAD

**Issue by SimonRuaGitHub** [googollee/go-socket.io#430]
It is necessary to use another third party provider for uuid usage since **the satori go.uuid repo is dead now**. This triggering compile error in the following code lines.

**Note: Although error is not visible when using go mod since it points to last release version, it is better to solve this issue, since redis broadcast artifact might be a good option for some people**

`..\..\go\src\github.com\googollee\go-socket.io\redis_broadcast.go:126:21: multiple-value uuid.NewV4() in single-value context
..\..\go\src\github.com\googollee\go-socket.io\redis_broadcast.go:358:26: multiple-value uuid.NewV4() in single-value context
..\..\go\src\github.com\googollee\go-socket.io\redis_broadcast.go:459:26: multiple-value uuid.NewV4() in single-value context
..\..\go\src\github.com\googollee\go-socket.io\redis_broadcast.go:497:26: multiple-value uuid.NewV4() in single-value context`

[Satori repo is dead](https://github.com/satori/go.uuid/issues/103)

**Comment by smhmh** [comment]
I has this problem too!

**Comment by arrayindex-dev** [comment]
[I made a fix. ](https://github.com/arrayindex-dev/go-socket.io/blob/master/redis_broadcast.go) Just replace your redis_broadcast.go file with this.

**Comment by DamareYoh** [comment]
@arrayindex-dev  you should probably consider migrating off of satori uuid. That repo has gone unmaintained for almost three years now. See the link in the reporter posted.

**Comment by arrayindex-dev** [comment]
> @arrayindex-dev  you should probably consider migrating off of satori uuid. That repo has gone unmaintained for almost three years now. See the link in the reporter posted.

Unfortunately this repo is being used in some production environments. Migrating off satori uuid would cause problems.

However, I agree that using Google uuid would be a better choice.

**Comment by DamareYoh** [comment]
Thanks for the repsonse @arrayindex-dev 

I should inform you that the version in use today is subject to a serious vulnerability where periodically the library will produce a UUID that has mostly 0's in it. https://snyk.io/vuln/SNYK-GOLANG-GITHUBCOMSATORIGOUUID-72488

The maintainer hasn't bothered to release this fix via a tag. While yes migrating off of libraries always sucks, the unfortunate reality is that you are creating a problem for your users by not migrating away from a dead library. I think you should reconsider your position.

Luckily, there's a fork of satori/go.uuid that's a drop in replacement and is actually maintained. https://github.com/gofrs/uuid. This should at least make it easier to migrate.

**Comment by mrfoe7** [comment]
Fixed into v1.4.5 release
