### ISSUE TITLE
I want to use unix-socket connection to local redis-server instead of TCP.

### ISSUE THREAD

**Issue by strizhechenko** [googollee/go-socket.io#434]
> **Is your feature request related to a problem? Please describe.**

Not a problem at all, I can work via TCP, but, you know, microoptimizations, low latencies, etc.

> **Describe the solution you'd like**

Something like:

``` go
ok, err := server.Adapter(&socketio.RedisUnixAdapterOptions{
    unixsocket: "/tmp/redis.sock",
    Prefix: "socket.io",
})
```
to keep RedisAdapterOptions backward-compatible and don't broke other software that relies on it. If the idea is acceptable, I can try to implement it myself.

**Comment by mrfoe7** [comment]
Thanks for you feedback, I'll add this functionality into next release

**Comment by mrfoe7** [comment]
Hey, @strizhechenko 
I added new options into `RedisAdapterOptions` by this PR https://github.com/googollee/go-socket.io/pull/464
To be carefully to use this functionality. I think we'll change in new major version

**Comment by mrfoe7** [comment]
Implemented
