### ISSUE TITLE
How to push []byte using protobuf？

### ISSUE THREAD

**Issue by nelsonkti** [googollee/go-socket.io#439]
**Describe the bug**
Before the push message is []byte, but what is pushed out is string, why is this?

Before the push messag：
![image](https://user-images.githubusercontent.com/58064299/115380841-90095900-a205-11eb-9b60-fcce3af83c48.png)
 pushed out：
![image](https://user-images.githubusercontent.com/58064299/115380859-95ff3a00-a205-11eb-912b-c9c3a76ac33e.png)

**Comment by imcarrow** [comment]
Why was this question closed?
What do you think? I want to send a binary, but not base64. How can I do that?

**Comment by UnderTreeTech** [comment]
I have the same problem, I want to emit plain json string to client, but it encrypt to base64 format default, how to disable base64 encrypt?

**Comment by Charlotte3240** [comment]
How to send binary data ? not base64

**Comment by nelsonkti** [comment]
Because I don't think that pushing through binary form with websocket optimization can greatly improve the performance of the system, so, I closed the question.

**Comment by nelsonkti** [comment]
@sshaplygin what you think？

**Comment by UnderTreeTech** [comment]
> 

I think the point is we want send binary data directly, not the performance issue.

**Comment by jqiris** [comment]
I think the point is we want send binary data directly, not the performance issue.
