### ISSUE TITLE
0.9.x branch client single message sent received duplicate at Node.js 0.9.14 server

### ISSUE THREAD

**Issue by h00kwurm** [googollee/go-socket.io#44]
When i'm using the go socket io client from the 0.9.x (branch/tag/whatever) against the node.js socket io v0.9.14 i'm receiving duplicate messages at the server side. Has anybody seen this or know what I'm doing wrong or whether there might be a bug along the way (socket->codec->websocketFrameWriter->hybi->socket) If it's relevant at all, I don't have the option to use socket io 1.+. so there's that as well.

edit: apologies for bad formatting. 

Using this client code on the go side: 
        client, err := socketio.Dial("http://127.0.0.1:8088")
        if err != nil {
            fmt.Println(err)
            return
        }

```
client.On("connect", func(ns *socketio.NameSpace) {
    fmt.Println("connected to socket!")
    ns.Emit("message", "here is a test message")
})

client.Run()
```

And this code at the Node.js server side: 
           `var io = require('socket.io');`
           `var express = require('express')`

```
    var app = express()
      , server = require('http').createServer(app)
      , io = io.listen(server)

    server.listen(8088)

    io.sockets.on('connection', function(socket) {
      socket.on('message', function(data) {
        console.log(data)
      });
    });
```

I see this at the server side: 
    ...
    debug - websocket writing 1::
    here is a test message
    here is a test message
    info  - transport end (socket end)
    ...

**Comment by erkie** [comment]
Closing this because it's very very old. Please feel free to re-open if you still think it's an issue.
