### ISSUE TITLE
how to receive json data from client?

### ISSUE THREAD

**Issue by piksonGit** [googollee/go-socket.io#440]

**Comment by piksonGit** [comment]
![image](https://user-images.githubusercontent.com/9671142/115512727-dc5fa200-a2b4-11eb-91ac-dc5778ddedfe.png)
I don't know if I am smart or foolish

**Comment by mrfoe7** [comment]
Do you can describe about your case?

If i understood correctly your issue this next code will help to you
JSON is structured string type:

```go
type ChatMsg struct {
	Type string
}
...
server.OnEvent("/chat", "msg", func(s socketio.Conn, msg string) string {
    var chatMsg ChatMsg
    err := json.Unmarshal([]byte(msg), &chatMsg)
    if err != nil {
        return "load error message"
    }
    //.... some todo
    log.Println("chat msg", chatMsg.Type)

    return "recv " + msg
})
```

If you send from client: 
```
 {"type": "client message"}
 ```
 You'll parse my code correctly, but if you'll send raw message, `json.Unmarshal` return error

**Comment by googollee** [comment]
As @piksonGit comes from China, I'll reply in Chinese here.

Go里一个函数也是一个值，可以符合`interface{}`。参见 https://tour.golang.org/methods/14。

关闭原因：这不是go-socket.io相关的问题。
