### ISSUE TITLE
UUID bug

### ISSUE THREAD

**Issue by grtfou** [googollee/go-socket.io#445]
Thanks for this repo.

I upgrade go-socket.io from  ```v0.0.0-20180921171217-25e1f67559cf``` to ```v1.4.5```
and I got the error.

```bash
../../../pkg/mod/github.com/gobuffalo/uuid@v2.0.5+incompatible/generator.go:32:13: undefined: uuid.NewV2
../../../pkg/mod/github.com/gobuffalo/uuid@v2.0.5+incompatible/uuid.go:41:7: undefined: uuid.V2
```

I try re-install go-socket.io again and got the same error. Have any idea?

P.S.
  * Go == v1.16.3
  * MacOS == v11.2.1

Thank you.

**Comment by mrfoe7** [comment]
Hey!
Did you to do `go mod tidy` in your project?

**Comment by grtfou** [comment]
Yeah, and I created `go.mod` again and got the same error message.
Maybe it's other library issues.
I'll keep try.
Thanks for your suggestion. 👍

**Comment by mrfoe7** [comment]
Thank you for feedback

**Comment by maxmcd** [comment]
Sorry, if anyone else gets here, the fix is (possibly).

```
go get -u github.com/gobuffalo/validate
```
