### ISSUE TITLE
when calling server side functions without specifying arguments, the client connection will break without errors

### ISSUE THREAD

**Issue by Jark** [googollee/go-socket.io#45]
Given this function on the go side of things:

```
server.On("connection", func(so socketio.Socket) {
    so.On("getInitialData1", func() string {
        fmt.Println("getInitialData1 called")
        return "initialData1"
    })
})
server.On("error", func(so socketio.Socket, err error) {
    log.Println("error:", err)
})
```

and this function on the js side of things:

```
socket.emit('getInitialData1', function (message) {
    appendToLog('getInitialData1Result: ' + message);
});
```

When I execute the emit for the first time, the message returns with a value of `undefined`.

Then when I execute the emit again nothing appears to work and the connection with the server seems to be in an invalid state.

If you need any more information please let me know.

**Comment by nfirvine** [comment]
Probably not relevant to @Jark any more, but I encountered the same problem. I suspect handler funcs with no arguments are not handled properly.

See https://github.com/googollee/go-socket.io/issues/121

**Comment by erkie** [comment]
Closing this because it's very very old. Please feel free to re-open if you still think it's an issue. (also #121 is newer :)
