### ISSUE TITLE
Support socket.io admin-ui panel

### ISSUE THREAD

**Issue by sshaplygin** [googollee/go-socket.io#450]
**Describe the solution you'd like**
Check and support admin-ui panel from https://github.com/socketio/socket.io-admin-ui

**Comment by googollee** [comment]
That could be hard for me. I'm not good at frontend. I'd like to expose some internal metrics in some way and make that admin UI another project.

Those metrics could be collected by other services like Prometheus.

**Comment by mrfoe7** [comment]
I added this issue for don't lost to it ))
