### ISSUE TITLE
Raw proposal for go-socket.io v2

### ISSUE THREAD

**Issue by sshaplygin** [googollee/go-socket.io#451]
**Is your feature request related to a problem? Please describe.**
Current libs version doesn't supported socket.io v2

It is not completed proposal version. I suggest some changes. At the future this document will be edit

## API: 

- Change create new server object 

    **Current version**
    ```go
    server := socketio.NewServer(nil)
    ```
    
    **New version**
    client code
    ```go
    server := socketio.New()
    ```
    inner code
    ```go
    // New create go-socket.io server instance
    func New(opts ...Options) *Server {
       ...
    }
    ```

- Hide `server.Serve()` and `server.Close()` method
  
    **Current version**
    ```go
    go server.Serve()
    defer server.Close()
    ```
    
    **New version**
    ```go
    //empty
    ```

- Change adapter interface

  **Current version**
    ```go
    ok, err := server.Adapter(&socketio.RedisAdapterOptions
    if err != nil {
		log.Println("error:", err)
		return
	}
    ```

  **New version**
    client code
    ```go
    err := server.Adapter()
    if err != nil {
		log.Println("error:", err)
		return
	}
    ```
    inner code
    ```go
    func (s *Server) Adapter(opts ...AdapterOptions) (error) {
        ...
    }
    ```

## Inner changes:

- Add level mode for full server logs

**Comment by googollee** [comment]
- `NewServer()`
 
As I still want to have client code, `NewServer()` is more clear that it returns a server, and `NewClient()` returns a client.

- `Serve()` and `Close()`

`Serve()` gives a preparing period before a server working.

```go
s := gio.NewServer()
// Prepare before the server working
go s.Serve()
```

Another we could keep that function, and make new creators like `LaunchServer()` which calls `Serve()` before returning.

I also hope to keep `Close()` to have a graceful way to quit a server. If someone wants a server running forever, they could ignore calling this function.

- Adaptor

I have more thoughts about the adaptor. I hope to support middleware to let adaptor hook messages, and no need to limit adaptor as Redis or other queue implementation.

**Comment by erkie** [comment]
I agree with @googollee here. I prefer to have the option to close a connection and choose to prepare the server, than to hide it inside the library. It's a bit more verbose but in this case I'd say it's a good thing

**Comment by googollee** [comment]
I think it's possible to remove `Serve()` function, by redesign engine.io. I'd like to do that in the new version and to see if it's possible to down-merge the new version to the old one. (If API doesn't change too much.)

**Comment by mrfoe7** [comment]
> If API doesn't change too much.

Why not? It is good changelog for new version ))

**Comment by mrfoe7** [comment]
In this [implementation](https://github.com/ambelovsky/gosf-socketio) run go-socket,io server without `Server()` and `Close()` method

**Comment by mrfoe7** [comment]
> Another we could keep that function, and make new creators like LaunchServer() which calls Serve() before returning.

> I also hope to keep Close() to have a graceful way to quit a server. If someone wants a server running forever, they could ignore calling this function.

It is good decision by my opinion.

**Comment by googollee** [comment]
Currently `engine.io` wraps a connection as a sock and that's why socket.io needs a `Serve()` to start a goroutine to do the "listen" thing.

As it requires changing the design of engine.io, I hope to remove `Serve()` and `Close()` in the next version. Also, I don't think breaking API in this version is good for users.

**Comment by mrfoe7** [comment]
Why not?

**Comment by mrfoe7** [comment]
I suggest add debug mode into socket.io and egnine.io level. What are you thins about this idea?

**Comment by mrfoe7** [comment]
I suggest update new major version in socketio with changes cleaner public API. i think it changes is worthy new major version. I think, current API does not implement full functionality original API by js version socketio

**Comment by mrfoe7** [comment]
Hey, @ralfbawg! 
If you havta some ideas by public API or some deep things realisation in new second major version, please, tell to us.

**Comment by Cinux-Chosan** [comment]
Does this mean the corresponding server version is only 1.x ?  [here](https://socket.io/docs/v4/client-installation/#Version-compatibility)

**Comment by Mistic92** [comment]
Current version of socket.io is 4.4.1. Does this library works only with 1.x which is 6 years old?

**Comment by erkie** [comment]
@Mistic92 yes, this project needs help

**Comment by sailingwithsandeep** [comment]
@erkie How can i contribute? I would love to contribute

**Comment by erkie** [comment]
There is a telegram channel, and there are a bunch of issues here in github. Just pick one and get going!
