### ISSUE TITLE
Refactoring current code

### ISSUE THREAD

**Issue by mrfoe7** [googollee/go-socket.io#452]
This issue for discussion about refactoring.

**Comment by mrfoe7** [comment]
That this [function]() to do? I don't understand her logic ((

**Comment by googollee** [comment]
Could you list something you want to do here?

**Comment by mrfoe7** [comment]
I'll send my refactoring version by engineio this evening.
Major changes:
- remove high cohesion session and session manager
- separate subject domain
- remove anchor code

**Comment by mrfoe7** [comment]
@googollee look up this. Sorry, i can't separate this big MR by litter path https://github.com/googollee/go-socket.io/pull/455

**Comment by mrfoe7** [comment]
i think it is doesi think it is done
