### ISSUE TITLE
Fix all lint errors

### ISSUE THREAD

**Issue by googollee** [googollee/go-socket.io#454]
**Describe the bug**
golangci-lint failed with a lot of errors, see https://github.com/googollee/go-socket.io/runs/2513044269?check_suite_focus=true.

**To Reproduce**
Remove `skip-files` in `.golangci.yml` and run `make lint`.

**Expected behavior**
No `skip-files` in `.golangci.yml` and `make lint` succeed with no errors.

**Environment (please complete the following information):**
 - Go version: 1.16
 - Server version: 1.4
 - Client version: 1.4

**Comment by mrfoe7** [comment]
I think it resolved
