### ISSUE TITLE
conn session,only have Add(), not have Remove()

### ISSUE THREAD

**Issue by iGoogle-ink** [googollee/go-socket.io#480]
from v1.5.x later, newSesson() can Add(), but there is no place to remove
This will cause the number of sessions to increase indefinitely

**Comment by piksonGit** [comment]
确实是有这个问题。找了半天发现Remove不能自己调用。希望能尽快解决这个问题，这个问题解决了内存泄露的问题可能也会解决。

**Comment by piksonGit** [comment]
在1.4.5版本调用Close()的时候会调用Remove()函数。

**Comment by eric-zhangqi** [comment]
yes, same problem, this project so bad

**Comment by iGoogle-ink** [comment]
> yes, same problem, this project so bad

用老版本吧，虽然多少也有点问题

**Comment by eric-zhangqi** [comment]
哪个版本问题少一些，我们现在测试的版本内存都有点泄漏，哎

**Comment by piksonGit** [comment]
反正我测试着新老版本都不行，让我一度怀疑是不是go不行。。

**Comment by chanbigbig** [comment]
我们更新到V1.6.0 版本，压测后发现，内存不断增长，不会释放。
然而，我们讲版本降低到V1.4.5，压测后发现内存会释放，希望新版本可以解决。

**Comment by iGoogle-ink** [comment]
> 我们更新到V1.6.0 版本，压测后发现，内存不断增长，一直不会释放。
> 然而，我们将版本降低到V1.4.5，压测后发现内存会释放，希望新版本可以解决。

看样子 1.4.5 不错啊，我也试试

**Comment by piksonGit** [comment]
> > 我们更新到V1.6.0 版本，压测后发现，内存不断增长，一直不会释放。
> > 然而，我们将版本降低到V1.4.5，压测后发现内存会释放，希望新版本可以解决。
> 
> 看样子 1.4.5 不错啊，我也试试

1.4.5怎么样，还泄露不

**Comment by iGoogle-ink** [comment]
> > > 我们更新到V1.6.0 版本，压测后发现，内存不断增长，一直不会释放。
> > > 然而，我们将版本降低到V1.4.5，压测后发现内存会释放，希望新版本可以解决。
> > 
> > 
> > 看样子 1.4.5 不错啊，我也试试
> 
> 1.4.5怎么样，还泄露不

我只在测试环境上了，线上环境还没搞

**Comment by zstttttt** [comment]
server.Count()一直整加，没有减少

**Comment by zstttttt** [comment]
我怀疑有内存泄漏，无论再哪个版本，我们现在线上在使用，10w+的连接，给多少机器都没办法满足

**Comment by iGoogle-ink** [comment]
> 

对的，很严重

**Comment by piksonGit** [comment]
> 我怀疑有内存泄漏，无论再哪个版本，我们现在线上在使用，10w+的连接，给多少机器都没办法满足

我是13万+的连接，之前是一直有内存泄露，不过测试了最近的1.6.2，问题还是没有解决，虽然开发者说解决了这个问题。

希望你们也测试下。

**Comment by sshaplygin** [comment]
@piksonGit Could share you tests case?

**Comment by piksonGit** [comment]
same with before. I will test again

**Comment by sshaplygin** [comment]
Hey, @piksonGit and @iGoogle-ink Do you have any updates?

**Comment by iGoogle-ink** [comment]
> Hey, @piksonGit and @iGoogle-ink Do you have any updates?

no，never updated version

**Comment by daveteu** [comment]
So you guys uses this project, and write your own client implementation? I come from JS and JS version of socketIO is already v4. Is it compatible?
