### ISSUE TITLE
Does socket.io support the usage of the "socket.io.min.js" on the front end?

### ISSUE THREAD

**Issue by darienmiller88** [googollee/go-socket.io#487]
When implementing  the basic example to get the socket server up, I noticed that messages only come into the server from the front end when using the socket.io.js library, not the up to date minified one which is the one recommended for development. As anyone else run into this issue? 

This one allows me to both connect to the server AND send messages.
 ` <script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/2.1.1/socket.io.js"></script>`

This one allows me connect to the server, but messages are not received by it.
`<script src=" https://cdnjs.cloudflare.com/ajax/libs/socket.io/3.1.3/socket.io.min.js"></script>`

Here's the Javascript just in case.
```
const socket = io.connect("http://localhost:7080", {transports: ['websocket']})
const form = document.querySelector("form")
const input = document.getElementById("chat")

form.addEventListener("submit", e => {
    e.preventDefault()
    const message = input.value

    console.log(message)
    socket.emit("message", message)
    form.reset()
})
```

And the golang code as well:
```
socketServer, err := socketio.NewServer(nil)
router := chi.NewRouter()


fs := http.FileServer(http.Dir("./static"))

if err != nil {
log.Fatal(err)
}

router.Use(middleware.RealIP, middleware.Recoverer)
router.Handle("/static/*", http.StripPrefix("/static", fs))
router.Handle("/socket.io/", socketServer)


socketServer.OnConnect("/", func(c socketio.Conn) error {
        c.Join("chat")
        fmt.Println(c.ID(), "joined the chat")
        return nil
})

socketServer.OnEvent("/", "message", func(c socketio.Conn, message string)  {
      fmt.Println("message from client", c.ID(), ":", message)
   
      if socketServer.BroadcastToRoom(c.Namespace(), "chat", "fromserver", message){
	      fmt.Println("message sent!")
      }
})

go socketServer.Serve()
defer socketServer.Close()

http.ListenAndServe(":7070",  router)
```

Is there a part of the library I'm not using?

**Comment by googollee** [comment]
Yes, it supports. But we don't support v2 and v3 yet.
