### ISSUE TITLE
can support redis auth?

### ISSUE THREAD

**Issue by zengbin3013** [googollee/go-socket.io#489]
I wan't to use redis broadcast,but the redis set password.
can support redis auth?

**Comment by Linzecong** [comment]
I also need it. Otherwise, i have to modify the adpter in https://github.com/googollee/go-socket.io/blob/484c2ea0a731b3cf1953a5e9118ec6939ca83da6/server.go#L29 and add password parameters to it

**Comment by mrfoe7** [comment]
Hey, @zengbin3013 

By current version does not support. I will add this option

**Comment by fchattigo** [comment]
HI! I need redis auth  too. I wait for that release.

Thanks!

**Comment by liuzesen** [comment]
+1，please

**Comment by YeRuyi** [comment]
#528
