### ISSUE TITLE
Difference in broadcast and emit

### ISSUE THREAD

**Issue by nrandell** [googollee/go-socket.io#49]
I've found a strange problem with a difference between emit and broadcast. My basic code was sending an array via emit on connection and to all connected clients periodically via broadcast. However I was finding that the client worked correctly on from the emit, but didn't work from the broadcast.

Debugging on the server I could see that the array was sent correctly from the emit, but was sent as an array of arrays on the broadcast. 

As an example. I was sending the an array of structs
`type eg struct {
  ts uint64
  text string
}`

`data := []eg{eg{ts: 1, text: "a"}, eg{ts: 2, text: "b"}}`

when I do `socket.Emit("update", data)` I see the following go over the network
`["update",[{"ts":1,"text":"a"},{"ts":2,"text":"b"}]]`

However when I do `socket.Broadcast("room","update",data)` I see something different
`["update",[[{"ts":1,"text":"a"},{"ts":2,"text":"b"}]]]`

The difference being that there is now an array of arrays of eg.

I tracked this down to sometimes passing arguments as arrays and sometimes passing them as variable arguments. 
The Send method in BroadcastAdaptor currently takes declares `args` as `[]interface{}`. Changing this and all implementations to `...interface{}` and whenever Send is called, pass arguments in as `args...` 

I've got this working locally and will submit a pull request shortly.

**Comment by googollee** [comment]
Will you test again?

**Comment by nrandell** [comment]
Ran a quick test, it looks ok.

Thanks for merging and also creating the project. Very useful!

Nick
