### ISSUE TITLE
Do you know any v3 or higher server?

### ISSUE THREAD

**Issue by ErsinDemirbas** [googollee/go-socket.io#497]
Hello sir, I am an jr.Android Developer and created a socket.io client side with java. So I think you know there is v1 or v2 in client side for java. My problem is that my company use v3 in server side so I have to use v2 client (highest version in java) but I cant connect to their server. So I need to a v3 or higher server side url for test my client side for check the problem is in my side or in server side. Do you know any v3 or higher server?

Note: When I switch to v1 in client I can easly connect to other v2 servers.

**Comment by googollee** [comment]
Sorry. I'm not familiar with Java.
