### ISSUE TITLE
OnConnect called twice.

### ISSUE THREAD

**Issue by wahello** [googollee/go-socket.io#498]

**Comment by wahello** [comment]
I'v checked, ` "socket.io-client": "^2.4.x",` works fine.  ` "socket.io-client": "^4.x",` and ` "socket.io-client": "^3.x",`  are not .

**Comment by googollee** [comment]
It only supports v2 now, but not v4.

**Comment by wahello** [comment]
Thanks. Add it to readme, please. It's helpful.
