### ISSUE TITLE
Activated Redis-adapter RoomLen return always -1

### ISSUE THREAD

**Issue by fasibio** [googollee/go-socket.io#507]
**Describe the bug**
If Redisadapter is activated. And you check the Len of Room it returns always -1

**To Reproduce**
Take the redis exmaple and add RoomLen at one of the methods

**Expected behavior**
The count of connections over all Replications

**Environment (please complete the following information):**
 - Go version: go1.16
 - Server version go-socket.io v1.6.0

**Comment by fasibio** [comment]
I debug the code and find out its a casting Problem here: https://github.com/googollee/go-socket.io/blob/master/redis_broadcast.go#L339

the result is from type int64 not int

**Comment by mrfoe7** [comment]
Good job!
