### ISSUE TITLE
Panic when client side emits null data.

### ISSUE THREAD

**Issue by mountkin** [googollee/go-socket.io#51]
```javascript
var socket = io.connect();
socket.on('connect', function() {
  socket.emit('something', null);
});
```
The server crashed at https://github.com/googollee/go-socket.io/blob/master/caller.go#L66 with "panic: reflect: call of reflect.Value.Elem on zero Value".
I think the validity of the reflect value ```v``` should be checked before calling ```v.Elem()```.

**Comment by googollee** [comment]
Will you test again?

**Comment by mountkin** [comment]
Thanks, @googollee 
The problem is fixed.
