### ISSUE TITLE
[bug] sessionManager.Remove(sid) never called

### ISSUE THREAD

**Issue by morapelker** [googollee/go-socket.io#510]
The internal Remove(sid) function seems to never be called which causes the number of connections to keep rising

This is easily testable by connecting/disconnecting to the server  and querying the server.Count() method to see the number keep rising

**Comment by sshaplygin** [comment]
@suxianbaozi or @morapelker do you make check this [fix](https://github.com/googollee/go-socket.io/pull/517) in your environments?

**Comment by nkcc** [comment]
Is this problem fixed now? I noticed that there is a PR to sovle this problem.

**Comment by sshaplygin** [comment]
resolved
