### ISSUE TITLE
disconnect event sometimes not called 

### ISSUE THREAD

**Issue by suxianbaozi** [googollee/go-socket.io#514]
**Describe the bug**

sometimes,a client has already dead,but disconnect event was not been called

**Comment by sshaplygin** [comment]
@suxianbaozi Hey! i need more information. What is you client client? are you setted `onDisconnect(...)` handler?
Good description is your code in this problem

**Comment by aslinaslin** [comment]
> @suxianbaozi Hey! i need more information. What is you client client? are you setted `onDisconnect(...)` handler? Good description is your code in this problem

Me too, I setted onDisconnect（）,but I called it 
ws // Count number of connections.
func (s *Server) Count() int {
	return s.engine.Count()
}
the count and goroutine have not reduction
