### ISSUE TITLE
server how to close socket.io connection?

### ISSUE THREAD

**Issue by plum330** [googollee/go-socket.io#518]
directly call Close()? When I directly call Close(), client will retry again. If I want to set code when server close socket.io connection, what should I do? 
THX!

**Comment by sshaplygin** [comment]
Socket.io connection have method [Close()](https://github.com/googollee/go-socket.io/blob/master/connection.go#L65) for your case. Connection's instance available into *handler* method 

> client will retry again. 

 I am not sure for this behaviour.
 
 >what should I do?
 
 Hm.... Good question

**Comment by zhuzhengyang** [comment]
`Close()` only stop accepting new connections, is there a way to close active connections ?
My program is stuck in graceful http shutdown, waiting `srv.closeIdleConns()`
https://pkg.go.dev/net/http@go1.17.3#Server.Shutdown

**Comment by poplark** [comment]
How is it going now?
I have the similar issue for authentication, when I directly call `Close()` if authentication failed, the client will handle `disconnect` signal, so it will reconnect.
Or, is there any way to use middleware just like the javascript library.

![image](https://user-images.githubusercontent.com/9588298/236979609-566df1d9-f42b-45ab-b99d-eb7d5b85a7dc.png)

THX
