### ISSUE TITLE
Cluster broadcast messages through redis

### ISSUE THREAD

**Issue by flutePeak** [googollee/go-socket.io#519]
Hello, first of all thank you very much to the contributors of this project, this library greatly reduces our workload.
Now we have a little problem. We hope to be able to build a socket cluster, but the message cannot be received through the existing redis adapter. Is the function not yet finished? If so, I don’t know if there is an update plan. If the development is over, is there any way to use it.
thank you very much

**Comment by Hanggi** [comment]
Is there any updates?

**Comment by zzsme** [comment]
Can someone support this function, thank you
