### ISSUE TITLE
Events emitted from server not heard by client

### ISSUE THREAD

**Issue by mjw56** [googollee/go-socket.io#52]
Hi, first thank you for this project.

I am working on simple demo to stream some data to the client. I am running into an issue where I am not hearing events which are emitted from server on the client. Here is what my use case looks like:

Server:

``` javascript
server.On("connection", func(so socketio.Socket) {
   log.Println("user connected")

   go tweets()

   so.On("get-tweets-data", func() {
       log.Println("I heard event from client!")
       so.Emit("tweets-data")
   })
   so.On("disconnection", func() {
       log.Println("user disconnected")
   })
})
```

Client:

``` javascript
socket.on('connect', function(data) {

  socket.emit('get-tweets-data');

  socket.on('tweets-data', function(data) {
    console.log('received data from the server');
  });

});
```

I heard the initial "get-tweets-data" call from the client, but after that when I try to callback to the client from server something gets lost in translation.

If I move the Emit outside of the On event, it works fine.

``` javascript
server.On("connection", func(so socketio.Socket) {
   log.Println("user connected")

   go tweets()

   so.On("get-tweets-data", func() {
       log.Println("I heard event from client!")
   })
   so.On("disconnection", func() {
       log.Println("user disconnected")
   })
   so.Emit("tweets-data")
})
```

**Comment by googollee** [comment]
As I merged the go-engine.io, please check this issue again. Thanks.

**Comment by mattmassicotte** [comment]
I know its been a while since this issue has been touched, but as of master on April 15th, 2015, I'm experiencing a similar issue. It appears that Emits that occur in the On("connection",..) function work, but all other emits return the "upgrading" error.

**Comment by alecthomas** [comment]
I'm having the same issue, though not reliably. Sometimes it errors with "upgrading", sometimes it doesn't.

**Comment by syhlion** [comment]
I'm having the same issue +1

**Comment by moul** [comment]
Same problem here 👍

**Comment by MarekBielecki** [comment]
+1

**Comment by pgamaster** [comment]
+1 upgrading error under 2000+ clients

**Comment by erkie** [comment]
Closing this issue because it is old. There are a couple of newer issues with the same problem so please refer to those. Thanks!
