### ISSUE TITLE
go-socket.io client 

### ISSUE THREAD

**Issue by phwolf** [googollee/go-socket.io#526]
Hi, 
I would like to use go-socket.io to create a socket.io client in go.
In the examples I can only see go-socket.io servers and clients in javascript.
Is it possible to write a client in go using go-socket.io?
Thanks a lot, best regards

**Comment by finaldzn** [comment]
Hey have you found how to use the library as a client or a go socket client that works with the library ?

**Comment by phwolf** [comment]
You could try using go-engine.io (which is used by go-socket.io) https://github.com/googollee/go-engine.io/blob/master/demo/client/client.go for the client. However this does not support the latest socket.io version v4!

**Comment by buuhvprojects** [comment]
@phwolf can we close this issue? Currently, it is already possible to make this communication in the most recent version of socket.io javascript with socket.io from golang. See chat example
