### ISSUE TITLE
How to emit to specific user or connection

### ISSUE THREAD

**Issue by ElegantSoft** [googollee/go-socket.io#531]
I want to emit messages to specific users by their connection id.
In NodeJs socket.io I used to write
```js
socket.to("clientId").emit("data")
```
how to achieve that in this package

**Comment by AndrusGerman** [comment]
There are different ways to do it, a simple one is to create a room for that user
```go
	server.OnConnect("/", func(s socketio.Conn) error {
		userID := s.ID()
                // Create room for private messages
		s.Join(userID)
		return nil
	})
```

```go
        // Send private message
	server.BroadcastToRoom("", userID, "event:name", "hello user <3")
```

userID could be the id of the user in the database, and this way if you are connected on multiple devices you will receive the same message
