### ISSUE TITLE
memory leak happens

### ISSUE THREAD

**Issue by ElegantSoft** [googollee/go-socket.io#533]
There are memory leak even if no one connected 

```
Showing top 10 nodes out of 116
      flat  flat%   sum%        cum   cum%
13364.07kB 34.21% 34.21% 13364.07kB 34.21%  bufio.NewReaderSize
 8738.04kB 22.37% 56.57%  8738.04kB 22.37%  bufio.NewWriterSize
 5125.75kB 13.12% 69.69%  5125.75kB 13.12%  net/textproto.(*Reader).ReadMIMEHeader
 1536.33kB  3.93% 73.63%  1536.33kB  3.93%  net/textproto.(*Reader).ReadLine
 1536.19kB  3.93% 77.56%  1536.19kB  3.93%  github.com/googollee/go-socket.io/engineio/session.New
```

 - Go version: 1.14.6
 - Server version latest
 - Client version latest

[profile007.pdf](https://github.com/googollee/go-socket.io/files/8624666/profile007.pdf)

**Comment by ElegantSoft** [comment]
![profile002](https://user-images.githubusercontent.com/47436634/166743457-c61891a6-146a-4918-80c8-667c6ae4bb6d.png)

**Comment by smallfish-root** [comment]
Yes,I also encountered this problem for long time.How to solve it?

**Comment by piksonGit** [comment]
same problem

**Comment by sshaplygin** [comment]
duplicated problem. same problem https://github.com/googollee/go-socket.io/issues/442
