### ISSUE TITLE
service freeze on certain connection

### ISSUE THREAD

**Issue by kingter-sutjiadi** [googollee/go-socket.io#535]
hi guys i deploy this on dockerswarm (swarmpit) single replica, 

the issue occurs if the service is connected by multiple connection the service is suddenly freeze

but when i check the ram and the cpu usage is still low, anyone encounter the same issue ?

![image](https://user-images.githubusercontent.com/52060866/167544071-628573c5-0756-4542-bfb6-c2ceaa070290.png)

**Comment by w967395388** [comment]
I have the same problem,how to solve this bug?
