### ISSUE TITLE
v1.6.2 : CPU use High

### ISSUE THREAD

**Issue by iGoogle-ink** [googollee/go-socket.io#538]
pprof :
<img width="1919" alt="image" src="https://user-images.githubusercontent.com/17245594/181417343-38934a23-9dda-4e5f-be0c-98a63d4f06cf.png">

<img width="814" alt="image" src="https://user-images.githubusercontent.com/17245594/181417492-d95adc3c-178f-4667-9732-e64865071e64.png">

<img width="805" alt="image" src="https://user-images.githubusercontent.com/17245594/181417569-2c76ddc1-e51b-4d93-a895-042d32a07334.png">

**Comment by iGoogle-ink** [comment]
I have a try on release env，this is my ecs CPU monitor info:
<img width="944" alt="image" src="https://user-images.githubusercontent.com/17245594/181419972-9e7934c1-1f2b-4a9b-be08-7dce5dc25567.png">

TCP count:
<img width="927" alt="image" src="https://user-images.githubusercontent.com/17245594/181420208-b8af1c1d-58a2-48b0-8af5-a70e2b90083a.png">

**Comment by RandalTeng** [comment]
Hey, I have the same problem with my production application, it seem always lock-unlock in read and write with session.
I don't know how to improve it, is there any advice about it?
