### ISSUE TITLE
Is server send ping request automatically?

### ISSUE THREAD

**Issue by forfcw** [googollee/go-socket.io#540]
server:    gosocketio version v1.6.2

websocket info:
client1:   v-2 "WebSocket++/0.8.2" /socket.io/?EIO=4&transport=websocket
client2:   v-2 "WebSocket++/0.5.1" /socket.io/?EIO=4&transport=websocket

the client1(latest socketio-cpp)  will reconnect every minute  because of the 60s ping-pong timeout, and do not get any ping request from server.
the client2(socketio-cpp serveral years ago) will running correctly.

is gosocketio server in this version send ping request automatically or just wait for ping request?
I have recompiled the c++ project socketio-cpp and added logger in pong request, but never called.
It seems that the server needs to actively initiate ping requests now accoding to [here](https://socket.io/blog/engine-io-4-release/).

looking forward to your reply, tks!

**Comment by alpcanm** [comment]
Hey! You solved this issue?

**Comment by forfcw** [comment]
> 
not yet, but it will reconnect at least

**Comment by forfcw** [comment]
> 

not yet, but it will reconnect at least
