### ISSUE TITLE
go-socket.io client ? with latest version of socket.io(v.4)

### ISSUE THREAD

**Issue by codesiddhant** [googollee/go-socket.io#544]
is there is any way to use  the is library to connect as socket-io client for my nodejs based socketio server which is using latest version(v4.5) ?

**Comment by MathiasDeWeerdt** [comment]
This would be super useful!

**Comment by ferjoaguilar** [comment]
Yes, I am the same question. I need a any way connect with socket-io client v4

**Comment by h-mavrodiev** [comment]
+1, as @MathiasDeWeerdt said, it would be super useful.

**Comment by backendman** [comment]
+1

**Comment by shuan86** [comment]
+1

**Comment by shaniqwa-drm** [comment]
+1 !

**Comment by xuanlongvts** [comment]
+1

**Comment by vandyahmadldm** [comment]
+1

**Comment by yubo9807** [comment]
+1, I tried several versions, but nothing worked.
