### ISSUE TITLE
How to use go-engine.io or go-socket.io as the client?

### ISSUE THREAD

**Issue by hlbbt** [googollee/go-socket.io#558]
I checked the previous issue and found that go-engine.io was used as the client, but an error was reported

the error is `unsupported protocol scheme "wss"`

The version of socket. io used by the server is 1.7.4, and the nodejs socket client can be used to connect normally, but it cannot be connected using golang

![image](https://user-images.githubusercontent.com/113571052/206151450-b47d1108-7fd2-4622-a432-3d85f6f6d725.png)

**Comment by hwwwi** [comment]
Try to remove `polling.Default` from the Transport.

**Comment by sshaplygin** [comment]
@hlbbt Hey! is it actual question?

**Comment by hlbbt** [comment]
> @hlbbt嘿！这是实际问题吗？

yes, Problems encountered in our actual project
