### ISSUE TITLE
socket.IO version

### ISSUE THREAD

**Issue by dev-hana** [googollee/go-socket.io#563]
Hello,
Node.js implemented a web socket using socket.IO version 2.4.1.
I want to change this project to go language, so I want to use this module, how do I fit the socket.IO version?

**Comment by Archie1978** [comment]
I looked this morning, I used github.com/googollee/go-socket.io@v1.5.1.

**Comment by sshaplygin** [comment]
@Archie1978 Hey! why are you don't upgrade to latest version?

**Comment by dev-hana** [comment]
> @Archie1978여기요! 최신 버전으로 업그레이드하지 않는 이유는 무엇입니까?

I lowered the version because of Unity WebGL.

**Comment by dev-hana** [comment]
> 오늘 아침에 보니 github.com/googollee/go-socket.io@v1.5.1을 사용했습니다.

Thank you for your reply.
The recently go-socket.io version used socketIO v2
