### ISSUE TITLE
How to set CORS?

### ISSUE THREAD

**Issue by jvstatinydev** [googollee/go-socket.io#578]
Hello.
I could archive CORS rule in python like this.

```
    app = Flask(__name__)
    origins = ["https://example.com", "https://www.example.com"]
    cors = CORS(app, resources={r"/*": {"origins": origins}})
    app.config['SECRET_KEY'] = 'secret!'
    socketio = SocketIO(app, async_mode="threading", cors_allowed_origins=origins)
    socketio.run(app, debug=False, allow_unsafe_werkzeug=True)
```

Is there an equivalent code in go-socket.io?
This may sound dumb as I am new to go lang and go-socket.io.
Thank you!

**Comment by sshaplygin** [comment]
@jvstatinydev Hey! is it [code](https://github.com/googollee/go-socket.io/blob/master/_examples/default-http/main.go#L15) doesn't help to you?

**Comment by jvstatinydev** [comment]
> 

Hello! Thank you for the example code. Could you let me know how to set CORS with this example? I want to allow one domain like I did in the python example that I wrote. I guess I should do something in "allowOriginFunc"?
