### ISSUE TITLE
Not able to make namespaces work

### ISSUE THREAD

**Issue by sanketsaurav** [googollee/go-socket.io#59]
I'm trying to create a namespace, but I'm not able to connect to the namespace from the client side.

Server:

```
func registerHandlers(server *socketio.Server) {
    server.Of("room1").On("connect", connectionHandler)
}

func connectionHandler(so socketio.Socket) {
    log.Println("on connection")
    so.Join("chat")
    so.On("chat message", func(msg string) {
        so.BroadcastTo("chat", "chat message", msg)
    })
}
```

Client:

```
var socket = io.connect("http://localhost:3000/room1");
socket.on('chat message', function(msg){
        $('#messages').append($('<li>').text(msg));
      });
```

Am I missing something?

**Comment by Dal-Papa** [comment]
Hi Sanket,

Did you have any update on that ? I run into the same problem here.

Cheers.

**Comment by rykov** [comment]
+1

**Comment by navneetk** [comment]
I am also facing the same issue.
The socket.io client socket with a namespace does not get connected and has undefined socket.id property.
Whereas on the server side any message send from the default socket (without namespace) get echoed with namespace attached.

Frame sent => 42["message","hello"]
Frame received => 42/myspace,["message","hello"]

**Comment by googollee** [comment]
I will try to figure out this issue.

**Comment by Nickstr** [comment]
Having the same issue here, any updates on this?

**Comment by fuel-shea** [comment]
@navneetk my fix may not solve your problem. It seems unrelated to the code I changed. I'm only able to confirm that without my fix, clients can't connect fully and with it, they are connected.

**Comment by collinglass** [comment]
Would really like to use this in production! Namespaces is a must. I made this little test app to compare node socket.io and go socket.io with namespaces. https://github.com/collinglass/socketio

**Comment by eliezedeck** [comment]
Is there any update on this? It's really not viable to build big applications with this library without namespace support.

**Comment by GoodWong** [comment]
Hi Sanket,

Did you have any update on that ? I run into the same problem here.

Cheers.

**Comment by erkie** [comment]
Closing this issue because it is old. There are a couple of newer issues with the same problem so please refer to those. Thanks!
