### ISSUE TITLE
Are you still working on this?

### ISSUE THREAD

**Issue by grahamjenson** [googollee/go-socket.io#602]
I have some PRs:
1. Migrating logging to slog and adding a bit more log lines
2. Writing a client for the library

Should I submit them or just keep my fork going?

**Comment by erkie** [comment]
PR's are always welcome.

**Comment by grahamjenson** [comment]
@erkie 

https://github.com/googollee/go-socket.io/pull/607
https://github.com/googollee/go-socket.io/pull/608
https://github.com/googollee/go-socket.io/pull/609
https://github.com/googollee/go-socket.io/pull/610
https://github.com/googollee/go-socket.io/pull/611

This is my current progress. 

My goal is to create a working stable version 3 socket.io client and server that can imitate and interact with the Javascript Socket.io server. I have the time to do it. Eventually, I will need socket.io version 4 (hopefully easier to implement) but that might not be for a while. 

Any help merging these would be appreciated so that my fork doesn't ever stray to far away from the source :)
