### ISSUE TITLE
fatal error: sync: unlock of unlocked mutex

### ISSUE THREAD

**Issue by xylfuc** [googollee/go-socket.io#604]
fatal error: sync: unlock of unlocked mutex

goroutine 222 [running]:
runtime.throw({0x2796c2e?, 0x4b4b35?})
        /usr/local/go/src/runtime/panic.go:992 +0x71 fp=0xc001977948 sp=0xc001977918 pc=0x45c271
sync.throw({0x2796c2e?, 0xffffffff?})

        /usr/local/go/src/runtime/panic.go:978 +0x1e fp=0xc001977968 sp=0xc001977948 pc=0x48bf9e
sync.(*Mutex).unlockSlow(0xc0011d27e8, 0x5f782c73)

        /usr/local/go/src/sync/mutex.go:220 +0x49 fp=0xc001977990 sp=0xc001977968 pc=0x4b4ba9
sync.(*Mutex).Unlock(0xc0011d27e8)

        /usr/local/go/src/sync/mutex.go:214 +0x55 fp=0xc0019779b0 sp=0xc001977990 pc=0x4b4b35
github.com/googollee/go-socket.io/engineio/transport/websocket.wrapper.NextReader.func1()
        /root/go/pkg/mod/github.com/googollee/go-socket.io@v1.7.0/engineio/transport/websocket/wrapper.go:33 +0x3a fp=0xc0019779d0 sp=
0xc0019779b0 pc=0xcf339a
runtime.deferreturn()
        /usr/local/go/src/runtime/panic.go:436 +0x33 fp=0xc001977a10 sp=0xc0019779d0 pc=0x45af33
github.com/googollee/go-socket.io/engineio/transport/websocket.wrapper.NextReader({0xc0010e3e40?, 0xc0011d27d8?, 0xc0011d27e8?})
        /root/go/pkg/mod/github.com/googollee/go-socket.io@v1.7.0/engineio/transport/websocket/wrapper.go:43 +0x2e5 fp=0xc001977b40 sp
=0xc001977a10 pc=0xcf3245
github.com/googollee/go-socket.io/engineio/transport/websocket.(*wrapper).NextReader(0xc00118ecc0)
        <autogenerated>:1 +0x65 fp=0xc001977b90 sp=0xc001977b40 pc=0xcf47e5
github.com/googollee/go-socket.io/engineio/packet.(*Decoder).NextReader(0xc0011a1800)
        /root/go/pkg/mod/github.com/googollee/go-socket.io@v1.7.0/engineio/packet/decoder.go:25 +0x4e fp=0xc001977c10 sp=0xc001977b90 
pc=0xcc54ee
github.com/googollee/go-socket.io/engineio/transport/websocket.(*conn).NextReader(0xc0007565a0)
        <autogenerated>:1 +0x57 fp=0xc001977c58 sp=0xc001977c10 pc=0xcf6cd7
github.com/googollee/go-socket.io/engineio/session.(*Session).nextReader(0xc000495680)
        /root/go/pkg/mod/github.com/googollee/go-socket.io@v1.7.0/engineio/session/session.go:204 +0x85 fp=0xc001977cd8 sp=0xc001977c5
8 pc=0xccf5a5
github.com/googollee/go-socket.io/engineio/session.(*Session).NextReader(0x0?)
        /root/go/pkg/mod/github.com/googollee/go-socket.io@v1.7.0/engineio/session/session.go:81 +0x34 fp=0xc001977d60 sp=0xc001977cd8
 pc=0xcce574
github.com/googollee/go-socket.io/parser.(*Decoder).DecodeHeader(0xc0011bc800, 0xc001977f30, 0x0?)
        /root/go/pkg/mod/github.com/googollee/go-socket.io@v1.7.0/parser/decoder.go:66 +0x6f fp=0xc001977e68 sp=0xc001977d60 pc=0xcf96
6f
github.com/googollee/go-socket%2eio.(*Server).serveRead(0xc001146d68, 0xc0006d9da0)
        /root/go/pkg/mod/github.com/googollee/go-socket.io@v1.7.0/server.go:291 +0x166 fp=0xc001977fb0 sp=0xc001977e68 pc=0xd1f306
github.com/googollee/go-socket%2eio.(*Server).serveConn.func3()
        /root/go/pkg/mod/github.com/googollee/go-socket.io@v1.7.0/server.go:230 +0x48 fp=0xc001977fe0 sp=0xc001977fb0 pc=0xd1e728
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc001977fe8 sp=0xc001977fe0 pc=0x491461
created by github.com/googollee/go-socket%2eio.(*Server).serveConn

        /root/go/pkg/mod/github.com/googollee/go-socket.io@v1.7.0/server.go:230 +0x7cf

**Comment by googollee** [comment]
archived.
