### ISSUE TITLE
Why is this neither being updated nor deprecated

### ISSUE THREAD

**Issue by reachdivyasingh** [googollee/go-socket.io#605]
Kindly deprecate this package. Version 1.4 was eons ago. This code is incompatible with anything modern on socket.io and should come with deprecation and unmaintained notice.

Such a notice will save hours of precious developer time.

Kindly consider deprecating it till new maintainers can come forward and take responsibility (like how Gorilla did).

**Comment by erkie** [comment]
Why is this something you'd demand from the maintainers of this project? The project still works, and the documentation is quite clear what versions of Socket it supports.
