### ISSUE TITLE
Cors problem with Golang Server

### ISSUE THREAD

**Issue by HichOoMa** [googollee/go-socket.io#620]
I am using `go-socket.io` in the backend

When I implement socket in the front side it show error `Reason: CORS header ‘Access-Control-Allow-Origin’ missing`

**Comment by TRSeculan** [comment]
any answer on this ?

**Comment by HaithamBH** [comment]
Still not but I moved to work with gorilla websocket is easy to implement also

**Comment by googollee** [comment]
archived.
