### ISSUE TITLE
Additional bytes in HTTP handshake

### ISSUE THREAD

**Issue by steve-nester-uk** [googollee/go-socket.io#623]
**Describe the bug**
I'm trying to test socket.io with GoLang v1.7.0.  The client is making the HTTP request to establish the connection but it's failing.  Upon inspecting the http request in browser tools, I can see additional bytes in response.  After adding Gin middleware to expect the being returned by the server, I can confirm the server is sending these additional bytes.

<img width="641" alt="image" src="https://github.com/googollee/go-socket.io/assets/1540076/b852f01f-32ce-4234-a54e-f14b214dbbcd">

<img width="418" alt="image" src="https://github.com/googollee/go-socket.io/assets/1540076/8f6b8e24-91f0-4b5c-94ac-f203db1f5086">

After a while the server is outputting "meet error: write: timeout", which is presumably because it is waiting for the client to respond.

**To Reproduce**
Server side:
- `go mod init myproject`
- `go get  github.com/googollee/go-socket.io@v1.7.0`

Client side:
React 
`npm install socket.io-client`

**Expected behavior**
There should not be additional bytes in front of the JSON.

**Environment (please complete the following information):**
 - Go version: v1.18.1 (also later tried to update to v1.21.1 but getting the same issue)
 - Server version: go-socket.io v1.7.0
 - Client version: socket.io-client v4.7.2

**Additional context**

**Comment by dirname** [comment]
use `"socket.io-client": "^2.5.0"` instead.

**Comment by googollee** [comment]
archived.
