### ISSUE TITLE
server.Remove undefined

### ISSUE THREAD

**Issue by Mohammad-DH** [googollee/go-socket.io#624]
server.Remove undefined (type *socketio.Server has no field or method Remove)

line 44 of Base example with using std net/http  ==> https://github.com/googollee/go-socket.io/tree/master/_examples
server.Remove(s.ID()) 

**Environment (please complete the following information):**
 - Go version: v1.21.5
 - Server version:  go-socket.io v1.4

(its my first day using Go)

**Comment by maulikpatel-in** [comment]
facing same issue, any solution to this bug?

**Comment by zieen** [comment]
User the New RC version of master version v1.8.0-rc.1

**Comment by muhamad-subkhan** [comment]
our problem is the same, I also just learned about this and experienced something similar. After I searched, it didn't have the "Remove" library on Socket IO. either because it wasn't included or there was another problem.

**Comment by googollee** [comment]
archived.
