### ISSUE TITLE
Pingtimeout and pinginterval does not work

### ISSUE THREAD

**Issue by mvltyldrmm** [googollee/go-socket.io#627]
Hi, I wasn't sure if there is a bug or a place I missed.

`
options := &engineio.Options{
PingTimeout:  30 * time.Second,
PingInterval: 10 * time.Second,
}
server := socketio.NewServer(options)
go func() {
 if err := server.Serve(); err != nil {
      log.Fatalf("socketio listen error: %s\n", err)
 }
defer server.Close()
}()
`

I give a Socket Server and give pingtimeout and pinginterval adjustments with Engine io, so that I aim to automatically detect those who come out of the connection without Disconnect trigger and throw them out of Socket. But even if the connection breaks in any way, the disconnect continues to keep users in Socket, should I add an additional setting or is this a bug?

**Comment by googollee** [comment]
archived.
