### ISSUE TITLE
Support "extraHeaders" in client

### ISSUE THREAD

**Issue by sagan** [googollee/go-socket.io#634]
**Is your feature request related to a problem? Please describe.**
Some socket.io servers require additional header exists in incoming connection, typically for authorization. Socket.io JavaScript client has [extraHeaders](https://socket.io/docs/v3/client-initialization/#extraheaders) option for it. However, there is no way to setup additional header of client using go-socket.io.

**Describe the solution you'd like**
Change the signature of `func (c *Client) Connect()` to `func (c *Client) Connect(extraHeaders http.Header)`

```go
func (c *Client) Connect(extraHeaders http.Header) error {
        // ...omit
	enginioCon, err := dialer.Dial(c.url, extraHeaders)
        // ...omit
}
```

**Describe alternatives you've considered**
Alternatively, change the `engineio.Options` struct, add a new `extraHeaders` field and use it when client do dialing.

**Comment by kalmastenitin** [comment]
Any update over this? or any suggestions?

**Comment by googollee** [comment]
archived.
