### ISSUE TITLE
read tcp 127.0.0.1:8001->127.0.0.1:55169: i/o timeout

### ISSUE THREAD

**Issue by Fiqry919** [googollee/go-socket.io#635]
**Describe the bug**
server error when client connect
meet error: read tcp 127.0.0.1:8001->127.0.0.1:55169: i/o timeout

**Environment (please complete the following information):**
 - Go version: [e.g. v1.22.2]
 - Server version [e.g. go-socket.io v1.7.0]

**Additional context**
using default example code with gin

**Comment by googollee** [comment]
archived.
