### ISSUE TITLE
Very bad source

### ISSUE THREAD

**Issue by expectedpeguin** [googollee/go-socket.io#636]
Unresolved reference 'NewClient'
Unresolved reference 'OnEvent'
Unresolved reference 'Connect'
Unresolved reference 'Emit'
Unresolved reference 'Close'
What do you do man?
package main

import (
	socketio "github.com/googollee/go-socket.io"
	"log"
)

func main() {
	uri := "http://127.0.0.1:8000"

	client, _ := socketio.NewClient(uri, nil)

	// Handle an incoming event
	client.OnEvent("reply", func(s socketio.Conn, msg string) {
		log.Println("Receive Message /reply: ", "reply", msg)
	})

	client.Connect()
	client.Emit("notice", "hello")
	client.Close()
}

Nothing works at client. What are you doing? What's that example for if you didn't even made it! What's that madness why are you wasting our time?!

**Comment by mrtowers** [comment]
you need to switch version from `v1.7.0` to `v1.8.0-rc.1` in your `go.mod` file. worked for me

**Comment by googollee** [comment]
archived.
