### ISSUE TITLE
[Feature] Emit to a Specific Client Only

### ISSUE THREAD

**Issue by kavania2002** [googollee/go-socket.io#638]
**Is your feature request related to a problem? Please describe.**

Currently, we don't have any support for emitting to a specific client only. Like the one given here [Link](https://stackoverflow.com/questions/10110411/node-js-socket-io-how-to-emit-to-a-particular-client?rq=3)

I don't have any solution for this as of now.
I want to know that are we really maintaining this repository. If yes, then I would like to deep dive in the code and look into what things we can do here and also update regarding my issue.

**Comment by msabaeian** [comment]
I never worked with this package but in general, a simple solution for this is to create a room for each user and join them to that room, then you can broadcast to the user's private room which results in emitting to a client only.

**Comment by erkie** [comment]
That's how we do it

**Comment by kavania2002** [comment]
Currently, I'm doing the same thing. But I think that would consume too much memory, will it?

**Comment by erkie** [comment]
How many users are you thinking?

**Comment by kavania2002** [comment]
> How many users are you thinking?

Maybe more than 10k users or something.

**Comment by erkie** [comment]
Then that's nothing to worry about at all. In our app we have 2 rooms per user (to be able to distribute to clients based on capability) and have 30k connected users at any given time. Rooms are basically just maps anyway so it's quite cheap.

**Comment by googollee** [comment]
archived.
