### ISSUE TITLE
How to receive Binary data 

### ISSUE THREAD

**Issue by ususvirkar** [googollee/go-socket.io#639]
Hi

Unable to receive binary data ,continuously going in loop with following _placeholder event message. Any suggestion 

Version: go-socket.io@v1.8.0-rc.1

2024/07/02 22:05:27 ==> binary-packet Event
map[_placeholder:true num:0]
2024/07/02 22:05:27 ==> binary-packet Event
map[_placeholder:true num:0]
2024/07/02 22:05:28 ==> binary-packet Event
map[_placeholder:true num:0]
2024/07/02 22:05:28 ==> binary-packet Event
map[_placeholder:true num:0]
2024/07/02 22:05:28 ==> binary-packet Event
map[_placeholder:true num:0]
2024/07/02 22:05:28 ==> binary-packet Event
map[_placeholder:true num:0]
2024/07/02 22:05:29 ==> binary-packet Event
map[_placeholder:true num:0]
2024/07/02 22:05:29 ==> binary-packet Event
map[_placeholder:true num:0]
2024/07/02 22:05:29 ==> binary-packet Event
map[_placeholder:true num:0]
2024/07/02 22:05:30 ==> binary-packet Event
map[_placeholder:true num:0]

**Comment by googollee** [comment]
archived.
