### ISSUE TITLE
When I frequently push data to the server, it becomes like this.

### ISSUE THREAD

**Issue by maxq783941739** [googollee/go-socket.io#640]
2024/08/12 14:54:38 Connection established.
2024/08/12 14:54:39 Connected to server
2024/08/12 14:54:40 Connected to server
2024/08/12 14:54:40 ERROR store post: err="post: Post \"http://localhost:9099/socket.io/?EIO=3&sid=29490cb2-97a0-4036-a399-72d3aa748e21&t=8MhWQSBwgV1&transport=polling&username=123\": write tcp 127.0.0.1:60671->127.0.0.1:9099: write: broken pipe"
2024/08/12 14:54:40 ERROR clientRead Error in Decoder err="post: Post \"http://localhost:9099/socket.io/?EIO=3&sid=29490cb2-97a0-4036-a399-72d3aa748e21&t=8MhWQSBwgV1&transport=polling&username=123\": write tcp 127.0.0.1:60671->127.0.0.1:9099: write: broken pipe"
2024/08/12 14:54:40 Disconnected from server: client namespace disconnect
2024/08/12 14:54:40 ERROR next writer session text: err="post: Post \"http://localhost:9099/socket.io/?EIO=3&sid=29490cb2-97a0-4036-a399-72d3aa748e21&t=8MhWQSBwgV1&transport=polling&username=123\": write tcp 127.0.0.1:60671->127.0.0.1:9099: write: broken pipe"
2024/08/12 14:54:40 INFO clientWrite Writer loop has stopped
2024/08/12 14:54:40 ERROR clientError err="error in namespace: () with error: (post: Post \"http://localhost:9099/socket.io/?EIO=3&sid=29490cb2-97a0-4036-a399-72d3aa748e21&t=8MhWQSBwgV1&transport=polling&username=123\": write tcp 127.0.0.1:60671->127.0.0.1:9099: write: broken pipe)"
2024/08/12 14:55:39 ERROR serveGet store 1: err="post: Post \"http://localhost:9099/socket.io/?EIO=3&sid=29490cb2-97a0-4036-a399-72d3aa748e21&t=8MhWQSBwgV1&transport=polling&username=123\": write tcp 127.0.0.1:60671->127.0.0.1:9099: write: broken pipe"

`func main() {
	client, err := createClient()
	if err != nil {
		log.Fatalf("Error creating Socket.IO client: %v", err)
	}

	go manageClient(client)

	time.Sleep(5 * time.Second)
	go func() {
		for {
			client.Emit("event04", "Hello, server!")
			///time.Sleep(10 * time.Second) // 每10秒发送一次消息
		}
	}()

	select {}
}`
When I frequently push data to the server, it becomes like this.

why？

**Comment by googollee** [comment]
archived.
