### ISSUE TITLE
websocket error

### ISSUE THREAD

**Issue by denson8090** [googollee/go-socket.io#642]
error info : http: superfluous response.WriteHeader call from github.com/googollee/go-socket.io/engineio.(*Server).ServeHTTP (server.go:99)

chorme  call

const socket = new WebSocket("ws://localhost:3000/socket.io/?EIO=4&transport=websocket");

socket.onopen = () => console.log('WebSocket connection opened');
socket.onmessage = (event) => console.log('Message from server:', event.data);
socket.onerror = (error) => console.error('WebSocket error:', error);
socket.onclose = (event) => console.log('WebSocket connection closed', event);

**Comment by dawnco** [comment]
i use this solve it

 https://github.com/googollee/go-socket.io/blob/master/_examples/default-http/main.go  

`var allowOriginFunc = func(r *http.Request) bool {
	return true
}

server := socketio.NewServer(&engineio.Options{
		Transports: []transport.Transport{
			&polling.Transport{
				CheckOrigin: allowOriginFunc,
			},
			&websocket.Transport{
				CheckOrigin: allowOriginFunc,
			},
		},
	})`

**Comment by googollee** [comment]
archived.
