### ISSUE TITLE
Plan to archive this project.

### ISSUE THREAD

**Issue by googollee** [googollee/go-socket.io#643]
Hello @erkie @sshaplygin,

I plan to archive this project and go-engine.io. I don't have time to maintain these projects and I see a lot of no responsed issues and prs. After archiving, it annoce to people that don't use these projects. Since I didn't use any other similar projects, I won't recommend any one. The user can still use the library after archiving.

If you want to keep the project, let me know and I will put your project in README.

Any objective?

**Comment by sshaplygin** [comment]
Hey, @googollee I agree with you plan

**Comment by erkie** [comment]
We're still actively using it so I could consider starting a fork on our account and trying to keep it "alive" there

**Comment by googollee** [comment]
@erkie I'd like to add a notice in my README mentioning your project and linking back to your repository. Would that be okay with you?

**Comment by erkie** [comment]
Alright! I've made a fork now here: https://github.com/feederco/go-socket.io

**Comment by googollee** [comment]
Thanks. Now archive the repo.
