### ISSUE TITLE
Can not include js from localhost:5000

### ISSUE THREAD

**Issue by ivkean** [googollee/go-socket.io#65]
Hello,
When i start server.go which included your code to start port 5000, console alert that serving port 5000.
Then I try to include socket.io.js file on client:
<script src="http://localhost:5000/socket.io.js"></script>
but console log in browser alert that 404 file not found.
Can you show me how to connect with server ?

**Comment by googollee** [comment]
You can check the [example code](https://github.com/googollee/go-socket.io/tree/master/example) .
