### ISSUE TITLE
Breaks after unknown emit.

### ISSUE THREAD

**Issue by bweston92** [googollee/go-socket.io#67]
The moment I emit something that isn't caught by the `on` listeners. It no longer responds to any other emit.

If I use the example code and emit

```
emit('chat message', "my text") // fine
emit('chat message', "my text") // fine
emit('chat msg', "my text") // fails as no listener
emit('chat message', "my text") // now fails
```

Also I am unable to transfer JSON objects, this also breaks everything?

**Comment by jdeschenes** [comment]
To further elaborate. The server tries to ping the connection twice and typically after roughly 45 seconds it will close the connection and create a new one. I am still trying to understand what is happening behind the scene.

A quick fix that I have found worked for me in file handler.go:
```go
c, ok := h.events[message]
if !ok {
    h.socket.conn.Close()    // ADD THIS LINE
    return nil, nil
}
```
I essentially close the connection and let the server create a new one. I find this is rather inelegant. I would like to find a better approach, perhaps @googollee has a better idea?

**Comment by googollee** [comment]
Could you show the more detail code about this?

**Comment by jdeschenes** [comment]
Hi, I have put in a pull request which solve the issue.

**Comment by nfirvine** [comment]
Is this issue fixed then? If so, please close it.
