### ISSUE TITLE
Not thread safe

### ISSUE THREAD

**Issue by polomsky** [googollee/go-socket.io#68]
The code is vulnerable to race conditions. Try run with `go run -race`

One example for all:
broadcast type in adapter.go uses unsynchronized access to the map (Join, Leave, Send)

**Comment by Incisive** [comment]
One way I got it working was to wrap a mutex around calls to BroadcastTo.  Another option would be to set up a buffered channel that a worker reads from and emits broadcasts from structs/data in the channel that way it doesn't block senders trying to send broadcasts.

**Comment by googollee** [comment]
I will try to figure out how to do it right.

**Comment by nkovacs** [comment]
I fixed the race condition in broadcast (Join/Send/Leave), but I couldn't find any others running the example app.

**Comment by erkie** [comment]
Closing this issue because it is very broad. If you have any specific races please open separate tickets for them so it's easier to take a look at.
