### ISSUE TITLE
Is there a way to close a socket on the server side?

### ISSUE THREAD

**Issue by bigblind** [googollee/go-socket.io#69]
If not, I'd really lick a Socket.Close() function. I'm implementing authentication for socket.io, and if the client doesn't send an auth event within a certain time, I'd like to close the connection.

**Comment by googollee** [comment]
Could you submit a pr?

**Comment by cention-adly** [comment]
Digging through the code one time to figure out a bug I discovered that if you `Emit()` a message called `disconnect` form the server then the Socket will be closed. The relevant code is here: https://github.com/googollee/go-socket.io/blob/9c83c02fa6172eaea8252b6428e3cef3576c9746/socket.go#L64.

I'm willing to pull out the API into its own `.Close()` func if nobody's volunteering.

**Comment by krzysztofantczak** [comment]
Unfortunately it seems, that on.disconnect is triggered twice when closing socket with emit:disconnect.

**Comment by erkie** [comment]
Closing this issue because it is old. `so.Emit("disconnect")` works. If there is an issue with this please open a new ticket. Thanks!
