### ISSUE TITLE
access origins issue

### ISSUE THREAD

**Issue by BEZEI2K** [googollee/go-socket.io#70]
I am having issue connecting a client from localhost:3000 -> localhost:5000

The two apps have to be separate. How do I set the access-control header in this lib.

**Comment by navneetk** [comment]
I am also facing the same issue. How can I set Access-Control-Allow-Origin.

**Comment by googollee** [comment]
You can wrap the ServeHTTP to add custom http headers.

**Comment by BEZEI2K** [comment]
That worked thanks!
