### ISSUE TITLE
thread-safe way for server to emit/broadcast?

### ISSUE THREAD

**Issue by armhold** [googollee/go-socket.io#73]
Is there a thread-safe way to call `socket.emit` and `server.BroadcastTo` via server-initiated events? My use case is that the server will participate in a Redis pubsub, and relay those events to/from the sockets. The events will arrive from Redis asynchronously, so it's unclear to me how to safely deliver them to the sockets. 

The usual way of handling events in go-socket.io is via `server.On` and `socket.On`, but those functions register callbacks that are handled in the server's goroutine loop and the socket goroutine loops respectively. In the Node model of course it would be safe to call `emit`/`broadcastTo` here, as there is only a single thread of execution, but not so in Golang.

Ideally I'd give each socket a channel from which to receive events, and then when a Redis event happens, I'd send it to the channel. Something similar to that is described in [this example](http://gary.burd.info/go-websocket-chat). But I can't see how to properly implement that in the current architecture.

**Comment by googollee** [comment]
No, you should sync the calls yourself.
