### ISSUE TITLE
Looking for a go-socket.io-client implementation. Does this exist?

### ISSUE THREAD

**Issue by olibearo** [googollee/go-socket.io#75]
Looking to create a socket connection to a separate socket.io server using go.

**Comment by alu0075** [comment]
+1 , this is really useful

**Comment by sumory** [comment]
+1, this is really useful!
why remove the client implementation before "1.x" commit?

**Comment by nfirvine** [comment]
https://github.com/zhouhui8915/go-socket.io-client

But won't vouch for its effectiveness
