### ISSUE TITLE
Why does this piece of code work?

### ISSUE THREAD

**Issue by Netherdrake** [googollee/go-socket.io#76]
```
    server.On("connection", func(so socketio.Socket) {
        logger.Info("on-connect")
        so.On("bootstrap-start", func(json string) {
            logger.Info("bootstrap-start")
            go _onError(so, startBoot(json))
        })
        so.On("bootstrap-stop", func() {
            logger.Info("bootstrap-stop")
            go _onError(so, stopBoot())
        })
        so.On("disconnection", func() {
            logger.Info("on-disconnect")
        })
    })
```

`_onError` is a helper method that `Emit`s errors to the web app.

Now, what boggles my mind is, why, when I send `bootstrap-start` and then `bootstrap-stop` right thereafter (lets say a second later), but whilst `_onError(so, startBoot(json))` takes 20 seconds to run, I will get the `logger.Info("bootstrap-stop")` to run exactly after `bootstrap-start` finishes, despite the fact that there is no sync mechanism between the methods, and they both run in goroutines.

This is a desired behaviour, it just grinds my gears, why does it work?

**Comment by initrdmk** [comment]
Will ```runtime.GOMAXPROCS(n)``` affect this? It seems that the default cpu number is 1.

**Comment by Netherdrake** [comment]
I'm running `runtime.GOMAXPROCS(2)`
