### ISSUE TITLE
Emit() fails silently with special characters (utf...)

### ISSUE THREAD

**Issue by Simon-L** [googollee/go-socket.io#82]
When sending special characters like the french alphabet accents (é, è, à), socket.Emit() fails silently:
This fails:

``` go
errSo := so.Emit("results", "<strong>ééé</strong>")
fmt.Println(errSo)
```

This works:

``` go
errSo := so.Emit("results", "<strong>abc</strong>")
fmt.Println(errSo)
```

In both case `errSo` is `<nil>`.
I'm testing with a chrome browser using basic socket.io on the client side.

I've seen in another issue that utf characters are embedded in maps, should I do that ?

**Comment by linlexing** [comment]
+1

**Comment by cinnabardk** [comment]
The same issue exists with the special characters, æ, ø, å, in the Danish alphabet..

**Comment by ewaters** [comment]
I was running into this issue with the packaged /example/asset/socket.io.js. I downloaded the latest version of socket.io (https://cdn.socket.io/socket.io-1.3.7.js) and that seemed to fix the problem.

**Comment by Simon-L** [comment]
So the issue could have been on socket-io.js side?!
I stopped using go-socket.io in the meantime.

**Comment by erkie** [comment]
This issue is really old, so it's probably been fixed/or completely changed. Please open a new ticket if this is still an issue. Thanks!
