### ISSUE TITLE
Socket authentication

### ISSUE THREAD

**Issue by zygi** [googollee/go-socket.io#90]
Is there currently a way to access the Socket and the initial *http.Request at the same time to authenticate the user and keep track of their socket?

**Comment by googollee** [comment]
IMO, authentication should only relate to http.Request, because Request is only input in socket.io. You can authenticate with Request before passing it to ServeHTTP.

What's the detail makes you want to access Socket and Request at the same time?

**Comment by zygi** [comment]
For example, I might want to add a Socket to a certain room only of the user is logged in to the website. I could do this by authenticating via socket messages, but it would be much easier if I could access the cookies of the initial http request, check the authentication status and then add a socket to the room. 

Using js socket.io server I would do this with
```
io.use(function(socket, next) {
  var cookies = client.request.headers.cookie;
  if (checkAuthorization(cookies)) {
    socket.join("secretroom");
  }
  next();
});
```

**Comment by woodsaj** [comment]
You can access the net/http Request object by using the sockets `Request()` method.

```
server.On("connection", func(so socketio.Socket) {
    if checkAuthorization(so.Request().Cookies()) {
        so.Join("secretroom")
    }
}
```

**Comment by nguyenquocthao** [comment]
As I see now Socket is replaced by Conn, so there is no Request method. Is there another way?

**Comment by jimmywong123** [comment]
get the header when server onConnect
```go
server.OnConnect("/", func(s socketio.Conn) error {
    header := s.RemoteHeader()
    // do something with header
    // set to context
    s.SetContext("")
    return nil
})
```
