### ISSUE TITLE
How do you send a message to all clients but the one that sent you data?

### ISSUE THREAD

**Issue by ajusa** [googollee/go-socket.io#92]
Basically, I have a two player game that is updating the other with the current coords of each player. However, when I send the coords, and use socket.BroadcastTo, it sends it to the same player, and to the other player. How do I send data to everyone but the client who sent the data to me?

**Comment by DisruptiveMind** [comment]
@Ajusa are you using the actual socket or the server's BroadcastTo?

**Comment by Ajusa** [comment]
I no longer know. I switched to gorilla websockets a while back. However, I
believe I was using BroadcastTo
