### ISSUE TITLE
Crash occurs when too many arguments are passed.

### ISSUE THREAD

**Issue by johnwchadwick** [googollee/go-socket.io#95]
Similar to #71 but the other way around. It occurs because the argument count check occurs too late and we index into `c.Args` up to the last index in `args`.

**Comment by DisruptiveMind** [comment]
+1

**Comment by zhouhui8915** [comment]
+1
直接上图：
![socket io](https://cloud.githubusercontent.com/assets/13176899/9287234/5087008e-433d-11e5-9b30-27dab0ce7808.png)

**Comment by zhouhui8915** [comment]
+1
![socket io](https://cloud.githubusercontent.com/assets/13176899/9287266/d096d64a-433e-11e5-9d50-58a41378bb11.png)
