### ISSUE TITLE
Is there any socket.io client in golang

### ISSUE THREAD

**Issue by zhouhui8915** [googollee/go-socket.io#97]
i don't found any  socket.io client in golang,  Is there any socket.io client in golang?

**Comment by osiloke** [comment]
https://github.com/oguzbilgic/socketio

**Comment by nfirvine** [comment]
For future reference, looks like @zhouhui8915 went ahead and wrote their own: https://github.com/zhouhui8915/go-socket.io-client

Am trying it out currently, won't vouch for it yet.

**Comment by kamronbatman** [comment]
@nfirvine How is it working?

**Comment by nfirvine** [comment]
@kamronbatman I wouldn't describe it as production ready. For instance, I fixed a bunch of race conditions in it. So I'm concerned there's more danger lurking there. That said, besides those race conditions, I used it pretty heavily (5000 connections to a server), and it seemed to work.

**Comment by graarh** [comment]
https://github.com/graarh/golang-socketio, my library with client

**Comment by md2k** [comment]
@graarh , unable to locate 'funstream/libs/socket.io/transport', your example require it.

**Comment by graarh** [comment]
Thank you! I fixed import paths.

**Comment by md2k** [comment]
@graarh  welcome, i created a issue in your repository, check it when you have time.

**Comment by pavelnikolov** [comment]
@graarh I was just about to write my own and found that you've already implemented it! Thank you!

**Comment by yzx226** [comment]
nsq is what you want.
https://github.com/nsqio/nsq

**Comment by pavelnikolov** [comment]
@yzx226 if serves a completely different purpose. And even if he needed a queue or a pub/sub lib probably http://nats.io/ is a better option.

**Comment by Mountains-and-rivers** [comment]
> https://github.com/graarh/golang-socketio, my library with client

how reconnect should i do when disconnected

**Comment by Mountains-and-rivers** [comment]
how to  reconnect   when disconnected ？
